### ISSUE TITLE
DataFlash logging can cause flash corruption

### ISSUE THREAD

**Issue by tridge** [diydrones/ardupilot#10]
If you log messages too fast then the buffer to page async write may not have completed by the time you get to the next page. We need to ensure that when we start a new page that the previous buffer to page for that page has completed.

**Comment by TompsonTan** [comment]
I found my log file data also occur this problem. 
Does this bug have been fixed now?

**Comment by gmorph** [comment]
This is working in the current release of all vehicles.
If you believe differently please let me know.
Thanks, Grant.
