### ISSUE TITLE
Copter: prevent bad Z-vibrations causing rapid climb.

### ISSUE THREAD

**Issue by AndKe** [diydrones/ardupilot#1009]
Here's latest victim of AccZ vibrations,  http://diydrones.com/forum/topics/fly-away-please-help-me-figure-out-why

please note that IMU2 provided good data.
I know that this is a user/assembly error, but still, there should be some handling of this scenario - after all, we can still detect an altitude gain that contradicts desired altitude/(input)

**Comment by R-Lefebvre** [comment]
I wonder if this can be closed now?  Better filtering of the accels.  EKF.  Bad sensor rejection...  all coming with 3.3.

**Comment by rmackay9** [comment]
Yes, the increase in the accel range from 8G to 16G should fix this.  We've never actually tested this in a copter but I think we are fairly confident.

**Comment by vmayoral** [comment]
After these changes we actually started seeing the copters climbing. Refer to #2026

**Comment by rmackay9** [comment]
I'm closing this issue after all the work we've done to improve the vibration handling.  We can open a new issue when/if we see it happen with AC3.3 (or higher) versions.
