### ISSUE TITLE
Copter: add min RSSI voltage

### ISSUE THREAD

**Issue by shaggee** [diydrones/ardupilot#1061]
Some of LRS receivers provide 0,4-3.3V RSSI voltage. Maximum RSSI voltage in arducopter can be adjusted but minimum not. In this case RSSI with no RC signal shows arround 17% RSSI. With RSSI min value it can be calculated more accurately than now.

**Comment by StewLG** [comment]
https://github.com/diydrones/ardupilot/pull/2770 should address this.

**Comment by magicrub** [comment]
Closed per @StewLG 's comment
