### ISSUE TITLE
PX4: Add Spektrum Satellite Receiver Binding Support

### ISSUE THREAD

**Issue by billbonney** [diydrones/ardupilot#1076]
Add support to be able to bind Spektrum Rx Satellite radio directly when connect to a pixhawk without using the base receiver.
Support for this is in the PX4 stack, it just needs to be patched through to the APM code and the MAVLink command message MAV_CMD_START_RX_PAIR and MAV_CMD_PREFLIGHT_CALIBRATION using param4 set to 1

**Comment by EShamaev** [comment]
I have tried to do that but MAV_CMD_START_RX_PAIR is command 500. The Mission_Command.id in ardupilot is only 1 byte.
I am trying to understand this limitation now and why it is there.

**Comment by EShamaev** [comment]
OK. Now I am completely lost.
In mavlink protocol id is really 1 byte.
In GCS_Mavlink it starts from 1 byte and then becomes 2 bytes.
Then in AP_Message it is going back to 1 byte.

The MAV_CMD_START_RX_PAIR id is 500 which is more than 1 byte.
What is going on?

**Comment by EShamaev** [comment]
I have figured all out. MAVLINK_MSG_ID_COMMAND_LONG is used.
Another question: how to test the message from mission planner?

**Comment by EShamaev** [comment]
Support in Mission Planner was added.

https://github.com/diydrones/MissionPlanner/pull/898

**Comment by tridge** [comment]
This is now supported in ArduPilot master (thanks to Eugene)
