### ISSUE TITLE
fails to reach correct waypoint after radio failsafe with FS_THR_ENABLE=2

### ISSUE THREAD

**Issue by motion-man** [diydrones/ardupilot#1085]
AC3.1.0
This is a revisit of an old issue with the Throttle Failsafe.
In an Auto Mission with say 10 waypoints if there is a Throttle Failsafe and FS_THR_ENABLE=2 then i see from the logs The mode change from Auto->LAND->RTL->AUTO. This is normal as i understand it (Randy ?)
The copter does not lose altitude but stops and then heads back to the first waypoint as if restarting the Auto Mission from the beginning. It does not carry on with the next Waypoint after it would seem the Failsafe has returned.
When this used to happen it was strange and could not be repeated on the bench so Randy and I moved on but now i can see what seems to be really happening is the next waypoint is not reached and the copter heads back to the first Waypoint. I know it does this because i have a curve after my first waypoint and the copter after the failsafe heading to the first waypoint and then proceeded to the 3rd Waypoint so then i had to manually RTL. 

Can we check where the Waypoint Mission might be "reset" during a Throttle Failsafe ?

**Comment by rmackay9** [comment]
The issue here will be that the flight mode was changed by the receiver during the throttle/radio failsafe.
I think I'll close this issue if that's ok.

**Comment by motion-man** [comment]
Wow, bump.

Ok Randy.



On Tue, Jun 9, 2015 at 12:09 PM, Randy Mackay <notifications@github.com>
wrote:

> The issue here will be that the flight mode was changed by the receiver
> during the throttle/radio failsafe.
> I think I'll close this issue if that's ok.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/diydrones/ardupilot/issues/1085#issuecomment-110198264>
> .
>



-- 
regards
Matthew Dorhauer
Senior Sales / Applications Engineer
Motion Solutions Australia
NSW
ph.02 49452266
fax.02 49451206
mob.0407780802
VIC
ph.03 95630115
fax.03 95682667
matthew@motion-solutions.com.au
www.motion-solutions.com.au
