### ISSUE TITLE
Pixhawk: add support for PX4FLOW

### ISSUE THREAD

**Issue by matthewlloyd** [diydrones/ardupilot#1089]
I've had a PX4FLOW sitting on my shelf for over a year now and would love to be able to use it with ArduCopter. I hear it speaks Mavlink over its UART and reports X/Y velocities and sonar altitude so it should be pretty easy to integrate.

**Comment by TheBond** [comment]
Have you found out if it is working yet?
I see code for the PIX4FLOW and some youtube videos of people using it but I can't find out if it is supported.

**Comment by rmackay9** [comment]
@TheBond,
It's not quite ready yet but it's getting close.  it'll be supported in AC3.3.

**Comment by rmackay9** [comment]
This is in master now and will go out with AC3.3.

**Comment by Felixrising** [comment]
Awesome. I'll find some time to test it out... if my 4 month old will let me.
