### ISSUE TITLE
Copter: Option to activate buzzer after period of inactivity

### ISSUE THREAD

**Issue by jweymarn** [diydrones/ardupilot#1119]
Hi,
Related to #291 and #441 

To find a lost copter the option to activate buzzer by ch7/ch8 is great but I would like to have these channels free for other things. 

SO, if I could, in MP, __set the buzzer to start beeping after x minutes of inactivity__ this would achieve the same goal. I'll let the gurus decide how inactivity is defined and timed...

**Comment by R-Lefebvre** [comment]
Something like this was recently added with the lost aircraft finder function.  I think it's not automatic though.

**Comment by rmackay9** [comment]
yes, it can be done with a special combination of RC stick moves.  I think it's left stick down, right stick down-right.  I'm going to close this.. we need to document that stick moves in the wiki.
