### ISSUE TITLE
Unlimited count of waypoints for Pixhawk

### ISSUE THREAD

**Issue by buckker** [diydrones/ardupilot#1132]
I noticed that the pixhawk can only save the same count of waypoints like on the APM 2.6. With the powerfull pixhawk hardware it should be possible to save more waypoints.

Very nice would be the possibility to save a lot of missions on the pixhawk (sd card) and choose before the filght, which mission we will execute.

**Comment by rmackay9** [comment]
AC3.3 supports something like 700+ waypoints so I'm going to close this issue.
