### ISSUE TITLE
Copter: 2 level battery failsafe

### ISSUE THREAD

**Issue by sgofferj** [diydrones/ardupilot#1164]
We discussed this on drones-discuss a while ago. For various reasons, a 2 level battery failsafe would be useful, where level one RTLs or does whatever the user configures and level two LANDs.
For level one I could imagine e.g.
- RTL
- Fly to closest rally point
- Fly to specified waypoint (failsafe-point)
- Start beeping / flashing yellow

The main reason is that immediate LAND is not always desirable, e.g. when operating over water or over forest. A 2 level battery failsafe would give the operator the possibility to calculate and configure a battery level at which it is still safe to RTL/fly to a failsafe destination (see #1163) before LANDing.

Drones-discuss: https://groups.google.com/d/msg/drones-discuss/pj3FhDVQJBU/7nmhUnKmQoYJ

**Comment by squilter** [comment]
Replaced by issue #1759
