### ISSUE TITLE
Copter: only set "home" once the hdop of the GPS is below a suitable very safe threshold value , for example 2

### ISSUE THREAD

**Issue by davidbuzz** [diydrones/ardupilot#1201]
related issues: 
https://github.com/diydrones/ardupilot/issues/910
https://github.com/diydrones/ardupilot/issues/268
https://github.com/diydrones/ardupilot/issues/107
https://github.com/diydrones/ardupilot/issues/647

**Comment by R-Lefebvre** [comment]
Is this still relevant with current EKF?

**Comment by rmackay9** [comment]
Yes, with AC3.3 we now set the home based upon the EKF reporting that it's got a good origin.. and the EKF has some logic in there.. that involves the number of satellites and also some other checks..
