### ISSUE TITLE
Detect bad airspeed sensor (autocal)

### ISSUE THREAD

**Issue by jschall** [diydrones/ardupilot#1215]
I forgot to plug in the airspeed sensor on one of my planes. The plane still flew, which is good. It even flew very fast without going unstable, so it may have successfully failed over to using an estimated airspeed for scaling PIDs.

However, on the next flight, I found the AIRSPEED_RATIO to be 4.0 - it had still been trying to autocal while the i2c airspeed sensor was disconnected.

**Comment by magicrub** [comment]
Lets close this in favor of the other airspeed sensor issue https://github.com/diydrones/ardupilot/issues/1628 . Usually first issue stays but discussion is happening on the newer one.
