### ISSUE TITLE
incorrect initialization of MTK GPS in NMEA mode

### ISSUE THREAD

**Issue by notgood** [diydrones/ardupilot#1226]
If MTK GPS is being used in NMEA mode, incorrect initialization string is being sent to GPS, resulting no RMC messages and no date/time in arducopter logs.

From libraries\AP_GPS\AP_GPS_NMEA.cpp
    "$PMTK314,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0*28\r\n" // GGA & VTG once every fix
should be like this instead
    "$PMTK314,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0*29\r\n" // RMC, GGA & VTG once every fix

**Comment by WickedShell** [comment]
Closing as this appears to have been fixed in 20a04ba
