### ISSUE TITLE
Copter: allow Autotuning Roll or Pitch individually

### ISSUE THREAD

**Issue by dcwalmsley** [diydrones/ardupilot#1232]
I've run into constant problem attempting to complete autotune on my Y6 with 4S 6000 mAh battery and my X8 with 4S 8000 mAh battery.
I'm able to complete the roll sequence before I run out of battery before the pitch sequence has completed, thus the tuning is void.

Recommend that the autotune be designed into two types of tuning proceeses. 
1) Keep the process you have for those who can tune both roll and pitch on one battery and;
2) Second option for those who can't tune on one battery.  Break this test into to two tuning processes of which the pilot can complete the roll tuning on a battery then power off and swap batteries and take off and initiatiate pitch test.

**Comment by rmackay9** [comment]
There's an autotune bitmask parameter in AC3.3 that allows this.  Eventually we'd like to implement some new mavlink messages to allow the GCS to kick-off the autotune for whichever axis the pilot wants without having to fiddle with parameters but that's another issue.
