### ISSUE TITLE
Send 2nd GPS's data to ground station via MAVLink

### ISSUE THREAD

**Issue by Christian666** [diydrones/ardupilot#1242]
In order that mission planner can show either two GPS positions/map locations, or at least for showing satcount and hdop for both GPS modules, it's neccessary to send them over Mavlink simultaneously.
So satcount should be renamed to satcount1, hdop to hdop1, satcount2 and hdop2 should be added. 
A variable is needed which shows the weighting of GPS use by EKF.
Regarding missionplanner issue 492 where "NO GPS" is shown if GPS1 status=0, also the gpsstatus should be renamed to gpsstatus1 and gpsstatus2 should be added. 
https://github.com/diydrones/MissionPlanner/issues/492

**Comment by WickedShell** [comment]
Both GPS's information is sent to the ground station. The indicator for which GPS is primarily being used is not sent down at the moment but that's being tracked in a different issue already.

If I missed anything about this, it can be reopened.
