### ISSUE TITLE
Copter: easier compass calibration without ground station

### ISSUE THREAD

**Issue by rmackay9** [diydrones/ardupilot#1281]
There have been complaints that the compass calibration (currently all done in the mission planner) is too difficult compared to other flight controller.

The likely main cause of the complaints is that the mission planner's algorithm captures the compass values at only 10hz (leading to a lower number of points captured over the same amount of time as an onboard capture could manage) and it appears to have strict rules about capturing enough points from each sector (perhaps there are 6 or 8 sectors?.

The requested solution is to move the compass calibration into the main flight controller software (this will allow for up to an 80hz capture rate) and while the calibration will probably use the same gauss-newton calibration method that the MP does, we will reduce the strict requirement on the number of sectors.

Some complications:
1. this could require a chunk of RAM that the APM2 cannot provide
2. JonathanC has a more complicated compass calibration routine in the works which provides scaling in multiple directions.

It may be possible to do the compass calibration at the same time as the accelerometer calibration although there's a risk that this means putting the compass very close to the ground at points in the calibration which may lead to interference.

Video of Mikrokopter calibration method: http://vimeo.com/21602317

![anotherfc_compasscalibmethod](https://cloud.githubusercontent.com/assets/1498098/3792278/f0465904-1b6f-11e4-92ba-cbf0177d5be9.png)

**Comment by R-Lefebvre** [comment]
I think this got added recently due to Solo?

**Comment by rmackay9** [comment]
hasn' made it into master yet.

**Comment by rmackay9** [comment]
pushed to AC3.4.

**Comment by guiseco** [comment]
Hi ! How difficult is to this code working with apm 2.6 ??? I have a cheerson cx-20 that came with this functionality but he lost after update the stock firmware by 3.2.1

**Comment by rmackay9** [comment]
@guiseco, this is in the solo branch but not in master yet.  It should make it in for AC3.4.
I'm afraid we won't be able to back-port this large feature to AC3.2.1 which is the last version that is supported on the AVR CPU which is what the cheerson uses.  It's open source of course though, so if a developer turns up who wants to try then we will give them advice on how to do it.

**Comment by rmackay9** [comment]
This has been added to master and will go out with Copter-3.4.  It still requires enhancements to Mission Planner, AP2 and Tower.

**Comment by busyStone** [comment]
Hi,  @rmackay9  when calibrating, what's the correct way to move the copter?  I have tried many times but failed.

Thanks.

**Comment by rmackay9** [comment]
@busyStone, it's on the wiki but in any case, it shouldn't be too hard to make it succeed.

**Comment by busyStone** [comment]
@rmackay9  thanks for your quick reply. 

Use MP and Live calibration, I can calibrate it. 

I use PX4-v1 board, and upload the code of master branch to it, then calibrate the board with the on-board calibration, i got failed.

I tried the 6 sides rotate and the Solo rotate. Is there some thing special?

**Comment by busyStone** [comment]
@rmackay9 I changed CAL_FIT param to 10 (comment range 4 - 20), then got success.  Maybe, for me, it's too strict. o(^▽^)o

**Comment by rmackay9** [comment]
@busyStone, ah right.  So many parameters I'm beginning to forget some of them.  Yes, I think you're right that the default is perhaps too strict for your board (and likely for some others too).  Great you got it working.
