### ISSUE TITLE
Copter: accel calibration should fail or warn if roll-pitch trims set to max (10deg)

### ISSUE THREAD

**Issue by rmackay9** [diydrones/ardupilot#1283]
When performing the accel calibration the first stage is critical in capturing "level".  If the user makes a mistake and leans the vehicle then the vehicle may fly crooked from then on (until they re-do the calibration or run the savetrim/autotrim).

Currently we give no warning if hit these limits so noobies are left wondering why their vehicle aren't flying straight.

Another possibility would be to add this to the Log Analyser.

**Comment by R-Lefebvre** [comment]
I probably can do this one.  Prefer to do it during the process, not in logs.  Prevent the problem instead of diagnosing it after.

**Comment by rmackay9** [comment]
This has apparently been done by someone.
https://github.com/diydrones/ardupilot/blob/master/libraries/AP_InertialSensor/AP_InertialSensor.cpp#L440
