### ISSUE TITLE
Feature request; Log target waypoint/mission steps.

### ISSUE THREAD

**Issue by AndKe** [diydrones/ardupilot#1318]
All planned mission events, waypoints, DO set servi, and other mission items where logged.
Each step should be logged as active once AP gets to it.

**Comment by AndKe** [comment]
not really needed ?

**Comment by rmackay9** [comment]
If this request was to log all the mission commands at the beginning of the log (like plane does) then I think it's a good valid issue.

If the request was to log the commands as they're executed, then that is already being done.  They appear as CMD messages in the dataflash.  Also we report the active command to the GCS through one of the MAVLink messages (i forget one).

**Comment by JoshWelsh** [comment]
I thought I remembered submitting an enhancement request to log all mission commands at the beginning of the log, but I can't find it.  Maybe we discussed when you were in San Diego, I'm not sure, but I can't find the original request.  Happy to put one in if this request is for the latter..

**Comment by rmackay9** [comment]
Sure, a new request would be fine.  We actually attempt to log it but the logging happens before the logs are enabled normally because we only enable logs when we first arm the vehicle.

**Comment by AndKe** [comment]
Actually , what I was thinking, is that a event log (EV) could contain M1 M2...M3  etc. ,  but then I see it's only a int8_t , no room for all waypoints, it could be expanded to a parameter, but then it would be very redundant as CMD already does that, and if desired, we could get same neat "pointers" in the APM Planner graph to respond to logged CMD.Cnum  rather than log same data as events.
