### ISSUE TITLE
Arducopter 3.2 RC5 RC6 throttle issue after 2nd arm

### ISSUE THREAD

**Issue by j-lang** [diydrones/ardupilot#1333]
Configuration: Y6 copter, pixhawk, minimosd, 3dr telemetry 
Firmware: Pixhawk Y6 3.2-RC5
Issue: after a second arm, when moving throttle stick little up from zero position, the motors speed increases rapidly a little under take off speed.

Procedure:
Power up, 1st arm and slowly move throttle up, the motors raises their speed according to the throttle position. 
Then throttle to zero, disarm and arm again. 
move the throttle a little the motors switch to a speed a little lower than they need to hover the copter. when moving the throttle stick up, towards the mid position the motor speed is nearly the same. 

After unplugging the accumulator and repeating the procedure, there is the same effect. 
Screenshots:
- 1st picture when starting 1st time all motors have low output ch1-6 1107
- 2nd picture after 2nd arm: ch1-in very low motor output ch1-6 around 1300 and increasing very low
(At screenshots only the pixhawk is powered - not the motors. It is reproducible what happened outdoors)

![1st start](https://cloud.githubusercontent.com/assets/7978914/4021253/f27133b8-2aea-11e4-83fa-934d344e5724.png)   ![2nd start](https://cloud.githubusercontent.com/assets/7978914/4021255/f58b3dc8-2aea-11e4-8dc6-362825a2ade0.png)

**Comment by R-Lefebvre** [comment]
Is this still open? I did notice something like this in the past, but not lately.  There have been a LOT of changes to the throttle controller in AC3.3 and I'd be surprised if this bug still existed.

**Comment by j-lang** [comment]
I will check it within the next days and give feedback.

**Comment by rmackay9** [comment]
Ok, found the problem and fixed with this commit which will go out with -rc9.
https://github.com/diydrones/ardupilot/commit/0bf1d04172f4ecb975cdd60df32f4a5b6db02ada
