### ISSUE TITLE
Pixhawk: MPU6K DLPF not being set

### ISSUE THREAD

**Issue by rmackay9** [diydrones/ardupilot#1370]
the INS_MPU6K filter is not being applied to the hardware on the pixhawk/px4.  It is being applied to the software filter (which is good).

Thanks to Steve McLaughlin for the report

**Comment by R-Lefebvre** [comment]
Should this be closed?

**Comment by R-Lefebvre** [comment]
Ok, now I really think this closes this issue:

https://github.com/diydrones/ardupilot/pull/1964#issuecomment-78410963

**Comment by rmackay9** [comment]
yup, let's close this.
