### ISSUE TITLE
MAX and MIN RX RSSI value

### ISSUE THREAD

**Issue by taedla01** [diydrones/ardupilot#1377]
Hello everyone,

Seeing in Ardupilot PARAMS, I found that it possible to adjust MAX RX rssi value and set a RSSI_PIN for load rssi value.
I have several legacy Thomas Scherrer LRS systems working on now with ardupilot. My rssi values are between 0,5 – 1,5 volts (aproximately).
Maybe a new PARAM (MIN RX RSSI) could be a good thing for make rssi reads more accurate.
In MininOSD Extra project (derived from ArduCAM OSD), the actual code and Config Tool makes easy adjust rssi values for visualize it then in OSD.

I think best is that Ardupilot will make possible those adjusts. More accepted range of RX means a more universal device.

Thanks for your effort.

Regards from Spain,
Dario.

**Comment by StewLG** [comment]
Yes, you can do it in MimimOSD, but I agree that this should be done properly in ArduPilot itself. This change should fix things for you:

https://github.com/diydrones/ardupilot/pull/2770

**Comment by magicrub** [comment]
Closed per @StewLG 's comment
