### ISSUE TITLE
AntennaTracker: have minimal distance

### ISSUE THREAD

**Issue by nhadrian** [diydrones/ardupilot#1407]
Hi,

My suggestion would be to make a parameter for minimal distance (ie. MIN_SCAN_DIST in m), and if distance between vehicle and tracker is smaller than that parameter, tracker freezes the movements. So if tracker is set up on a mobile ground station or a transmitter case, it will not start crazy bouncing when too close.
And, even directional antennas have some 360 degrees radiation pattern.

Regards
Adrian

**Comment by rmackay9** [comment]
Thanks for the enhancement request.  I've added a DISTANCE_MIN parameter to the tracker 0.5 with this commit.  https://github.com/diydrones/ardupilot/commit/404df7fe7d9ef5aa8f016cbee8cc0521ca7e9e17

This should appear in the MP in about 1.5hrs from now.
