### ISSUE TITLE
Copter: allow selecting more than 6 flight modes via transmitter

### ISSUE THREAD

**Issue by IllusionPerdu** [diydrones/ardupilot#1438]
Hello,

I think with the time the ardupilot have implement many "Flight Modes"  and now 6 select "Flight Modes" selection is not reasonable ;)

Actualy  :
* it's possible to selec 6 "Flight Modes" but they're 13 "Flight Modes" !
* to configure the radio we use many time some switch 
If we use 2 switch with 3 positions we can do in theory 9 "Flight Modes".

**It's possible to change the "Flight Modes" configuartor to do assign this 9 modes ?**

Idea (admit the pwm is 1000 to 2000) : 

if we have only 2 position in radio ( the range is *round((2000-1000)/2)=500* ) =>
1000 -> 1500 : mode 1 
1500 -> 2000 : mode 2

....

if we have 7 position in radio ( the range is *round((2000-1000)/7)=142* ) =>
1000 -> 1142 : mode 1
1142 -> 1284 : mode 2
1284 -> 1426 : mode 3
1426 -> 1568 : mode 4
1568 -> 1710 : mode 5
1710 -> 1852 : mode 6
1852 -> 2000 : mode 7

....

**What do you think about this ?**

**Comment by magicrub** [comment]
holy crap, you guys are actually talking about using 3 or 4 switches? That's nuts. I agree with Randy, if you need that much control then you should be on a tablet or some other MAVLink interface.

**Comment by R-Lefebvre** [comment]
I think this should be closed.  With the recent addition of more Aux Switch options, we have even more possibility for assigning modes on extra switches.  I'd rather extend Aux Switch to all 16 channels rather than make the change requested here.  More than 6 modes is madness.

**Comment by rmackay9** [comment]
Ok, closing.

**Comment by roycruse** [comment]
Id really like more than 6 modes -  easilly achived with the 6 mode buttons in a tx16s plus a second 2 or 3 way toggle giving 12 or even 18 mode selections.

My main use case at the moment is I want to try out all the modes.   ive got my 6 modes set to manual, acro, cruise, auto_takeoff, loiter, rtl but would like to try other modes out also.   especially if i start running autonomous missions etc

**Comment by rmackay9** [comment]
Hi @roycruse,

Auxiliary function switches can also be setup to change the vehicle into another mode and all the standard ground stations support changing into any available mode.  I think for testing (which is greatly appreciated) using the GCS is the best way.
![image](https://github.com/ArduPilot/ardupilot/assets/1498098/dfbb804a-2875-4761-ab15-c94898acd39f)
