### ISSUE TITLE
Copter: tilt in the direction the stick is pushed in stabilize & alt-hold modes

### ISSUE THREAD

**Issue by jschall** [diydrones/ardupilot#1452]
Currently, stick forward is pitch euler angle and stick right is roll euler. Since euler angles are ordered rotations, putting your stick in the top right corner causes the copter to accelerate more to the right than forward. i.e. not in the direction of your command.

**Comment by R-Lefebvre** [comment]
I think this was completed?

**Comment by rmackay9** [comment]
Yes, done, thanks.
