### ISSUE TITLE
Add AMP_OFFSET parameter

### ISSUE THREAD

**Issue by ethomas997** [diydrones/ardupilot#149]
Add AMP_OFFSET parameter to support current monitors that output 2.5V at zero current (like Allegro acs756).  This parameter as been added to the ArduPlane code; would like to see it added to ArduCopter.  There's a forum post on this here:  http://diydrones.com/profiles/blogs/allegro-acs756-current-sensor-for-arducopter

--ET

**Comment by gmorph** [comment]
This is in the Copter release so closing this out.
If you believe differently please let me know.
Thanks, Grant.
