### ISSUE TITLE
Copter: jump in altitude when EKF becomes available

### ISSUE THREAD

**Issue by jschall** [diydrones/ardupilot#1494]
If you get up in alt-hold before EKF becomes available, and subsequently EKF becomes available, the copter will very suddenly either fall a bit or climb a bit. This is very scary and could cause a crash if low.

I think our ultimate goal for the behavior should be this:
- EKF becomes available faster - no GPS, only estimating height and attitude, not position and velocity.
- Pre-arm check makes it impossible to arm before EKF is ready
- Really, we should have a pre-arm check for "home position set." It doesn't make much sense to allow an RTL (and especially not an RTL with a land) to a home position that was set in-flight.
- We should probably just go into an "indoor mode" when you arm with no GPS. Play a different buzzer tone, regularly play a warning tone, and disallow non-manual modes until the user lands, disarms, and then arms again. "Indoor mode" should also be force-able by arming with a different stick gesture.
- In the meantime, we should probably by default disallow arming before a home position is set. I'll make a separate issue.

**Comment by rmackay9** [comment]
With AC3.3 we should no longer have this issue because there's no switch between EKF and inertial nav anymore (because inertial nav is gone).
