### ISSUE TITLE
AntennaTracker. Proxy mode does not pass actions through from Mission Planner

### ISSUE THREAD

**Issue by AndrewCollier42** [diydrones/ardupilot#1504]
When running Antenna Tracker in proxy mode all seems to be working well, however we cannot set flight modes of the vehicle via Mission Planner (Flight data, Actions). Waypoint uploading, joystick and rc mode re-assignment works. and all else works so far however we have a critical need for being able to set modes as we often fly out past 20km and have no rc radio control to reset modes should the need arrive.

**Comment by rmackay9** [comment]
We've removed the proxy mode now and instead use a more standard message forwarding method that's shared with all other vehicle types.  I've tested updating the vehicle's flight mode and it seems to work so I'm closing this issue.  We can reopen it though if you find it doesn't work.
