### ISSUE TITLE
Copter: disable fence temporarily after GPS glitch

### ISSUE THREAD

**Issue by jschall** [diydrones/ardupilot#1516]
Not a particularly new piece of information, but I didn't find an issue for this in a cursory search.

On copter, a GPS glitch can cause a fence breach which causes an attempt to RTL with a bad GPS. This causes the copter to lean over hard and hit the nearest tree.

There's really 2 issues here - RTL should return false under these conditions (when it isn't really sure that it can get us home), and fence should not trigger based on a spurious location.

There's an example of this issue here: http://ardupilot.com/forum/viewtopic.php?f=80&t=10033
The GPS completely cuts out during RTL, but we don't stop trying. Perhaps this is fixed in 3.2?

**Comment by R-Lefebvre** [comment]
Is this still AC3.3 Candidate?  Seems a bit late to start experimenting with critical safety interfaces this late in the game?  Can this even occur with EKF?

**Comment by rmackay9** [comment]
I don't think this is valid anymore so closing.
