### ISSUE TITLE
Copter: Circular limits for pitch/roll axes

### ISSUE THREAD

**Issue by jolyboy** [diydrones/ardupilot#1531]
Feature request for a circular limit on pitch and roll axes, as discussed here:

https://groups.google.com/forum/m/#!msg/drones-discuss/23tugDhdJlE/KONqXiVKtegJ

This is essential to the feel of copter, especially acro type flying. This is also critical to the basic function of attitude control on TradHeli to ensure mechanical limits cannot be exceeded.

I have a working sketch for circular limits on input side for copter, and also output stage for TradHeli. It doesn't make sense to me to apply circular limits to output for multicopters, bit can add it if required.

**Comment by R-Lefebvre** [comment]
Can this issue be closed? It appears a subsequent PR has been accepted which addresses this issue?

**Comment by rmackay9** [comment]
The circular roll/pitch input part has been done for multicopters so yes, maybe it can be closed.  I think I left it open because there were some other bits in the pull request from Joly that I didn't merge.

**Comment by R-Lefebvre** [comment]
Yes, I think we still have to integrate the circular swash plate limits for Tradheli.  I think this should be done on a separate issue/PR.  Joly, if you've got code for that, can you please make a separate issue/PR and assign it to me?  I hope to get to your stuff soon.
