### ISSUE TITLE
Copter: Pirouette compensation

### ISSUE THREAD

**Issue by jdsaund** [diydrones/ardupilot#1532]
Feature request for pirouette compensation for TradHeli. This is important for acro type flying because it ensures that the attitude of the machine is accurately held during rapid yaw. This type of feature will attract more users because it brings the acro code up to spec with the vast majority of heli controllers.

**Comment by R-Lefebvre** [comment]
To be included in AC3.3 for Heli

**Comment by R-Lefebvre** [comment]
Closing, this is in Master and AC3.3 now.
