### ISSUE TITLE
add L1 xtrack error to DF log

### ISSUE THREAD

**Issue by tridge** [diydrones/ardupilot#1538]
should log L1 internal error in DF logs

**Comment by magicrub** [comment]
done in Plane v3.4 but I think it was integrated much earlier than that. Probably v3.2.

**Comment by magicrub** [comment]
whoops, my mistake it was only over MAVLink. Here's a PR to add it to DF logs. https://github.com/diydrones/ardupilot/pull/3435 This is small enough that it could sneak into Plane v3.5

**Comment by magicrub** [comment]
closed via https://github.com/diydrones/ardupilot/pull/3435
