### ISSUE TITLE
Plane: TECS issue about the function _update_height_demand

### ISSUE THREAD

**Issue by NUAAFLY** [diydrones/ardupilot#1546]
_hgt_dem  is the value of relative_target_altitude_cm(), which is updated at 10Hz, so the process of _hgt_dem below may be wrong?

      // Apply 2 point moving average to demanded height
	// This is required because height demand is only updated at 5Hz
	_hgt_dem = 0.5f * (_hgt_dem + _hgt_dem_in_old);

**Comment by magicrub** [comment]
This code is fine, it's just an averaging filter. Add two samples and divide by two (x0.5).
 Thanks for the catch @NUAAFLY , I'll update the comment so its not misleading.
