### ISSUE TITLE
Plane: TECS issue about function AP_TECS::update_pitch_throttle

### ISSUE THREAD

**Issue by NUAAFLY** [diydrones/ardupilot#1547]
I think function  _update_speed() should be executed after inputs converting. 
Because the value of  _EAS_dem in _update_speed() is not the latest value of Equivalent airspeed demand.

        _update_speed();
	// Convert inputs
	_EAS_dem = EAS_dem_cm * 0.01f;

**Comment by WickedShell** [comment]
@tridge, @priseborough, or @magicrub  is this a correct catch? If not can someone close it, I'm inclined to think he's correct but I'm not familiar enough with TECS to be sure on that.

**Comment by priseborough** [comment]
Given that _EAS_dem is only used inside _update_speed(), yes I would change the order as it introduces an unnecessary 1 frame delay in executing airspeed demand changes.  It's not urgent but is an easy no-brainer fix.

**Comment by magicrub** [comment]
There's a long thread talking about this somewhere

**Comment by magicrub** [comment]
My mistake, I was thinking of this one: https://github.com/diydrones/ardupilot/pull/2860

**Comment by magicrub** [comment]
fixed https://github.com/diydrones/ardupilot/commit/da01ceee53eaaf8610ed799fb58c85aa0d0732a1, thank you @NUAAFLY !
