### ISSUE TITLE
add microSD format to NuttX

### ISSUE THREAD

**Issue by tridge** [diydrones/ardupilot#1608]
useful for bad microSD cards

**Comment by abvgeej** [comment]
ext* would be useful (even through i recommend reiserfs), but fixing the partition seems like a overkill.
I would prefer to have a possibility to write in raw. Just to write the logs directly to the card.

**Comment by magicrub** [comment]
What advantage does ext have on an sd card? The idea if using the
traditional FAT is to make it portable to be read on various computers

**Comment by rmackay9** [comment]
Tridge has implemented the original request which is to format the card from Nuttx so closing.
