### ISSUE TITLE
Make Fly-By-Wire Low Altitude Limit function also work for FBW-A but not only for FBW-B

### ISSUE THREAD

**Issue by FPVs8** [diydrones/ardupilot#161]
The Fly-By-Wire Low Altitude Limit function only works for FBW-B but not for FBW-A? I don't have an airspeed sensor so I can only use FBW-A. This would be a great safety function to have especially when flying FPV if you go too low :) (I am using this for Arduplane not Arducopter if that matters)

**Comment by gmorph** [comment]
This functionality works even if you don't have an airspeed sensor - see here:
http://plane.ardupilot.com/wiki/fly-by-wire-low-altitude-limit/
Further, you can and should use the geofence to achieve this functionality.  Closing this out.
Thanks, Grant.
