### ISSUE TITLE
increasing number of input channels for APM2

### ISSUE THREAD

**Issue by KIrill-ka** [diydrones/ardupilot#1625]
Would you consider increasing AVR_RC_INPUT_NUM_CHANNELS to 11 in AP_HAL_AVR/RCInput.h?
For ArduPlane this is the only change needed to make ch10 and ch11 to work as input channels. ch9 also can be used for some functions (e.g. modeswitch, mission reset).
By the way, I've implemented  S.BUS firmware for atmega32u2. If you are interested, I'll push the code to github so you can check it out.

**Comment by gmorph** [comment]
This has been done and put into master.
https://github.com/diydrones/ardupilot/pull/1804
Thanks!
