### ISSUE TITLE
Copter: revise the yaw rate controller

### ISSUE THREAD

**Issue by robustini** [diydrones/ardupilot#1635]
The yaw rate controller is always a little bit "lazy", is a problem already discussed but never resolved.
The comparisons I've done with other systems, and unfortunately I always found this problem in our Copter, also playing with the parameters compensates too little or overcompensate.
We must be able to eliminate the tendency to "bounce" and gain altitude.
This thing is highlighted when using ESC reflashed with SimonK or BLHeli, especially using the damped.

**Comment by robustini** [comment]
@jschall: what do you think to ask Randy to try it?

**Comment by rmackay9** [comment]
I bow to the better judgement of Paul, Jon and Leonard.  If those 3 agree Jon's method is better, then that's all we need to move to master.

**Comment by lthall** [comment]
I think this can be closed. We have implemented a dramatically improved yaw controller in 3.3 combined with autotune. I have not seen any complaints.
John's work here was some early experiments that evolved into what is in 3.3.
If this is still an issue I would like to see this detailed in the 3.3 discussion along with autotune logs for Yaw and logs showing the problems.

**Comment by rmackay9** [comment]
ok, Closing.  others can object if they'd like it reopeened and we can do that.
