### ISSUE TITLE
Dataflash: move vehicle specific messages to Dataflash lib

### ISSUE THREAD

**Issue by rmackay9** [diydrones/ardupilot#1671]
One of our long term objectives is to increase the amount of code sharing between vehicles by moving as much as possible into shared libraries including the dataflash library.  After a short review by Tridge and Randy, these messages should be combined so that at least the dataflash structure is shared between the vehicles:
attitude  <-- Tridge is happy for the plane to populate the Desired Roll, pitch, yaw just as copter does
performance
cmd message
mode
sonar
arm/disarm
compass
current  <-- Randy is happy to remove throttle integrator from copter

**Comment by R-Lefebvre** [comment]
Can this be closed now?

**Comment by rmackay9** [comment]
Yes.  There may be some other messages but we can raise a new issue issue when we find those.

**Comment by R-Lefebvre** [comment]
I know that Performance is still not commonized, but there are significant differences between them we'd have to get agreement between Copter and Plane for what to do.
