### ISSUE TITLE
APM2 bootloader: unjustified firmware size limit

### ISSUE THREAD

**Issue by KIrill-ka** [diydrones/ardupilot#1673]
Bootloader size is 8k, but it limits firmware size to 0x3c000 which is 256k-16k.
This looks like a bug in bootloader
Tools/APM2_2560_bootloader/stk500boot.c:
    #if FLASHEND > 0x0F000
        #define BOOTSIZE 8192
    #else
        #define BOOTSIZE 2048
    #endif
    #define APP_END  (FLASHEND -(2*BOOTSIZE) + 1)

**Comment by gmorph** [comment]
Hi Klrill-ka.  Are you going to submit a pr for this change?  Thanks.

**Comment by KIrill-ka** [comment]
I'm going to prepare github branch with 2k bootloader code. There's minimalistic doc (FLASH.txt) among the bootloader sources. It will be updated to show how to change fuse bits to match the bootloader size.

**Comment by KIrill-ka** [comment]
2k bootloader: 162597c2173d1e6738753ed9ff21688343341687

**Comment by taedla01** [comment]
This is the last solution for integrate newer options into older AVR 2560 boards... Thanks @KIrill-ka!

**Comment by squilter** [comment]
Plane and Copter have now dropped APM2, so unfortunately I don't think it's worth pursuing this any more.
