### ISSUE TITLE
catch MPU6k hardware failures using WHOAMI register

### ISSUE THREAD

**Issue by rmackay9** [diydrones/ardupilot#1706]
We have discovered about 38 cases where users have flown with MPU6k accelerometer failures during user's flight.  Because we are able to read back values from the accelerometer (ie.. they don't go to zero) our current health checks don't immediately catch the problem.  Sometimes this leads to a crash and other times the weighting of the accels (especially with the EKF) allows the vehicle to continue it's flight successfully.

We need to ensure both the user knows of the failure and that DCM, EKF and Inertial Nav do not use the bad accelerometer.

Note that if the failure happens before take-off the Copter pre-arm checks catch the problem (incidentally some users foolhardily turned off the pre-arm check to allow the vehicle to fly but this can't be helped).

**Comment by tridge** [comment]
this is implemented in master now
