### ISSUE TITLE
DO_MOUNT_CONFIGURE & DO_MOUNT_CONTROL not implemented in ArduPlane mission scripts

### ISSUE THREAD

**Issue by billbonney** [diydrones/ardupilot#171]
In ArduPlane you cannot set the MOUNT mode or control the camera with a Mission Script. You can send MAVLink msgs in real-time to do it, but it's not a feature I could see in Mission Planner.

This is a request to add the scripting commands to ArduPlane (I haven't checked ArduCopter to see if its the same)

see http://diydrones.com/forum/topics/no-help-in-the-forums-so-far-i-will-paypal-someone-20-if-they-can

see AP_Mount.cpp Line 550

```C++
/// Set mount configuration, triggered by mission script commands
void AP_Mount::configure_cmd()
{
    // TODO get the information out of the mission command and use it
}

/// Control the mount (depends on the previously set mount configuration), triggered by mission script commands
void AP_Mount::control_cmd()
{
    // TODO get the information out of the mission command and use it
}
```

**Comment by rmackay9** [comment]
I think these are implemented in master now so closing.
https://github.com/diydrones/ardupilot/blob/master/libraries/AP_Mount/AP_Mount_Backend.cpp#L30
