### ISSUE TITLE
latitude and longitude values are not updated

### ISSUE THREAD

**Issue by bnurbekov** [diydrones/ardupilot#1730]
Hi,

First of all, my GPS is off. I turned it off in order to be able to try to hold the position in the air relying on the current velocity purely (since I am indoors).
So, here goes the problem. Whenever I try to call inertial_nav.get_latitude() or inertial.get_longitude() I get 0's as the return values (I print these values in userhook_FastLoop() function). Could you please help me with this issue?
However, when I upload AP_InertialNav_test.pde I get some non-zero values.

Thank you in advance!
Ben

**Comment by R-Lefebvre** [comment]
Those values are not updated because the GPS is turned off.  The system is designed to work with GPS only.
