### ISSUE TITLE
Use mavlink_gps_raw_int_t to send current active GPS

### ISSUE THREAD

**Issue by emilecastelnuovo** [diydrones/ardupilot#1734]
If using 2 GPSs and the primary fails (or it is not used) GCS's are not aware of the GPS switch and will always display the GPS on port 1 (UartB).

It would make sense to send the active GPS status to the GCS that should not know if there are more than one available and which one the flight control is using.

Maybe an idea would be to do like the AHRS2 log, where it holds the info about the secondary AHRS and switches between EKF and DCM when using DCM or EKF respectively.
 
So maybe mavlink_gps_raw_int_t should contain the active GPS, while mavlink_gps2_raw_t should have the secondary (if available) GPS info.

**Comment by WickedShell** [comment]
Closing this as this is not the correct approach for reporting which GPS is the primary GPS. That should be reported elsewhere, but swapping the underling GPS instance that is used to fill in the GPS_RAW_INT message will produce confusing logs and generally serve to mask GPS related problems. The reasons that tridge closed #1810 here, #2572 is tracking the proper reporting of this
