### ISSUE TITLE
copter: need to fill in NAV_CONTROLLER_OUTPUT for RTL

### ISSUE THREAD

**Issue by tridge** [diydrones/ardupilot#1735]
copter needs to fill in NAV_CONTROLLER_OUTPUT.target_bearing and wp_dist for all automatic navigation modes, including RTL. Otherwise the GCS cannot display the point that the copter is heading towards, which is very confusing when using rally points.
Note that GUIDED mode has the same issue.

**Comment by rmackay9** [comment]
Thanks for finding this.
fixed with this commit:https://github.com/diydrones/ardupilot/commit/f54a13f24bb7925453691ad62731bbd292db9ab0
