### ISSUE TITLE
ArudRover2 v2.40 beta code does not indicate GPS 3D lock on Oilpan red led

### ISSUE THREAD

**Issue by TC3** [diydrones/ardupilot#174]
Since updating to ArduRover2 v2.40 beta code I have found that when the GPS is indicating a 3D lock the red led on the Oilpan, used to indicate a 3D lock, is no longer functional in that respect. The led works fine otherwise. Not having an indication from the APM of a 3D lock is a bit disconcerting when not communicating with the MP over the Mavlink.

Tom C

**Comment by gmorph** [comment]
Checking with TomC if this can be closed.

**Comment by TC3** [comment]
Hi Grant, 

Can definitely be closed! 

Regards, 
Tom C AVD 

----- Original Message -----

**Comment by gmorph** [comment]
Thanks!  Closed!
