### ISSUE TITLE
Copter - Log all mission commands/waypoints to dataflash when vehicle arms

### ISSUE THREAD

**Issue by JoshWelsh** [diydrones/ardupilot#1746]
For troubleshooting purposes it would be helpful to know what the mission is that a copter has programmed when it arms.  This will help streamline post-analysis of logs for data examination as well as user support and remove the need to ask the question, "can you send me the mission as well?"

I would say this is a low priority, nice to have thing, but helpful nonetheless.

**Comment by touma-setsuna** [comment]
The Great Firewall prevented me from uploading everything. I've tried 10 times to upload 2 images. Looking for Stable&Free “ladder”......

**Comment by rrr6399** [comment]
Logging the initial mission definition is definitely needed for troubleshooting. Any mission updates during flight should also be logged as well.

**Comment by R-Lefebvre** [comment]
I'll see if I can do this with my other logging changes I'm working on.

**Comment by rmackay9** [comment]
Tom Pettinger has added this to AC3.3.
