### ISSUE TITLE
Expand Ch7/8 Aux-Function Channels

### ISSUE THREAD

**Issue by R-Lefebvre** [diydrones/ardupilot#1749]
There are many possible functions which can be assigned to Ch7/8 aux-functions, but only 2 channels possible to control them.  There are also plenty of low-cost RCTx units available with more than 8 channels.  We should add at least 2 more possible channels for Aux Functions.

Ideally, Aux-Function control should move into a common-vehicle library.  But at the least for AC3.3, I'd like the existing Ch7/8 function expanded to 9 and 10.

**Comment by robustini** [comment]
+1

**Comment by multigcs** [comment]
my patch for v3.2
http://www.multixmedia.org/test/ardupilot-ch9-ch12.diff

**Comment by R-Lefebvre** [comment]
Nice.

**Comment by robustini** [comment]
Thanks multigcs! When in the master? ;-)

**Comment by JSGordon** [comment]
+1

**Comment by rmackay9** [comment]
This is in master now.  We may have accidentally not given proper credit to multigcs.  I apologise profusely for that.  Rob's changes are a superset of yours but I could have set the name on one of the patches to be multigcs.  Hmm, really sorry about.  I'll try and make it up to you some how.
