### ISSUE TITLE
TradHeli: Circular swash-plate limits

### ISSUE THREAD

**Issue by jdsaund** [diydrones/ardupilot#1755]
As discussed, request to add circular swash-plate limits for TradHeli -- @R-Lefebvre 

Current PR is located here  #1754
***** I am totally unable to compile or upload (currently at sea) so I would really appreciate your help verifying the integrity of this code.

**Comment by jolyboy** [comment]
As a side note, this code did compile and bench test OK as part of the previous PR. 

This PR uses a freshly rebased master and cherry picked commits, so needs verification that nothing has gone pear shaped in the process.

**Comment by R-Lefebvre** [comment]
Rebased and PR'd here:

https://github.com/diydrones/ardupilot/pull/2970

**Comment by R-Lefebvre** [comment]
Closing this, fix is merged into Master and AC3.3.
