### ISSUE TITLE
Copter: Reason for the arm failure

### ISSUE THREAD

**Issue by gtiramani** [diydrones/ardupilot#1763]
When it is impossible to arm for the failure of the pre-arm check,  would be very useful to display on the screen the element that does not allow to arm copter

**Comment by squilter** [comment]
It usually does give a reason.  Do you know under what situation it didn't in your case?

**Comment by robustini** [comment]
The real problem is that the message appears but then shortly he leaves.
I think this a Planner "issue", not in the code.

**Comment by R-Lefebvre** [comment]
Can this be closed?  Seems most failures are well reported?

**Comment by rmackay9** [comment]
Yes, I think they're all reported now.
