### ISSUE TITLE
Plane:Error comment in parameter LAND_PITCH_CD

### ISSUE THREAD

**Issue by jinchengde** [diydrones/ardupilot#1776]
in the Parameters.pde, it is comments that it is in function without airspeed sensors

    // @Param: LAND_PITCH_CD
    // @DisplayName: Landing Pitch
    // @Description: Used in autoland for planes without airspeed sensors in hundredths of a degree
    // @Units: centi-Degrees
    // @User: Advanced
    ASCALAR(land_pitch_cd,          "LAND_PITCH_CD",  0),

  but actually, it is used in final stage whether or use airspeed sensors in AP_TECS.cpp

  if (flight_stage == FLIGHT_LAND_FINAL) {
        // in flare use min pitch from LAND_PITCH_CD
        _PITCHminf = max(_PITCHminf, aparm.land_pitch_cd * 0.01f);
        // and allow zero throttle
        _THRminf = 0;
    }

**Comment by tridge** [comment]
thanks for reporting that! I've pushed an improvement to those docs along with some of the other landing docs.
http://plane.ardupilot.com/wiki/flying/automatic-landing/
