### ISSUE TITLE
How to add new library into ardupilot and can use "make"

### ISSUE THREAD

**Issue by jwfjia123** [diydrones/ardupilot#1777]
I want to add a new navigation library into the ardupilot libraries, it is called AP_Nav_UKF including AP_Nav_UKF.cpp and AP_Nav_UKF.h, and I add #include <AP_Nav_UKF.h> in the arducopter.pde, but using "make px4" comes an error:

fatal error: AP_Nav_UKF.h: No such file or directory

the wiki does not mentioned how to add new library, can anyone help me?

**Comment by rmackay9** [comment]
jwfjia123,
Probably better to email drones-discuss@googlegroups.com or you can join Gitter.
https://gitter.im/diydrones/ardupilot
