### ISSUE TITLE
Compass dev id changed after PX4Firmware changes

### ISSUE THREAD

**Issue by jschall** [diydrones/ardupilot#1794]

**Comment by tridge** [comment]
this should be fixed in master now. Jon, please test

**Comment by rmackay9** [comment]
Hi there, this problem crept in after we branched for AC3.2.1. right?

**Comment by tridge** [comment]
better check the devid to be sure - it depends on the PX4Firmware version

**Comment by rmackay9** [comment]
This seems all good to me so I'm closing this.

I tested AC3.2 vs AC3.2.1 vs master and all had DEV_ID = 73225 and DEV_ID2 = 131594.  I tried removing the external compass and the 131594 id properly shifted from ID2 to ID.

**Comment by jschall** [comment]
Thanks Randy.
