### ISSUE TITLE
Where the modified ArduCopter procedure for the 6 axis

### ISSUE THREAD

**Issue by luo674526417** [diydrones/ardupilot#1795]
Where the modified ArduCopter procedure for the 6 axis

**Comment by rmackay9** [comment]
I guess this is a support question but it's unclear what the "6-axis" refers to.  Accel, gyro, compass?  is it a calibration routine that's being looked for?

**Comment by luo674526417** [comment]
Firmware flight six axis that part in the changes in the ArduCopter
