### ISSUE TITLE
How to use Ubuntu to compile ArduCopter, supply using Px4

### ISSUE THREAD

**Issue by luo674526417** [diydrones/ardupilot#1796]
How to use Ubuntu to compile ArduCopter, supply using Px4

**Comment by luo674526417** [comment]
How to use Ubuntu to compile ArduCopter, supply using Px4

**Comment by rmackay9** [comment]
Dev wiki is here including a section on how to build the code.
http://dev.ardupilot.com/wiki/building-the-code/
