### ISSUE TITLE
The GPS don't find any satelites (ublox, Firmware  v3.2.1-rc1)

### ISSUE THREAD

**Issue by micaelkarlsson** [diydrones/ardupilot#1818]
Hello

I have two problems:

1. Cant connect to Command Line Interface (CLI).
2. The GPS dont find any satellites.

I have two APM 2.6, each has it's own GPS (ublox).Have two copters, one X4 and one Y6. X4 is working but I have problem with the Y6 setup copter.

I have tried both beta and stable firmware, right now I have: v3.2.1-rc1 (0c3f43b2) in the controller.

Question 1
Think I found answer for that one. The CLI interface is removed from version 3.2 and up. Is hat correct? I would like to do a motor check and check the health on GPS, but I think it's not possible.

Question 2
I don't think it is any problem with the GPS module. I have checked the power module output voltage to Flight Controller, it is 4.87. I have had it outside searching for satellites for about 30 minutes and it could not found anyone. I have reseted the flight controller (with factory reset) and tried to update the firmware. The only diffrence I think I have is that one firmware is for X4 and the other for Y6. Is it same Firmware or is it different for each setup?

**Comment by rmackay9** [comment]
Thanks for the report although this is really a support question so it belongs in the APM Forum.  http://ardupilot.com/forum/viewforum.php?f=100
