### ISSUE TITLE
Unable to connect to Mission Planner with AC(V3.3, 3.2.1 ,3.2)

### ISSUE THREAD

**Issue by Tuck3rz** [diydrones/ardupilot#1820]
Good evening, I have an APM2.6 and I have downloaded the Arducopter codes (AC master version, AC 3.2.1, AC 3.2) from github and uploaded it to APM via USB (with nothing connected to it) using Arduino IDE. 

These codes are uploaded successfully (with CLI enable in APM_Config.h). However I'm not able to connect them through Mission Planner and all i got was "No heartbeat packets received". I checked it through the terminal and no codes were running in the CLI as well.

I have tested it with v3.1.5 and it managed to connect to Mission Planner though.
Does anyone have any idea why the later version does not work for me?

Observation: With AC 3.2 and above, the APM board only flashes blue LED.
                     For AC 3.1.5, the Red and blue LED are blinking one at a time with transmit LED when idle

**Comment by rmackay9** [comment]
This looks like more of a support question in which case it's probably best to raise in the APM Forum.
http://ardupilot.com/forum/viewforum.php?f=100

In any case, I'm afraid master won't fit on an APM2.x.  We're not supporting the AVR CPU based boards beyond AC3.2.1.

**Comment by Tuck3rz** [comment]
Hi there, I have tried using the branch files of 3.2 & 3.2.1 too but it does not connect as well
