### ISSUE TITLE
how to enable more pins for sonar sensors on APM 2.5

### ISSUE THREAD

**Issue by spied001** [diydrones/ardupilot#1853]
Hello everyone,

I am having issues trying to enable more pins to be use for the sonar sensors to be able to avoid objects while in-flight. Can please some one direct me or help me finding a solution for this problem. Thank you very much for any information and help.

**Comment by rmackay9** [comment]
@spied001,
You'll likely need to make code changes in the AP_RangeFinder library to enable more sonar.  After that's done you should see more RNGFND2_PIN, RNGFND3_PIN parameters which you can set.
http://copter.ardupilot.com/wiki/common-rangefinder-maxbotix-analog/

Dev questions should probably go to drones-discuss@googlegroups.com so I will close this.  There's an active discussion on how to do object avoidance for copters so you might want to collaborate with the other people (including me) who are looking into that.  Honestly, getting the sonar's working is the easy part.
