### ISSUE TITLE
Remove the concept of "INTERNAL" I2C for pixhawk and future systems.

### ISSUE THREAD

**Issue by proficnc** [diydrones/ardupilot#1858]
For plane 3.3?

This will allow for either i2c bus to be used in the future for compass, or other features.  Currently there are some drivers that assume that if a device is on i2c1 that it is internal, so it applies limitations to it.  ie, the compass on i2c1 will not allow a rotation to be applied, this could cause an issue if someone was to fit to a standard GPS/compass to i2c1.

Future Pixhawks may have access to i2c1, so could allow for a second GPS/ Mag to be connected.

This is legacy from the old days of onboard i2c compasses.

This would be a step 1, a further step would be to allow per sensor orientations to be set... longer term goal.

**Comment by gmorph** [comment]
Patch has been applied.
