### ISSUE TITLE
yaw autotune

### ISSUE THREAD

**Issue by geofrancis** [diydrones/ardupilot#1859]
the current autotune only does pitch and roll, but not yaw or throttle. the reason im asking is a lot of quads have an off set CG like a camera hanging down and to the front so when the quad yaws the centrifugal force pushes the camera out and the quad back, so if the autotune could do some yaw movements to detect and compensate for this it would make tuning much faster,

**Comment by ronhogwarts** [comment]
This has already been requested and is an issue for AC 3.3.0: #874

**Comment by rmackay9** [comment]
@ronhogwarts, thanks for noticing the duplication.  I'll close this issue.
