### ISSUE TITLE
HIL Simulation the plane altitude did not change！

### ISSUE THREAD

**Issue by coolmrcsh** [diydrones/ardupilot#1862]
The firmware is 3.2.1, when the plane fly, the altitude did not change, the altitude always the same. So when auto take off, the plane always climb, because always not reach the target altitude.

**Comment by squilter** [comment]
Other plane HIL issues are #164 #283 #937 #1106

**Comment by tridge** [comment]
Thanks for letting us know! I've reproduced the issue and will fix for the 3.2.2 release
