### ISSUE TITLE
APM Planner v2.0.16-rc3

### ISSUE THREAD

**Issue by MJBeaubien** [diydrones/ardupilot#1864]
I updated my APM Planner this morning and now when I go to Graphs and try to go to Droneshare APM Planner crashes. I've tried numerous times and crashes every time.

**Comment by rmackay9** [comment]
@MJBeaubien, could you raise this in the APM Planner issues list?
https://github.com/diydrones/apm_planner/issues

**Comment by MJBeaubien** [comment]
Sure.


 


Date: Mon, 9 Feb 2015 17:26:34 -0800

**Comment by MJBeaubien** [comment]
Done.


 


From: mcbeaubien@hotmail.com
To: reply@reply.github.com
Subject: RE: [ardupilot] APM Planner v2.0.16-rc3 (#1864)
Date: Mon, 9 Feb 2015 17:44:27 -0800




Sure.


 


Date: Mon, 9 Feb 2015 17:26:34 -0800
