### ISSUE TITLE
Fixing Error when AC_FENCE = DISABLE on APM 2.x

### ISSUE THREAD

**Issue by iyia12co** [diydrones/ardupilot#1870]
For those who wish to disable fence to save space by removing the comment on `APM_Config.h` from:

    #define AC_FENCE              DISABLED            // disable fence to save 2k of flash

...will result in the following error on `motors.pde`

    motors.pde:340: error: 'fence' was not declared in this scope

Turns out that the code on `motors.pde` does not check to see if `AC_FENCE` is enabled before calling it, so I thought I'd point it out to anyone that needs to bypass this.

One 'untested' fix is to add the conditionals

    #if AC_FENCE == ENABLED
        // check fence is initialised
        if(!fence.pre_arm_check()) {
            if (display_failure) {
                gcs_send_text_P(SEVERITY_HIGH,PSTR("PreArm: check fence"));
            }
            return;
        }
    #endif

Then, it will compile.

-Cheers

**Comment by rmackay9** [comment]
Thanks very much for reporting this and providing the solution.
https://github.com/diydrones/ardupilot/commit/a4fd36a775a4f5990eb34925516770641521816f
