### ISSUE TITLE
Plane Landing - disarm after landing

### ISSUE THREAD

**Issue by magicrub** [diydrones/ardupilot#1877]
After a plane landing is detected a disarm should occur. This can be implemented via a delay param such as LAND_DISARM_DELAY where 0 is disabled and positive values are in seconds before the disarm.

**Comment by proficnc** [comment]
Keep in mind petrol aircraft!  A disarm before the motor is off is really bad :)

**Comment by magicrub** [comment]
the short term workaround is to disable the feature with a value of 0. However, to properly implement it I suppose we would need to check that throttle is at or near the min. The implementation I was thinking of using was to trigger /w the landing wp which suppresses the throttle anyway.

I'll make sure to reset the timer if we takeoff again (come out of LANDING_APPROACH_FINAL)

**Comment by magicrub** [comment]
See pull request 1922
https://github.com/diydrones/ardupilot/pull/1922
