### ISSUE TITLE
Copter- Circle with radius of 1 meter causes crash

### ISSUE THREAD

**Issue by AdamMullins** [diydrones/ardupilot#1885]
I've been trying to circle my hexacpoter in its own axis in auto mode and setting the radius to 0 is supposed to make it turn in place. For me, setting to 0 makes it circle about 4 meters out from the center. 
Today inset the radius to 1 and it got the waypoint then starter to barel role and fall. I now have a broken arm and motor mount.

**Comment by rmackay9** [comment]
@AdamMullins, before raising an issue here, we should confirm it's really a software bug.  The best way forward is to raise it in the APM Forum.  Sorry to be strict but if we're not then the issues list just becomes a support forum.
When you submit to the forum, a dataflash log would be good.
http://ardupilot.com/forum/viewforum.php?f=100
