### ISSUE TITLE
Sensor Drifting in APM 2.6

### ISSUE THREAD

**Issue by ozanio** [diydrones/ardupilot#1886]
I dont know If this is a hardware issue or a code issue but here goes. My roll tends to -1.4 degrees. My pitch tends to -2.1 and my yaw goes to the negative forever. It is as if it's incrementing at 0.2 degrees per sec.

I'm using the MPU 6000 library to get my data. When I use the DCM library I don't get any drift but then I don't know how to get roll rate data

**Comment by rmackay9** [comment]
This sounds more like a development question so should probably go to drones-discuss@googlegroups.com.
sounds like the problem is you're not compensating for gyro drift by using the accelerometers.
