### ISSUE TITLE
Plane - altitude drift in v3.2.2

### ISSUE THREAD

**Issue by magicrub** [diydrones/ardupilot#1891]
I'm seeing a lot of altitude drift on my Pixhawk on Plane v3.2.2 which does not happen in v3.2.1alpha (Dec 17). The baro pressure is stable but the AHRS value drifts significantly. This is all while the plane is sitting on the table.

**Comment by haogodent2** [comment]
It's the same issue I posted on the user forum below:
http://ardupilot.com/forum/viewtopic.php?f=107&t=11323

**Comment by magicrub** [comment]
Does anyone else observe this? It's quite obvious and easy to test and keeps us from using V3.2.x.

**Comment by tridge** [comment]
thanks. I've reproduced the issue and I should have a fix this morning

**Comment by magicrub** [comment]
eager to alpha test! :)

**Comment by magicrub** [comment]
fixed with this commit
https://github.com/diydrones/ardupilot/commit/6781a8d3290d846e9abcb925b7fee0302f5000e2
