### ISSUE TITLE
AP_Limits: Wrong headers included ("GPS.h")

### ISSUE THREAD

**Issue by dgrat** [diydrones/ardupilot#1896]
I wonder why it is compiling with your buildsystem.
Currently implement a cmake build system and found this.

Best, Daniel

**Comment by 19504643** [comment]
hello dgrat,
I run into this problem suddenly and I can NOT find where GPS.h is.
did you solve this strange problem?

**Comment by dgrat** [comment]
This issue is one year old. I don't think it is still important.

**Comment by 19504643** [comment]
except for this GPS.h header error, in AP_Limit_Geofence.h,there comes another error, [GPS *&gps](https://github.com/diydrones/ardupilot/blob/master/libraries/AP_Limits/AP_Limit_Geofence.h)
where is the GPS  defined?

**Comment by dgrat** [comment]
It isn't defined, this is why I issued the problem. GPS was a very old class, which is removed already since years. I wrote this problem in the mailing list and in the issue and even made a patch once.

**Comment by 19504643** [comment]
that is to say,files in the AP_Limits directory are NOT compiled all the way?

**Comment by dgrat** [comment]
Yes :D
