### ISSUE TITLE
EKF_CHECK_THRESH default is 0.6 on the wiki but 0 in Mission Planner

### ISSUE THREAD

**Issue by andyp1per** [diydrones/ardupilot#1936]
I also found that I could not change this setting in APM Planner 2. Which value is correct? Not sure if this is a firmware or MP issue.

**Comment by rmackay9** [comment]
Ah, ok.  What's likely happening is your vehicle's EKF_CHECK_THRESH is set to 0.6 which did not appear in the list of valid values.  I've added that now and whenever the mission planner next updates it's parameter descriptions you should see "Strict" appear in the drop-down.
https://github.com/diydrones/ardupilot/commit/033bcd849b07726e0c84c7fdf8a7c5cec9d0f828

I've also fixed the wiki to correctly show the default as 0.8.

Thanks for the report!
