### ISSUE TITLE
Pixhawk firmware update via UART

### ISSUE THREAD

**Issue by magicrub** [diydrones/ardupilot#1938]
Add ability to perform Pixhawk firmware update via UART without USB.

**Comment by magicrub** [comment]
Per @Craig3DRobotics and @tridge this is already available but the bootloader is implemented as USB-only or UART-only.

**Comment by squilter** [comment]
@magicrub Maybe this issue could be moved to PX4/Bootloader?

**Comment by magicrub** [comment]
sure

**Comment by magicrub** [comment]
Moved to https://github.com/PX4/Bootloader/issues/33

**Comment by magicrub** [comment]
and https://github.com/PX4/Bootloader/issues/35
