### ISSUE TITLE
Copter: forbid arming in Sport/Acro

### ISSUE THREAD

**Issue by abvgeej** [diydrones/ardupilot#1944]
We should have a special reminder for arming in Sport/Acro modes, or have a ability to forbid arming in those modes.

**Comment by rmackay9** [comment]
My view is that this is really a GCS responsibility.

**Comment by JoshWelsh** [comment]
I would agree with that, since we're talking about arming from the GCS I hope and not the RC transmitter.. The title concerned me initially until I saw Randy's reply :)

**Comment by abvgeej** [comment]
@JoshWelsh No, i am talking about RC.
We should care about the users who have memory problems, and dont need to arm in Acro :)
Of course, there are users which want to arm in those modes, but i would prefer to at least have some beeping and blinking on me before i do something i dont do that often.

**Comment by R-Lefebvre** [comment]
What exactly is the issue you're trying to solve here?

**Comment by abvgeej** [comment]
1) Have a different beep pattern or LED warning when arming in those modes.
2) Get a option to forbit arming in those modes.
(As i know, you cant arm in Drift/Circle, but if i am wrong, that also applies to them)

**Comment by R-Lefebvre** [comment]
I'm asking why you would want this?

**Comment by abvgeej** [comment]
@rmackay9 "We should care about the users who have memory problems"
Mode switches are a thing you can always forget about.

**Comment by lthall** [comment]
Is the intention of this is to warn people that they haven't checked what mode they are in before arming the copter?

If you forget about your mode switch then you forget about safety and shouldn't be flying.

I am speechless!!!

**Comment by R-Lefebvre** [comment]
I think you should just remove acro and stabilize modes from your switches?

**Comment by abvgeej** [comment]
@lthall Well, this is still a good safety feature. I fly well, but constantly forget the antennas at home :)
After all, we have arm locks on LAND, RTL and many more modes. Why cant we have a optional one on those?

@R-Lefebvre But i still wish to use them. (And what does "Stabilize" have to do with this?)

I start to realize how utterly stupid this feature sounds, and all of my comments on it. Close this, as I feel ashamed.

**Comment by JoshWelsh** [comment]
@abvgeej since you opened it you can close it yourself, you don't have to ask Randy or the others to close it.
I think Stupid is too strong a word, as your intention sounds decent enough, but I echo Leonard's thoughts as well as Robs that this is a setup and safety awareness issue. I'm glad you've come around on this request now!

**Comment by abvgeej** [comment]
@JoshWelsh As i know, i dont have the rights to close this issue, but if you know a way i can, it would be great.

**Comment by rmackay9** [comment]
the overall goal of trying to improve safety is a worthy goal.
I'll close this as agreed above.
