### ISSUE TITLE
Error: Build ArduCopter in eclipse

### ISSUE THREAD

**Issue by zhujimson** [diydrones/ardupilot#1958]
I follow this:http://dev.ardupilot.com/wiki/editing-the-code/editing-the-code-with-eclipse/
and this:http://dev.ardupilot.com/wiki/building-the-code/building-with-eclipse/

when I build the ArduCopter code in eclipse, it gave me this:
ERROR: cannot determine sketchbook location - please specify on the commandline with SKETCHBOOK=<path>

I am in a Win7 32bit system.
Please help me out.

**Comment by rmackay9** [comment]
Thanks for gettnig involved with the development.
This looks more like a developer question so could you instead email drones-discuss@googlegroups.com?
