### ISSUE TITLE
Puzzles in accelemeter calibration

### ISSUE THREAD

**Issue by WXFMAV** [diydrones/ardupilot#1967]
Puzzles in accelerometer calibration. 
The output of accelerometer is calibrated in accelerometer_calibration.cpp & mpu6000.cpp, and then they were transformed into body frame to estimate speed and position.
While we noticed that the IMU measurement units could not work even in several seconds without GPS kit. We integrate accelerometer outputs twice to estimate position of quadrotor, position errors could rapidly increase to tens of meters in several seconds.
We noticed that the calibration uses algorithm as below:

//////////////////////////////////////////////////////////////////////////////////////////////
        **float x_in_new = ((report.accel_x * _accel_range_scale) - _accel_scale.x_offset) * _accel_scale.x_scale;
	float y_in_new = ((report.accel_y * _accel_range_scale) - _accel_scale.y_offset) * _accel_scale.y_scale;
	float z_in_new = ((report.accel_z * _accel_range_scale) - _accel_scale.z_offset) * _accel_scale.z_scale;**
//////////////////////////////////////////////////////////////////////////////////////////////

We puzzles with the algorithm as above, especially why there is bias and scale rate in outputs of accelerometer. We know that the output of accelerometer could be transformed into body frame with a rotation matrix provided by calibration program, so it seemed that there is no need to do the bias and scale rate calibration.
Could anyone tell us why? Thanks.

**Comment by rmackay9** [comment]
this looks more like a developer question so could you instead email drones-discuss@googlegroups.com?
