### ISSUE TITLE
accel CLI command does not work from secondary serial port

### ISSUE THREAD

**Issue by dongfang** [diydrones/ardupilot#199]
When commected to UART3(APM1) or UART2(APM2), it is possible to enter CLI mode and go setup -> accel.
The console interaction does not work, because the IO goes from/to UART0 via hal.console. The user will get the impression that the APM/PX4 has crashed.
Changing AP_InertialSensor_UserInteractStream interact to use cliSerial instead of hal.console seems to fix this - if it does not break anything else :)

**Comment by gmorph** [comment]
CLI is deemed as deprecated.  This functionality may or may not work at the time of writing but it won't be updated either way.  If anyone things differently please let me know.
Thanks, Grant.
