### ISSUE TITLE
Copter: RTL completely ignored (APM:Copter V3.2.1 Release)

### ISSUE THREAD

**Issue by robustini** [diydrones/ardupilot#2002]
Tested today with VR Brain V4.5 (NuttX inside), the "RTL" flight mode are completely ignored, stay in the latest state (Position Hold), same when i try to engage "Auto".
Here logs and tlogs (at 94.83% the first event):

https://drive.google.com/file/d/0B3HEcrNCOga9RktpNU1HdHMwSDA/view?usp=sharing

![rtl_issue](https://cloud.githubusercontent.com/assets/3864712/6766199/ebbdc2a4-cffc-11e4-9956-12176612b3f9.png)

**Comment by rmackay9** [comment]
Marco, thanks for the report, I'll have a look.
I'm closing this issue as it's really a support issue at this point.  If it's confirmed as a bug or enhancement we can raise it here.
