### ISSUE TITLE
Copter: Scheduler value to correct (1 min required to fix it)

### ISSUE THREAD

**Issue by Ju1ien** [diydrones/ardupilot#2004]
https://github.com/diydrones/ardupilot/blob/master/ArduCopter/ArduCopter.pde#L734
In :  { update_thr_average, 40, 10 },
the "40" value should be replaced by "4" because that function should be called at 100Hz, and not 10Hz

**Comment by rmackay9** [comment]
Oh my, nice find!

**Comment by magicrub** [comment]
@rmackay9 , is this merged into v3.3.0? if so, please close this issue.

**Comment by rmackay9** [comment]
It seems AC3.2 went out with the throttle average running at 100hz so I think we will leave this as it is.

**Comment by rmackay9** [comment]
Forget what I said above.  I've checked in the change to master here.  Thanks Julien!
https://github.com/diydrones/ardupilot/commit/b7a6e3bf2cbc1b52d6bcda70b545f173fe4c8eef
