### ISSUE TITLE
How to recall actual Waypoint in Arduplane.pde ?

### ISSUE THREAD

**Issue by MetalSlugX** [diydrones/ardupilot#2009]
I need the number of the current way point to use it in arduplane.pde?
How can I recall it?

I apologise for the question i am quite a beginner in APM

**Comment by rmackay9** [comment]
@MetalSlugX , this looks like a developer question so would probably be better to email this to drones-discuss@googlegroups.com.
the answer is that there should be a "mission" object with an accessor that allows retrieving the number of commands in the mission.
