### ISSUE TITLE
losing height during roll(bank) problem

### ISSUE THREAD

**Issue by deadlyboy** [diydrones/ardupilot#2019]
hi 

recently i decided to write my own simple flight controller. i tested it in flight gear, i works well except losing height during roll , it's about 20 to 50 meter but i suppose in real world it increases substantially.

i think i should use a combination of rudder and elevator  along side aileron to keep altitude constant.

i work with APM2.5 and it do roll very well without losing altitude , but in it's code i can't find some code that doing this compensation.

how is the exact method for the roll in apm and who it do that ?
if it's possible show me a reference to a part of code that handle this part .
thanks in advance

**Comment by magicrub** [comment]
This is not an "issue" with ArduPilot, please re-post in the forums. Meanwhile, check out the Attitude Control code and search for "yaw" and you'll see that it's rather complicated.
https://github.com/diydrones/ardupilot/blob/master/libraries/AC_AttitudeControl/AC_AttitudeControl.cpp
