### ISSUE TITLE
RFE: log rxrsssi

### ISSUE THREAD

**Issue by marcmerlin** [diydrones/ardupilot#2021]
Last I needed it for debugging, my pixhawk didn't log the value of rxrssi to sd. It was being shown on my OSD, but not saved for later review.
Assuming it hasn't been added recently
http://diydrones.com/forum/topics/is-rxrssi-not-being-logged-by-apm-at-all-1
could it be added in a future build?

Thanks.

**Comment by magicrub** [comment]
Done via https://github.com/diydrones/ardupilot/pull/2804
