### ISSUE TITLE
i think therer is a bug in  both AP_Math/vector3.cpp and vector2.cpp

### ISSUE THREAD

**Issue by cat888** [diydrones/ardupilot#2039]
vector3.cpp:
template <typename T>
bool Vector3<T>::operator !=(const Vector3<T> &v) const
{
    return (x!=v.x && y!=v.y && z!=v.z);
}

should be: return (x!=v.x || y!=v.y || z!=v.z);

vector2.cpp:
template <typename T>
bool Vector2<T>::operator !=(const Vector2<T> &v) const
{
    return (x!=v.x && y!=v.y);
}

should be: return (x!=v.x || y!=v.y);

**Comment by magicrub** [comment]
nice catch!

**Comment by tridge** [comment]
fixed, thanks!!

**Comment by magicrub** [comment]
Now the question is what, of anything, has been using those operands?
Surely the behavior would change.

**Comment by tridge** [comment]
I've checked what was using it. Nothing was using the Vector2 != operator. There was one user of the Vector3 != operator, in AP_Param::set_and_save(), but the result wasn't used for vector parameters, so it didn't change any behaviour
Still worth fixing though!

**Comment by magicrub** [comment]
totally worth fixing, thanks for the quick merge!
