### ISSUE TITLE
LIM_PITCH_CD

### ISSUE THREAD

**Issue by PistaJ** [diydrones/ardupilot#2040]
Is it a mistaken term in the manual
As far as I understand it this does not exist

**Comment by magicrub** [comment]
That may have been replaced with LIM_PITCH_MIN and LIM_PITCH_MAX, where do you see LIM_PITCH_CD?

**Comment by magicrub** [comment]
@PistaJ ping

**Comment by magicrub** [comment]
probably a beta vs release documentation mixup.
