### ISSUE TITLE
Travis is broken (again)

### ISSUE THREAD

**Issue by magicrub** [diydrones/ardupilot#2056]
Example build:
https://travis-ci.org/diydrones/ardupilot/builds/57389164

Following error occurs:
Tools/scripts/build_all_travis.sh: line 15: /home/travis/opt/gcc-arm-none-eabi-4_7-2014q2/bin/arm-none-eabi-gcc: No such file or directory

**Comment by rmackay9** [comment]
I think travis is fixed now so can we close this?
