### ISSUE TITLE
AP_InertialSensor Compile error in APM2

### ISSUE THREAD

**Issue by jinchengde** [diydrones/ardupilot#2063]
it looks like some error when compile code in Arduino-1.0.3

D:\Backup\Git\ardupilot\libraries\AP_InertialSensor\AP_InertialSensor.cpp: In member function 'bool AP_InertialSensor::calibrate_accel(AP_InertialSensor_UserInteract*, float&, float&)':
D:\Backup\Git\ardupilot\libraries\AP_InertialSensor\AP_InertialSensor.cpp:533:29: internal compiler error: Segmentation fault

**Comment by magicrub** [comment]
This is not a code error, is a problem with gcc 4.6. We were getting that
problem with pixhawk so we upgraded to gcc 4.8.

What IDE and compiler are you using?

**Comment by rmackay9** [comment]
I've closed this based on the discussion above.

**Comment by jinchengde** [comment]
@magicrub
I used gcc 4.7.2 and after upgrade to 4.8.2, everything is ok.
thanks for you help.
