### ISSUE TITLE
Error while using Arduino IDE 1.6.3 ????

### ISSUE THREAD

**Issue by anisjamil** [diydrones/ardupilot#2112]
I am trying to compile APM 3.1.1 by using arduino ide 1.6.3, and it is giving me following set of errors 
Arduino: 1.6.3 (Windows 8.1), Board: "Arduino Mega or Mega 2560, ATmega2560 (Mega 2560)"

Build options changed, rebuilding all

Using library AP_Common in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Common (legacy)

Using library AP_HAL in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_HAL (legacy)

Using library AP_Progmem in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Progmem (legacy)

Using library AP_Menu in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Menu (legacy)

Using library AP_Param in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Param (legacy)

Using library StorageManager in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\StorageManager (legacy)

Using library AP_GPS in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_GPS (legacy)

Using library AP_Baro in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Baro (legacy)

Using library AP_Compass in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Compass (legacy)

Using library AP_Math in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Math (legacy)

Using library AP_ADC in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_ADC (legacy)

Using library AP_ADC_AnalogSource in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_ADC_AnalogSource (legacy)

Using library AP_InertialSensor in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_InertialSensor (legacy)

Using library AP_AHRS in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_AHRS (legacy)

Using library RC_Channel in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\RC_Channel (legacy)

Using library AP_RangeFinder in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_RangeFinder (legacy)

Using library Filter in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\Filter (legacy)

Using library AP_Buffer in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Buffer (legacy)

Using library AP_Relay in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Relay (legacy)

Using library AP_Camera in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Camera (legacy)

Using library AP_Airspeed in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Airspeed (legacy)

Using library AP_Terrain in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Terrain (legacy)

Using library APM_OBC in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\APM_OBC (legacy)

Using library APM_Control in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\APM_Control (legacy)

Using library GCS_MAVLink in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\GCS_MAVLink (legacy)

Using library AP_SerialManager in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_SerialManager (legacy)

Using library AP_Mount in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Mount (legacy)

Using library AP_Declination in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Declination (legacy)

Using library DataFlash in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\DataFlash (legacy)

Using library SITL in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\SITL (legacy)

Using library AP_Scheduler in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Scheduler (legacy)

Using library AP_Navigation in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Navigation (legacy)

Using library AP_L1_Control in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_L1_Control (legacy)

Using library AP_RCMapper in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_RCMapper (legacy)

Using library AP_Vehicle in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Vehicle (legacy)

Using library AP_SpdHgtControl in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_SpdHgtControl (legacy)

Using library AP_TECS in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_TECS (legacy)

Using library AP_NavEKF in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_NavEKF (legacy)

Using library AP_Mission in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Mission (legacy)

Using library AP_Notify in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Notify (legacy)

Using library AP_BattMonitor in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_BattMonitor (legacy)

Using library AP_Arming in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Arming (legacy)

Using library AP_BoardConfig in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_BoardConfig (legacy)

Using library AP_Frsky_Telem in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Frsky_Telem (legacy)

Using library AP_ServoRelayEvents in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_ServoRelayEvents (legacy)

Using library AP_Rally in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Rally (legacy)

Using library AP_OpticalFlow in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_OpticalFlow (legacy)

Using library AP_HAL_AVR in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_HAL_AVR (legacy)

Using library AP_HAL_AVR_SITL in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_HAL_AVR_SITL (legacy)

Using library AP_HAL_PX4 in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_HAL_PX4 (legacy)

Using library AP_HAL_FLYMAPLE in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_HAL_FLYMAPLE (legacy)

Using library AP_HAL_Linux in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_HAL_Linux (legacy)

Using library AP_HAL_Empty in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_HAL_Empty (legacy)

Using library AP_HAL_VRBRAIN in folder: C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_HAL_VRBRAIN (legacy)

C:\Users\Anis\Desktop\A\arduino-1.6.3\hardware\tools\avr/bin/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10603 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR -IC:\Users\Anis\Desktop\A\arduino-1.6.3\hardware\arduino\avr\cores\arduino -IC:\Users\Anis\Desktop\A\arduino-1.6.3\hardware\arduino\avr\variants\mega -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Common -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_HAL -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Progmem -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Menu -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Param -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\StorageManager -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_GPS -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Baro -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Compass -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Math -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_ADC -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_ADC_AnalogSource -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_InertialSensor -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_AHRS -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\RC_Channel -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_RangeFinder -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\Filter -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Buffer -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Relay -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Camera -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Airspeed -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Terrain -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\APM_OBC -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\APM_Control -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\GCS_MAVLink -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_SerialManager -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Mount -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Declination -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\DataFlash -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\SITL -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Scheduler -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Navigation -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_L1_Control -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_RCMapper -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Vehicle -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_SpdHgtControl -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_TECS -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_NavEKF -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Mission -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Notify -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_BattMonitor -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Arming -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_BoardConfig -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Frsky_Telem -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_ServoRelayEvents -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Rally -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_OpticalFlow -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_HAL_AVR -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_HAL_AVR_SITL -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_HAL_PX4 -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_HAL_FLYMAPLE -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_HAL_Linux -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_HAL_Empty -IC:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_HAL_VRBRAIN C:\Users\Anis\AppData\Local\Temp\build525886779525760197.tmp\ArduPlane.cpp -o C:\Users\Anis\AppData\Local\Temp\build525886779525760197.tmp\ArduPlane.cpp.o 

In file included from C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_HAL/AP_HAL.h:9:0,

                 from ArduPlane.ino:34:

C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_HAL/AP_HAL_Boards.h:245:2: error: #error "Unknown CONFIG_HAL_BOARD type"

 #error "Unknown CONFIG_HAL_BOARD type"

  ^

C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_HAL/AP_HAL_Boards.h:249:2: error: #error "No CONFIG_HAL_BOARD_SUBTYPE set"

 #error "No CONFIG_HAL_BOARD_SUBTYPE set"

  ^

In file included from C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Param/AP_Param.h:30:0,

                 from ArduPlane.ino:38:

C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Common/../StorageManager/StorageManager.h:39:2: error: #error "Unsupported storage size"

 #error "Unsupported storage size"

  ^

In file included from C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_GPS/AP_GPS.h:25:0,

                 from ArduPlane.ino:40:

C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Math/AP_Math.h:187:2: error: #error "Build is including Arduino base headers"

 #error "Build is including Arduino base headers"

  ^

In file included from C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Compass/AP_Compass_HMC5843.h:9:0,

                 from C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Compass/AP_Compass.h:6,

                 from ArduPlane.ino:42:

C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Compass/Compass.h:45:3: error: #error "You must define a default compass orientation for this board"

 # error "You must define a default compass orientation for this board"

   ^

In file included from C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Notify/AP_Notify.h:22:0,

                 from ArduPlane.ino:79:

C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Notify/AP_BoardLED.h:71:2: error: #error "Unknown board type in AP_Notify"

 #error "Unknown board type in AP_Notify"

  ^

ArduPlane.ino:221:3: error: #error Unrecognized CONFIG_COMPASS setting

In file included from C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Param/AP_Param.h:30:0,

                 from ArduPlane.ino:38:

C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Common/../StorageManager/StorageManager.h:69:44: error: 'STORAGE_NUM_AREAS' was not declared in this scope

     static const StorageArea layout_copter[STORAGE_NUM_AREAS];

                                            ^

C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Common/../StorageManager/StorageManager.h:70:45: error: 'STORAGE_NUM_AREAS' was not declared in this scope

     static const StorageArea layout_default[STORAGE_NUM_AREAS];

                                             ^

C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Common/../StorageManager/StorageManager.h: In static member function 'static void StorageManager::set_layout_copter()':

C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Common/../StorageManager/StorageManager.h:59:52: error: 'layout_copter' was not declared in this scope

     static void set_layout_copter(void) { layout = layout_copter; }

                                                    ^

In file included from ArduPlane.ino:29:0:

C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Math/AP_Math.h: At global scope:

C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Math/AP_Math.h:174:15: error: expected unqualified-id before 'float'

 float radians(float deg);

               ^

C:\Users\Anis\Desktop\A\arduino-1.6.3\hardware\arduino\avr\cores\arduino/Arduino.h:89:24: note: in definition of macro 'radians'

 #define radians(deg) ((deg)*DEG_TO_RAD)

                        ^

C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Math/AP_Math.h:174:15: error: expected ')' before 'float'

 float radians(float deg);

               ^

C:\Users\Anis\Desktop\A\arduino-1.6.3\hardware\arduino\avr\cores\arduino/Arduino.h:89:24: note: in definition of macro 'radians'

 #define radians(deg) ((deg)*DEG_TO_RAD)

                        ^

C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Math/AP_Math.h:174:15: error: expected ')' before 'float'

 float radians(float deg);

               ^

C:\Users\Anis\Desktop\A\arduino-1.6.3\hardware\arduino\avr\cores\arduino/Arduino.h:89:24: note: in definition of macro 'radians'

 #define radians(deg) ((deg)*DEG_TO_RAD)

                        ^

C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Math/AP_Math.h:177:15: error: expected unqualified-id before 'float'

 float degrees(float rad);

               ^

C:\Users\Anis\Desktop\A\arduino-1.6.3\hardware\arduino\avr\cores\arduino/Arduino.h:90:24: note: in definition of macro 'degrees'

 #define degrees(rad) ((rad)*RAD_TO_DEG)

                        ^

C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Math/AP_Math.h:177:15: error: expected ')' before 'float'

 float degrees(float rad);

               ^

C:\Users\Anis\Desktop\A\arduino-1.6.3\hardware\arduino\avr\cores\arduino/Arduino.h:90:24: note: in definition of macro 'degrees'

 #define degrees(rad) ((rad)*RAD_TO_DEG)

                        ^

C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Math/AP_Math.h:177:15: error: expected ')' before 'float'

 float degrees(float rad);

               ^

C:\Users\Anis\Desktop\A\arduino-1.6.3\hardware\arduino\avr\cores\arduino/Arduino.h:90:24: note: in definition of macro 'degrees'

 #define degrees(rad) ((rad)*RAD_TO_DEG)

                        ^

C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Math/AP_Math.h:180:10: error: expected unqualified-id before 'float'

 float sq(float v);

          ^

C:\Users\Anis\Desktop\A\arduino-1.6.3\hardware\arduino\avr\cores\arduino/Arduino.h:91:17: note: in definition of macro 'sq'

 #define sq(x) ((x)*(x))

                 ^

C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Math/AP_Math.h:180:10: error: expected ')' before 'float'

 float sq(float v);

          ^

C:\Users\Anis\Desktop\A\arduino-1.6.3\hardware\arduino\avr\cores\arduino/Arduino.h:91:17: note: in definition of macro 'sq'

 #define sq(x) ((x)*(x))

                 ^

C:\Users\Anis\Desktop\A\APM 3.1.1\libraries\AP_Math/AP_Math.h:180:10: error: expected ')' before 'float'

 float sq(float v);

          ^

C:\Users\Anis\Desktop\A\arduino-1.6.3\hardware\arduino\avr\cores\arduino/Arduino.h:91:17: note: in definition of macro 'sq'

 #define sq(x) ((x)*(x))

                 ^

ArduPlane.ino:257:24: error: 'uint32_t millis()' was declared 'extern' and later 'static' [-fpermissive]

In file included from ArduPlane.ino:29:0:

C:\Users\Anis\Desktop\A\arduino-1.6.3\hardware\arduino\avr\cores\arduino/Arduino.h:132:15: error: previous declaration of 'long unsigned int millis()' [-fpermissive]

 unsigned long millis(void);

               ^

ArduPlane.ino:258:24: error: 'uint32_t micros()' was declared 'extern' and later 'static' [-fpermissive]

In file included from ArduPlane.ino:29:0:

C:\Users\Anis\Desktop\A\arduino-1.6.3\hardware\arduino\avr\cores\arduino/Arduino.h:133:15: error: previous declaration of 'long unsigned int micros()' [-fpermissive]

 unsigned long micros(void);

               ^

ArduPlane.ino:128:26: error: 'AP_HAL_BOARD_DRIVER' was not declared in this scope

ArduPlane.ino:763:42: error: 'compass' was not declared in this scope

ArduPlane.ino: In function 'void update_compass()':

ArduPlane.ino:940:30: error: 'compass' was not declared in this scope

ArduPlane.ino: In function 'void compass_accumulate()':

ArduPlane.ino:957:9: error: 'compass' was not declared in this scope

ArduPlane.ino: In function 'void compass_save()':

ArduPlane.ino:1068:9: error: 'compass' was not declared in this scope

ArduPlane.ino: In function 'void update_GPS_10Hz()':

ArduPlane.ino:1158:21: error: 'compass' was not declared in this scope

ArduPlane.ino: At global scope:

ArduPlane.ino:1578:14: error: expected constructor, destructor, or type conversion before ';' token

GCS_Mavlink.ino: In function 'void send_extended_status1(mavlink_channel_t)':

GCS_Mavlink.ino:235:30: error: 'compass' was not declared in this scope

GCS_Mavlink.ino: In member function 'bool GCS_MAVLINK::try_send_message(ap_message)':

GCS_Mavlink.ino:602:52: error: 'compass' was not declared in this scope

GCS_Mavlink.ino: In member function 'void GCS_MAVLINK::handleMessage(mavlink_message_t*)':

GCS_Mavlink.ino:1070:17: error: 'compass' was not declared in this scope

GCS_Mavlink.ino:1075:17: error: 'compass' was not declared in this scope

Parameters.ino: At global scope:

Parameters.ino:1036:13: error: 'compass' was not declared in this scope

Parameters.ino:11:85: note: in definition of macro 'GOBJECT'

sensors.ino: In function 'void read_battery()':

sensors.ino:70:5: error: 'compass' was not declared in this scope

system.ino: In function 'void init_ardupilot()':

system.ino:160:14: error: 'compass' was not declared in this scope

Error compiling.

-------------------------------------------------------------------------------------------------------

 I have also tried Arduino IDE 1.0.3, it works fine but does not include the arduino core files during compilation and gives me follwing message.

Excluding arduino cores from the include path

    Anybody who could plz help me out. I am working to resolve this error since last month but nothing is being done correctly..

**Comment by rmackay9** [comment]
By default we only support the modified version of Arduino IDE ver 1.0.3 and moving to a higher arduino IDE is definitely off our strategic direction so I'm afraid not many devs will likely be able to help much.  http://dev.ardupilot.com/wiki/building-the-code/
