### ISSUE TITLE
Plane: param LAND_DISARMDELAY set to 0 after reboot

### ISSUE THREAD

**Issue by magicrub** [diydrones/ardupilot#2129]
Plane: param LAND_DISARMDELAY set to 0 after reboot on latest master

**Comment by magicrub** [comment]
well crap, now I'm getting the same thing on LOG_BITMASK so maybe something is wrong on my end. Can someone please sanity check me and tell me if their LAND_DISARMDELAY value sticks through a reboot. If so I'll close this issue.

**Comment by tridge** [comment]
yes, it sticks fine for me
