### ISSUE TITLE
Read-only parameter: Firmware version/build string

### ISSUE THREAD

**Issue by sreid55** [diydrones/ardupilot#2134]
Create a read-only parameter which returns a string identifying the firmware version (e.g., "COPTER Y6B 3.3-RC1").   This would allow the GS software to easily report this information upon connecting to the craft.

**Comment by magicrub** [comment]
Mission Planner for Windows shows this info at the very top.

-TomP

**Comment by rmackay9** [comment]
This looks like a duplicate of this other issue: https://github.com/diydrones/ardupilot/issues/1104
