### ISSUE TITLE
Add aircraft ID parameter (feature request)

### ISSUE THREAD

**Issue by sreid55** [diydrones/ardupilot#2135]
Add a parameter which can be written and read by the Ground Station which holds an arbitrary string value.   This will allow GS software to support assigning unique IDs to different aircraft, and maintaining separate GS profiles for each.

The parameter would have no semantic meaning within the firmware.

For example, the GS software could recognize a particular airframe by ID, and let the user store and load a few different profiles (parameter sets) for that airframe, which may include different PIDs and battery capacities that the user has created/tuned for different batteries.

**Comment by iskess** [comment]
SYSID_THISMAV
Assign it a number and Mission Planner will sort the .tlogs into different folders by number.
I use the same numbers on my RC handheld model list to help me remember.
It would be really nice if we could assign a name to each model in Mission Planner, which it would correlate to the parameter value. Then it could use this name to label the folder, even each tlog. It would also show which model you are connected to.

These requests belong in the Mission Planner site, APM already has the functionality you are requesting.

**Comment by rmackay9** [comment]
I'm going to close this item if that's ok.

**Comment by sreid55** [comment]
Got it - thanks for the info guys.
