### ISSUE TITLE
parameters missing in AC3.3 on pixhawk 

### ISSUE THREAD

**Issue by taogashi** [diydrones/ardupilot#2152]
Firmware: Copter 3.3-rc1 11-Apr-2015
Board: pixhawk 2.4.6
GCS: APM planner 2.0.17
toolchain: gcc-arm-none-eabi-4.7

![param error](https://github.com/taogashi/winter-offensive/blob/ys/param.png)

The problem is that APM planner cannot load or set the **loiter pid** and the **throttle pid**, so I can't do extended tuning. Some more parameters may suffer the same issue, not sure.

When rolling back to ArduCopter-3.2.1, everything turns to be OK.
But I really need the support for PX4Flow.

How can I solve this problem? or is there a way to avoid it? Thanks.

**Comment by rmackay9** [comment]
Thanks for the report.
This caused by the renaming of some parameters between AC3.2 and AC3.3 so we need to get the AP Planner 2 guys to update their extended tuning page.  So we need a new issue raised over in the AP Planner issues list.
https://github.com/diydrones/apm_planner/issues/685
