### ISSUE TITLE
copter：help me

### ISSUE THREAD

**Issue by jyl58** [diydrones/ardupilot#2177]
I use APM 3.2 firmware at a quadrotor.when I set the fight mode to RTL from loiter,the quadrotor slowly down frome home positon.But when I control the yaw  at this time ,the quadrotor clime up suddenly and up to 300m .it is so quickly！！someone  can help me？  thanks so much.

**Comment by rmackay9** [comment]
Support goes into the APM Forum or on diydrones.  Sorry but although it's sometimes hard to get support answered in these other two areas we can't allow the github issues list, which is for enhancement and bug requests, to turn into another support forum.
