### ISSUE TITLE
Feature suggestion: add vehicle name parameter

### ISSUE THREAD

**Issue by hsteinhaus** [diydrones/ardupilot#2182]
I would like to propose to add a vehicle name parameter, that makes it easier to remember the vehicle that a certain log belongs to. 

It would also allow to auto-generate flight logbooks (as required in some legislations for UAVs) from dataflash logs via simple scripting.

**Comment by magicrub** [comment]
Like a param that is just a string of whatever you want?

**Comment by magicrub** [comment]
I like that, makes it much easier to identify logs from multiple aircraft.
Very easy to do, I love the idea.

**Comment by hsteinhaus** [comment]
Exactly. Just a param to store a short alphanumeric label. I wonder that nobody else missed that yet.

**Comment by magicrub** [comment]
I'll jump on that, I'll submit a PR tomorrow for it. Easy to do.

**Comment by hsteinhaus** [comment]
I think the main challenge is to find a nice central location (library?) that adds it to all vehicle types without touching three/four Parameters.pde files.

**Comment by magicrub** [comment]
That's my plan

**Comment by rmackay9** [comment]
Duplicate so staying with tradition I will close the newer one.
https://github.com/diydrones/ardupilot/issues/1411

**Comment by AndKe** [comment]
SYSID_THISMAV  - does more or less just that ?

**Comment by magicrub** [comment]
Strings are best, just need to get them implemented
