### ISSUE TITLE
Fuzzy PID 

### ISSUE THREAD

**Issue by masbi** [diydrones/ardupilot#2233]
Hello, my Name is Masbi from Sepuluh Nopember Institute of Technology (ITS) ,Indonesia

I am at final semester student of Engineering Physics ITS and my final project is about control quadcopter with Fuzzy-PID.

Can you tell me, when and where can I edit the PID code to implement Fuzzy gain scheduling PID ?
have anybody ever did the same project as me ? 
I am confused because too much code in APM and I need to find the code of roll,pitch, and yaw PID Gain and add the Fuzzy algoritm in there..

i hope anybody could help me...
thanks...

**Comment by magicrub** [comment]
/libraries/PID would be a good place to start but the issue tracker is not the proper place to ask for code advice. Please use
dev chat: https://gitter.im/diydrones/ardupilot
dev email: https://groups.google.com/forum/#!forum/drones-discuss
