### ISSUE TITLE
AC3.3: reduce attitude estimate fallback to DCM

### ISSUE THREAD

**Issue by rmackay9** [diydrones/ardupilot#2238]
We should only fall back to DCM if the EKF has encountered a really critical error like an infinity or NAN.

**Comment by priseborough** [comment]
We could use the reported filter fault status here:

https://github.com/diydrones/ardupilot/blob/master/libraries/AP_NavEKF/AP_NavEKF.cpp#L4753

This will only be non-zero if there are numerical errors or if the filter has not initialised

**Comment by rmackay9** [comment]
fixed in master by paul with this patch: https://github.com/diydrones/ardupilot/commit/c2ac80cc63a319ef2cb59f52ccdd7a706bb04758
