### ISSUE TITLE
ArduCopter does not compile succesfully

### ISSUE THREAD

**Issue by laigege** [diydrones/ardupilot#2244]
I followed with the description from http://dev.ardupilot.com/wiki/building-the-code/building_with_make/，both arduplane and APMRover2 can make successful, however the ArduPilot can't, with the message:

ardupilot-master/ArduCopter/ArduCopter.pde:588:8: error: 'AP_InertialNav_NavEKF' does not name a type static AP_InertialNav_NavEKF inertial_nav(ahrs);

I don't know why. Can anyone help me?

**Comment by rmackay9** [comment]
So it's not possible to build copter with arduino anymore.  It's mentioned on this wiki page but sadly not on the one you looked at.
http://dev.ardupilot.com/wiki/building-the-code/building-ardupilot-with-arduino-windows/

AC3.2.1 will still build on arduino but all more recent versions, including master won't build.
