### ISSUE TITLE
How to disarm the quadrotor in LOITER mode.

### ISSUE THREAD

**Issue by icyore** [diydrones/ardupilot#2276]
In document, I should take-off in loiter mode when I use the PX4FLOW. But I can not disarm the quadrotor in loiter mode. Should I disarm the quadrotor in  STABILIZE mode and switch to LOITER mode to take off?

**Comment by rmackay9** [comment]
It should be possible to disarm in loiter mode, just wait for the motors to slow down.  Are you finding that it's acting differently if it's got the PX4Flow sensor attached vs no PX4Flow sensor?

This is more of a question that probably belongs in the APM Forum or on diydrones as a discussion so I'll close this but I'll stlil monitor this issue for your reply.  A dataflash log showing the issue may also help.  Maybe we've got some problem..
