### ISSUE TITLE
Commanded z altitude not constant at mid RC_3

### ISSUE THREAD

**Issue by tuloski** [diydrones/ardupilot#2292]
AC 3.2.1
I'm trying to command the quad with external RC. In particular the RC channel 3 is used to give z velocity reference in loiter mode. The channel is calibrated at [994 1994].
What I don't understand is why if the channel pwm is close to 1500 us, the velocity is negative (altitude reference increasing). In particular up to 1420us the altitude keeps growing.
Is this related to THR_MID and other parameters setting the mid point for throttle?
Isn't correct in loiter/altitude hold that 1500 (or mid point) is considered as zero velocity?

**Comment by rmackay9** [comment]
It's actually a small mistake in the AC3.2.1 code but it's resolved in AC3.3.  The beta is out now so if you're still interested in this, please give the beta a try.  By the way, controlling the vehicle by providing direct RC inputs to the flight controller is not the recommended method.  instead try using dronekit.
