### ISSUE TITLE
retractable Landing Gear not working with 3.3 rc3 and rc4

### ISSUE THREAD

**Issue by lijingwei0710** [diydrones/ardupilot#2304]
following the wiki page :http://copter.ardupilot.com/wiki/landing-gear/ but can not got the landing gear working.

**Comment by rmackay9** [comment]
Can you raise this on the AC3.3 dev thread actually?  We shouldn't clutter up our git issues list with beta testing requests before they're confirmed to be issues.
http://diydrones.com/forum/topics/copter-3-3-beta-testing
