### ISSUE TITLE
Copter landing gear servo output parameters not documented in the source

### ISSUE THREAD

**Issue by hamishwillee** [diydrones/ardupilot#2307]
The auto-generated copter parameters for the servo AUX-to-purpose mapping do not include options 28 and 29 (landing gear).

For example, see [RC10_Function](http://copter.ardupilot.com/wiki/configuration/arducopter-parameters/#servo_out_function_rc10_function) - this stops at number 27. However we know that option 29 is the landing gear, and presumably option 28 is something too. The other RCn_Functions are also missing this information.

**Comment by R-Lefebvre** [comment]
This is simply a MP release timing issue.  It will be rectified when AC3.3 goes out stable.

**Comment by hamishwillee** [comment]
Thanks. Closing then.

**Comment by rmackay9** [comment]
I don't think this will be fixed with a MP release.  Hamish is talking about the automatically generated wiki pages so very separate from the MP.

**Comment by hamishwillee** [comment]
Correct. I didn't read Robert's message properly :-0 . Normally updates to these parameters go out as soon as they are in the main codeline so I would expect them there now.

**Comment by R-Lefebvre** [comment]
Ah, sorry about that.

**Comment by rmackay9** [comment]
Ok, found the issue and fixed.
https://github.com/diydrones/ardupilot/commit/b121d83beb28fd0fcf4ff9dc0e10186d9e484d55

**Comment by hamishwillee** [comment]
Thanks - I can see the parameters are no on the wiki!
