### ISSUE TITLE
Create AP_MotorsMultirotor Class

### ISSUE THREAD

**Issue by R-Lefebvre** [diydrones/ardupilot#2319]
New class will position below AP_MotorsClass and all the lower multirotor code (ie: AP_MotorsMatrix, etc).  Intent is extra abstraction layer between Helicotper and Multirotor code.  AP_MotorsClass will contain mostly pure virtual function declarations and not much else. At this point, all parameters created in AP_Motors will move down to AP_MotorsMultirotor.

**Comment by rmackay9** [comment]
this is in master now.
