### ISSUE TITLE
Brake mode allows altitude to fall over time

### ISSUE THREAD

**Issue by R-Lefebvre** [diydrones/ardupilot#2325]
When leaving copter in Brake mode for extended periods of time, it seems the altitude controller is active and controlling for accelerations, but is not maintaining altitude. 

Issue identified by Tom Buetow here:

http://diydrones.com/forum/topics/copter-3-3-beta-testing?id=705844%3ATopic%3A1964465&page=65#comments

**Comment by rmackay9** [comment]
Leonard and I found and fixed this bug.  This will go out with AC3.3-rc6.
https://github.com/diydrones/ardupilot/commit/ee3ba4809735d7c37843ef7c4871b1f9d237677c

**Comment by R-Lefebvre** [comment]
So how does that work, just so I understand?
