### ISSUE TITLE
Arduplane: Land Flaps don't reset

### ISSUE THREAD

**Issue by Jman841** [diydrones/ardupilot#2327]
After doing an Auto landing and completing the mission, I disarmed the plane and reset the mission. Upon activating auto mode again, auto take off engages the flaps.

For auto take off I have 0 flaps programmed, only for auto landing.

After cycling the power the flaps worked properly for the next mission, however, it was required to cycle power to fix this issue. Doing mission reset and disarming the plane (both in the GCS and via the button) failed to make the flaps work correctly during auto take off.

This issue was repeatable after another successful auto landing.

**Comment by tridge** [comment]
I think this was fixed by lekston with PR#2569 today
I'll close this for now. If you see the problem again please re-open
