### ISSUE TITLE
Land Detector does not perform adequately for TradHeli

### ISSUE THREAD

**Issue by R-Lefebvre** [diydrones/ardupilot#2328]
Tridge and myself have experienced indication that the land detector is not working well for helicopters.  Basically, it does not trigger reliably.  This resulted in a ground tipover for Tridge, and a I've had bad yaw oscillations.

Critical fix for AC3.3

**Comment by rmackay9** [comment]
can we close this now maybe?

**Comment by R-Lefebvre** [comment]
If you pulled in my PR, which I think you did, then yes.

**Comment by R-Lefebvre** [comment]
https://github.com/diydrones/ardupilot/pull/2335
