### ISSUE TITLE
why my APM2.6  high speed to sky

### ISSUE THREAD

**Issue by rebelboy** [diydrones/ardupilot#2343]
why my APM2.6  high speed to sky?

my flight mode is ALT_HOLD .  Fly with 100% THR.  copter will high speed to sky.

my log file http://115.28.20.145/APM26LOG.zip

**Comment by rebelboy** [comment]
my Firmware is 3.2 RC

**Comment by rebelboy** [comment]
My English is not good. Thanks you help

**Comment by rmackay9** [comment]
The pilot's input throttle was at full.  If you didn't actually hold the throttle high maybe the receiver had some kind of problem?
