### ISSUE TITLE
Yaw Twitch After Takeoff

### ISSUE THREAD

**Issue by R-Lefebvre** [diydrones/ardupilot#2346]
Yaw twitches when taking off, twice, first at 1.5m and then at 5m.  This is because of the EKF dealing with the possibility of ground magnetization.  Very noticeable with tradhelis.

Paul has the fix for this already, the yaw reset is slowly integrated over a short period of time, just needs to be merged in.

**Comment by robustini** [comment]
Same issue here, confirmed!

**Comment by R-Lefebvre** [comment]
Yeah, it's a well known issue that's already got a fix.  This is just a reminder to pull the fix in.

As of now, the yaw will still move a little bit, but it won't be so aggressive.

What's happening is the yaw heading resets after leaving the ground, which is meant to fix problems that occur when people take off from a surface that is magnetized.

**Comment by andrea25** [comment]
Confirmed also by me. Same issues here. Very noticiable also with Hexa.

**Comment by rmackay9** [comment]
this is fixed with AC3.3-rc7
