### ISSUE TITLE
Bug: Land command initiated by pilot is ignored due to EKF failsafe logic

### ISSUE THREAD

**Issue by rrr6399** [diydrones/ardupilot#2357]
Since it doesn't appear that I can reopen this bug myself:
https://github.com/diydrones/ardupilot/issues/2334 ,
 I created this bug.

It appears from the logs of two failed fly away flights with two separate copters that when the pilot initiated the LAND command via the GCS that the LAND command triggered the EKF failsafe logic not vice-a-versa. This failsafe logic has a 4 second delay logic that I suspect is causing the delay in the LAND command. Since it appeared that the copters were out of control given that the change to LAND mode was being ignored by the firmware, the both copters were disarmed in flight leading to hard crashes.

**Comment by magicrub** [comment]
@rmackay9 , please re-evaluate https://github.com/diydrones/ardupilot/issues/2334
@rrr6399 , please do not intentionally open up duplicate issues. If there is no response to comments on an issue then bring it to the attention of the gitter chat channel or drones-discuss email.

**Comment by rrr6399** [comment]
The issues are being closed too quickly. It takes a lot of time to generate a decent bug report and its frustrating to see the issue immediately closed without any further discussion. There is no way for me to reopen the request either.
