### ISSUE TITLE
Plane: parachute support under loss of control and during missions

### ISSUE THREAD

**Issue by CraigElder** [diydrones/ardupilot#2359]
Add
https://github.com/diydrones/ardupilot/blob/master/libraries/AP_Parachute/AP_Parachute.cpp
enable deployment from a mission command
stop the motor as part of the deployment sequence

**Comment by magicrub** [comment]
What is the current deployment method in Copter?

**Comment by alexchernoff** [comment]
Suggestion on chute opening on Plane:  if a DO_SET_SERVO command exists after DO_LAND_START, assume it is a chute servo. Once the aircraft enters the Flare stage and altitude, it cuts off throttle and executes the servo command. 

This way:
1: aircraft is very close to home and on approach
2: it's at a flare (lower) altitude than RTL altitude.

**Comment by rmackay9** [comment]
In case it helps there's a MAV_CMD_DO_PARACHUTE that can be used to trigger the parachute as part of a mission (in copter at least).  It should also be possible to send it wrapped in a COMMAND_LONG so that it can be triggered immediately from the ground station.

In addition in copter we use ch7/ch8 aux switches to allow the pilot to trigger the release manually.

**Comment by naktinis** [comment]
Since #2553 was merged as duplicate, I wanted to stress that it was particularly about automatic deployment (what Randy referred to as "crash checker") when some criteria are met (not about deployment from a mission command). Similar to what's implemented for the copter.

**Comment by rmackay9** [comment]
I've updated the title a bit to hopefully make that clear.

**Comment by naktinis** [comment]
Thanks!

**Comment by tridge** [comment]
initial version of this is now in master

**Comment by naktinis** [comment]
Since this is now closed, I think #2553 should be reopened. The code that is now in master, as I understand, does not automatically detect a fault and deploy a parachute (which Copter is capable of and which #2553 is about).
