### ISSUE TITLE
Copter: allow faster descents when moving forward

### ISSUE THREAD

**Issue by rmackay9** [diydrones/ardupilot#238]
There's an optimisation that maybe we could do which is to allow a faster descent when you're moving forward.  Because of the prop wash problem when coming down (in stabilize mode) a copter can actually descend much quicker if it comes down at an angle vs straight down.  This is very different than climbing where you climb slower if you're leaned over at all.  At the moment we treat climb and descending pretty much the same which is not ideal..

**Comment by R-Lefebvre** [comment]
Randy, wonder if we can totally remove this now with Leonard's changes in 3.3 that allow very fast descents without wobble.

**Comment by rmackay9** [comment]
yeah, good idea.  people aren't really asking for it anyway.
