### ISSUE TITLE
source code "ArduCopter 3.2.1-rc2"  30-Jan-2015 for APM 2.6

### ISSUE THREAD

**Issue by nahci13** [diydrones/ardupilot#2438]
Hello all!
I know, just now this is last version of firmware complete supports APM 2.6.
But, how I can find or downloading source code of **ArduCopter 3.2.1-rc2** *(30-Jan-2015)* for **APM 2.6**?
Regards

**Comment by Johnex** [comment]
You can get the final source from:
https://github.com/diydrones/ardupilot/archive/ArduCopter-3.2.1.zip

**Comment by nahci13** [comment]
Thank you!
