### ISSUE TITLE
Wp speed ch6 opt  no work on copter ac3.3rc5

### ISSUE THREAD

**Issue by roque-canales** [diydrones/ardupilot#2464]
Wpspeed value change on the full parameter list following ch6 knob, but in the air during autoflight mission turning ch6 knob not affect at all the speed of drone.

**Comment by rmackay9** [comment]
I tested this in SITL and it seems to work ok.  I suspect the problem is the tuning parameter conventions can be confusing.
TUNE: 10
TUNE_LOW: 0
TUNE_HIGH: 1000  <-- gives speed of up to 10m/s (1500 = 15m/s)

If the speed provided is below 1m/s (i.e. 100) then it is ignored.
