### ISSUE TITLE
sudden impact shutoff

### ISSUE THREAD

**Issue by Jgayler** [diydrones/ardupilot#2497]
If during flight mode, or during a landing sequence, a sudden deceleration is detected, chances are that the solo has impacted with something. Most likely the ground. There should be an instant shut off that happens when this occurs. otherwise Solo will flip over.

**Comment by R-Lefebvre** [comment]
How exactly do we detect this deceleration? Accelerometer spike?  How big and how long?  GPS accel?

**Comment by magicrub** [comment]
I'm interested to hear about how this gets done. I have a crude crash
detection for plane that I'm pushing soon and would love to improve it.

**Comment by rmackay9** [comment]
I think we should concentrate more on the desired behaviour and raise an issue for that rather than the actual implementation.  We have a crash detector already, in what case does it not perform adequately?

**Comment by squilter** [comment]
The crash detector is designed to accomplish this.  It was broken for Solo in a previous release, but it has been fixed now.  Even so, I think the crash detector was never broken for ardupilot master.
