### ISSUE TITLE
AHRS: perf improvement by replacing sinf in yaw_drift_correction

### ISSUE THREAD

**Issue by rmackay9** [diydrones/ardupilot#250]
This line of AP_AHRS_DCM.cpp:
https://github.com/diydrones/ardupilot/blob/master/libraries/AP_AHRS/AP_AHRS_DCM.cpp#L562
error.z *= sinf(fabsf(roll));

Can probably be replaced with this:
error.z *= fabsf(_dcm_matrix.c.y);

..but maybe pitch should also be incorporated into this calculation somehow?

**Comment by R-Lefebvre** [comment]
Think this can be closed?  We don't use DCM anymore?

**Comment by rmackay9** [comment]
yup, closing!  txs.
