### ISSUE TITLE
How/where do I change how a given motor responds to input?

### ISSUE THREAD

**Issue by tedbyers** [diydrones/ardupilot#2505]
I am looking at experimenting with an airframe I have never seen before.  If someone else has, I'd love an URL.  Picture an H-frame hexacopter, but with a difference.  The back pair of motors would be on a V-tail, and the front pair would be on what would be called an A-tail, except this is at the front.  Now, to this, we add two more motors, both mounted so that their axis is parallel to the main axis of the copter.  These additional motors would respond only to pitch, having no role in either yaw or roll, as they provide only forward thrust.

Now, the other six motors would have the usual inputs that an H-frame hexacopter would have (subject to modifications applicable to an A-nose and V-tail), including pitch (so the copter can use them to slow/stop, when necessary.  However, the new motors ought to be off when the pitch input is negative, and should be on, with RPM increasing with increasing positive input, so that  when the maximum pitch input is reached, the motor has the maximum RPM it can support with the prop mounted on it.

The question is, what files, and portions thereof, ought I examine, so I can modify it to support this 'pusher motor/prop, and how to tell the FC that this motor (or these motors) react in this way to pitch input, and this without altering how the other motors respond to the pitch inputs.  I do not want to control these 'pusher motors' with a switch or a pot on the Tx, and that would make them too unresponsive: that is, the pilot would have less control of these motors than he ought, whereas it is quite intuitive to have these motors respond only to pitch input (and this restricted to positive input).  We want the pusher motor to push the drone forward slowly with a small positive pitch input, but as fast forward as it can go with 100% pitch input.

Is there a better/simpler way to achieve what I want to do with these pusher motors?

Thanks

Ted

**Comment by rmackay9** [comment]
This is probably more of a dev question so could you email drones-discuss@googlegroups.com or chat on gitter?  https://gitter.im/diydrones/dronekit-python
