### ISSUE TITLE
FLOW_ORIENT_YAW parameter documentation not being auto-generated 

### ISSUE THREAD

**Issue by hamishwillee** [diydrones/ardupilot#2514]
The FLOW_ORIENT_YAW does not appear on the wiki in the parameter lists for copter, plane, rover. It is a valid parameter and appears in Mission Planner when viewing the "Full Parameter List" for copter.

**Comment by rmackay9** [comment]
ok, this should fix it.
https://github.com/diydrones/ardupilot/commit/03356a8d3a6d5971927ae054347f35dbaa51ad67

**Comment by hamishwillee** [comment]
It did. Thank you!
