### ISSUE TITLE
Copter: Update Wiki On Tricopter Servo Changes

### ISSUE THREAD

**Issue by Johnex** [diydrones/ardupilot#2518]
Hi!
The wiki needs to be updated with the new tricopter servo parameters introduced in these 2 commits:

https://github.com/diydrones/ardupilot/commit/b8181b6b90fb2a5b5fbfaede335ec250d59e7cf3
https://github.com/diydrones/ardupilot/commit/8dc7cf7fa8caea5869df6308f8456e0696c4d9f1

APM motors still says RC7_REV and Pixhawk motors doesn't even mention the tricopter at all.

**Comment by rmackay9** [comment]
Ok, we've added a tricopter wiki page now:
http://copter.ardupilot.com/wiki/tricopter/

And I've updated the apm2 and pixhawk pages to point to this new page (and updated the message to say that there are two possible parameters that need to be changed - which one depends upon the software version).
http://copter.ardupilot.com/wiki/connecting-the-escs-and-motors/
http://copter.ardupilot.com/wiki/initial-setup/assembly-instructions/connect-escs-and-motors-pixhawk/

Hope that covers it so closing this issue.  if i've missed something comment below and I'll see it.
