### ISSUE TITLE
Storm32: Serial connection adopt the revise for firmware 0.78 and higher

### ISSUE THREAD

**Issue by Gregmaan** [diydrones/ardupilot#2534]
Randy also tested that the storm32 firmwares above 0.77 did not work anymore via serial connection.
It would be fine if we can use the benefits of firmware 0.78 and above vial serial.
http://www.olliw.eu/storm32bgc-wiki/Serial_Communication

**Comment by fillycheezstake** [comment]
#2752

**Comment by Gregmaan** [comment]
duplicate #2752
