### ISSUE TITLE
convert ftoa_engine.S and ulto_invert.S to C

### ISSUE THREAD

**Issue by tridge** [diydrones/ardupilot#255]
We have a problem at the momment with inconsistency between printf()
behaviour between our AVR boards, our ARM (PX4/VRBrain) board and our
SITL implementation. The behaviour of printf() with such simple things
as "%f" is quite different. This affects things like dataflash logging
behaviour and has led to some real bugs.

The problem stems from two AVR assembler files, in
libraries/AP_HAL_AVR/utility/ called ftoa_engine.S and ultoa_invert.S.

If we could convert those two assembler files to C then we could have
uniform behaviour across all our HAL implementations, which would (among
other things) make our SITL testing a more accurate representation of
the true behaviour.

Note that these functions are not speed critical, so it doesn't matter
if the C version is a bit slower than the asm version. Consistent
behaviour is more important for us in this case than speed.

What does matter though is that the C version behave exactly the same as
the existing assembler versions. That way we can be confident the
conversion won't introduce a bug.

Any takers?

**Comment by gmorph** [comment]
Confirmed with Tridge as resolved.  Closing.
