### ISSUE TITLE
AC3.3: enable EKF check only after EKF position estimate has been initialised

### ISSUE THREAD

**Issue by rmackay9** [diydrones/ardupilot#2559]
This should resolve the issue where the LEDs flash yellow-red if the GPS is disabled (GPS_TYPE=0) intentionally and the pilot is only flying in non-GPS modes.

**Comment by andyp1per** [comment]
IIRC I still get the blue light when I am in a non-GPS mode and don't have a lock (not actually tried flying). Is this a different scenario?

**Comment by rmackay9** [comment]
During a bench test this is certainly the case, but in a real copter I think it flashes yellow+red.  There's a report on the AC3.3 beta testing thread from another user as well.

**Comment by andyp1per** [comment]
I never do benchtests :) I'll have another go to check when I have some time.

**Comment by rmackay9** [comment]
This should be resolved with this commit which will go out with AC3.3-rc8
https://github.com/diydrones/ardupilot/commit/277e3d86752da103a4d3a8ce1061664ab3d20bf6
