### ISSUE TITLE
Level and Accel Calibration not available in MP for Rovers

### ISSUE THREAD

**Issue by TC3** [diydrones/ardupilot#2566]
I encountered an interesting issue with both MP 1.3.30 and 1.3.28 when trying to calibrate my rover accels when using either firmware v 2.49 or 2.50: There is no longer a level or accel calibration in the Mandatory Hardware drop down when using the rover firmware like there is for Arduplane. I had to use the CLI to calibrate for level and the accels. The Wizard seems to skip both the level and accel calibration, yet gives me a warning that the accels are not calibrated. Has anyone else encountered this issue when calibrating their rovers?
Regards,
Tom C AVD

**Comment by rmackay9** [comment]
@TC3,
I guess this is more of a MissionPlanner issue so I'll close it here if that's ok and maybe you can copy-paste into a new issue in the MP issues list?
https://github.com/diydrones/MissionPlanner/issues
