### ISSUE TITLE
using apm for other projects

### ISSUE THREAD

**Issue by kalukurikrishna** [diydrones/ardupilot#2567]
hiee all
i want to use apm 2.6 for other projects like simple projects like controlling four servos using inbuilt gyro... etc
is it possible???

**Comment by squilter** [comment]
Yes, it is an Arduino.  Open the Arduino IDE and set the board to the `Arduino Mega 2560`.  Poke around [here](https://github.com/diydrones/ardupilot/tree/master/libraries/AP_HAL_AVR/utility) to figure out the pinout.
