### ISSUE TITLE
Add annotations to facilitate building GUIs

### ISSUE THREAD

**Issue by geeksville** [diydrones/ardupilot#264]
As there are more and more GCS options, it seems to make sense to encode metadata in the ardupilot source so that device side developers can add new parameters and expect all GCSes to 'just work'.

The following parameter annotations are already accepted by the build system:

@Units: m/s
@Range: 5 50
@Increment: 1
@User: Standard|Advanced
@Param: ARSPD_FBW_MAX
@DisplayName: Fly By Wire Maximum Airspeed
@Description: Airspeed corresponding to maximum throttle in Fly By Wire B mode.
@Values

I would propose changing as follow:

@User: Standard|Advanced|SomeOtherPageName
Where page name can be used to select which page this parameter should be placed.  This allows the developer to specify new page names to logically group parameters (rather than just 'standard' and 'advanced').

@UIHint: <hint>
If this (rarely used) annotation is not specified, the GCS will select widgets as follows:
* If @Values are specified then then a dropdown menu-item will be used.
* If @Range is specified a horizontal slider will be used
* Otherwise, a text box with numeric entry will be used
If this annotation is specified, the following control types can be specified:
* VBar - a vertical scroll bar
* HBar - a horizontal scroll bar

**Comment by gmorph** [comment]
Hi Kevin.  This has gone nowhere in 2 years.  I don't believe this is going to be implemented.  Did you want to keep this open or should we close it out?
Thanks, Grant.

**Comment by WickedShell** [comment]
Closing this for now as Grant never got a response and we support values/ranges now. While their is no hinting supported for the GCS about when to use a horizontal or vertical scroll bar it's hard to see how this UI feature should be dictated by the autopilot developer, the GCS should use whichever it prefers (due to theme or presentation issues). If someone objects then please reopen.
