### ISSUE TITLE
Division by zero in AP_AHRS_DCM

### ISSUE THREAD

**Issue by alexbuyval** [diydrones/ardupilot#2657]
I faced out with this error during work with [own SITL mode](https://groups.google.com/forum/#!topic/drones-discuss/sgGNg7IpqN8). I am not sure that this error appears with real hardware.
The error occurs in the following rows:
https://github.com/diydrones/ardupilot/blob/master/libraries/AP_AHRS/AP_AHRS_DCM.cpp#L122
https://github.com/diydrones/ardupilot/blob/master/libraries/AP_AHRS/AP_AHRS_DCM.cpp#L562

I think that it is better to add a check.

**Comment by tridge** [comment]
thanks! I've added a check for zero
