### ISSUE TITLE
Copter: Change mount_mode with DO_MOUNT_CONTROL

### ISSUE THREAD

**Issue by squilter** [diydrones/ardupilot#2664]
DO_MOUNT_CONTROL should consume parameter 7 and change the mount_mode.  That way, arducopter can do a DO_MOUNT_CONTROL in guided mode, not just auto.

**Comment by squilter** [comment]
@rmackay9 ArduCopter is using `MOUNT_CONFIGURE` and `MOUNT_CONTROL`.  These are similar, but not the same as `MAV_CMD_DO_MOUNT_CONFIGURE` and `MAV_CMD_DO_MOUNT_CONTROL`.  The 7th parameter that we wanted to consume is only in `MAV_CMD_DO_MOUNT_CONTROL`, which isn't a packet we are listening to.

**Comment by rmackay9** [comment]
Ok, I'd suggest that we should get rid of the ardupilotmega messages and stick with the common messages.  It's a pain that that will cause changes to all ground stations and vehicles though!

**Comment by squilter** [comment]
@rmackay9 So these are actually totally different messages?

**Comment by rmackay9** [comment]
@squilter yes, I'm afraid so.  One is sent within a COMMAND_LONG or MISSION_ITEM, the other two are their own individual messages.

**Comment by squilter** [comment]
Done with #2696
