### ISSUE TITLE
Plane: Unable to connect when external compass disconnected since 3.3.0

### ISSUE THREAD

**Issue by Hangarspace** [diydrones/ardupilot#2675]
Since 3.3.0, Mission Planner is unable to connect to Arduplane on APM if the APM is setup to use an external compass and the compass is disconnected. This becomes a real inconvenience, if nothing else, when you want to connect to the APM in a disassembled model that has the compass on a wing. Think 'large model, small workshop'.

http://ardupilot.com/forum/viewtopic.php?f=110&t=13198

http://ardupilot.com/forum/viewtopic.php?f=110&t=12861

http://ardupilot.com/forum/viewtopic.php?f=110&t=12888

Apologies if this has been dealt with, but can't see a record of it.

**Comment by tridge** [comment]
this was fixed a few weeks ago in master
