### ISSUE TITLE
issues while building arduCopter-3.3 for pixhawk using PX4toolchain

### ISSUE THREAD

**Issue by baoyuncheng** [diydrones/ardupilot#2706]
hello guys:
I am a newer here.
Recently i built arduCopter-3.3 using PX4toolchain as the official-guide: http://dev.ardupilot.com/wiki/building-the-code/building-px4-with-make/

but i cannot get what i wanna.it's just show like this in the px4 console:
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree
Use '--' to separate paths from revisions
and so on...

and i noticed that in 'ardupilot-Copter-3.3-->modules-->PX4Firmware & PX4NuttX & uavcan' there are empty!!
with any step wrong could make it so bad?? i need your help,sinceriously!!

**Comment by rmackay9** [comment]
maybe try running this on the console.
"git submodule update"

This is a dev question so doesn't really belong on the to-do list.  Best to email drones-discuss@googlegroups.com or join Gitter.  It's listed on the dev wiki under the "How the team works" section.  http://dev.ardupilot.com/

**Comment by baoyuncheng** [comment]
I think I have done it,but got the same…and I also did ‘git submodule init’ ‘git submodule update’ ‘git init’.  any idea?

 

发件人: Randy Mackay [mailto:notifications@github.com] 
发送时间: 2015年8月17日 14:39
收件人: diydrones/ardupilot
抄送: baoyuncheng
主题: Re: [ardupilot] issues while building arduCopter-3.3 for pixhawk using PX4toolchain (#2706)

 

maybe try running this on the console.
"git submodule update"

This is a dev question so doesn't really belong on the to-do list. Best to email drones-discuss@googlegroups.com <mailto:drones-discuss@googlegroups.com>  or join Gitter. It's listed on the dev wiki under the "How the team works" section. http://dev.ardupilot.com/
