### ISSUE TITLE
kmz,gpx exports from log don't tally with data in arducopter 3.3rc9

### ISSUE THREAD

**Issue by AdrianEvans** [diydrones/ardupilot#2735]
kmz and gpx files do not contain entire mission. data from gps log shows proper transect lengths but kmz is very short and of limited time. Previously one could see different paths for different states (auto, stab, loiter etc) but none of this is present.

**Comment by rmackay9** [comment]
The kmz files are produced by Mission Planner so this issue problem belongs in the mission planner issues list.
https://github.com/diydrones/MissionPlanner/issues
