### ISSUE TITLE
Mavlink on serial 5

### ISSUE THREAD

**Issue by mpd79** [diydrones/ardupilot#2739]
Hi could I raise an enhancement? I have a pixhawk with Frsky telemetry on S1, 3Dr radio GCS on S2, GPS on S3 & S4. This means I have run out of ports for a storm32 Mavlink gimbal. Could S5 be configurable for this function? Cheers, Mike

**Comment by rmackay9** [comment]
Duplicate of this existing issue: https://github.com/diydrones/ardupilot/issues/2552
