### ISSUE TITLE
UAVCAN is out of date

### ISSUE THREAD

**Issue by pavel-kirienko** [diydrones/ardupilot#2777]
UAVCAN driver used in APM is quite outdated, and it is not compatible with the release candidate version of the UAVCAN specification. An up-to-date version can be found in the PX4 master, beta and v1.0 release.

Is there any option to expedite the update process?

**Comment by magicrub** [comment]
This is something we really need to update, thanks for the kick-in-the-pants reminder! I'm excited to start using/developing on the PX4ESC Pro v1.6.

**Comment by chriseyhorn** [comment]
+1

**Comment by priseborough** [comment]
Is there a patch available so APM developers can do testing with newer CAN ESC's? I have some  Ben Dyer ESC's which i wanted to start doing experimentation on with different thrust control modes and the interaction with TECS.

**Comment by pavel-kirienko** [comment]
Is update to a newer version of PX4 somewhere on the roadmap? If yes, what is the ETA? If not, is my understanding correct that in order to see up-to-date UAVCAN stack the necessary changes will have to be backported from PX4?

**Comment by ctech4285** [comment]
+1

**Comment by silverburn** [comment]
+1

**Comment by czq13** [comment]
+1

**Comment by hsteinhaus** [comment]
As a user of UAVCAN GPS hardware and a big fan of UAVCAN ESCs I would love to help bringing the UAVCAN stack back on track. 

After looking into the differences since the last upstream merge, I can only second that our best chance would be to move to a newer PX4/Firmware release. @tridge - are there any plans on that for the foreseeable future?

**Comment by Georacer** [comment]
+1

**Comment by WickedShell** [comment]
UAVCAN was updated 10 days ago. @tridge can this be closed?
