### ISSUE TITLE
make bbbmini broken?

### ISSUE THREAD

**Issue by El-Mango** [diydrones/ardupilot#2799]
Some problem here?

debian@arm:~/ardupilot/ArduCopter$ make bbbmini
%% libraries/AP_HAL_Linux/Scheduler.o
...
%% libraries/AP_HAL_Linux/Scheduler.o
// BUILDROOT=/tmp/ArduCopter.build HAL_BOARD=HAL_BOARD_LINUX HAL_BOARD_SUBTYPE=HAL_BOARD_SUBTYPE_LINUX_BBBMINI TOOLCHAIN=BBONE EXTRAFLAGS=-DGIT_VERSION="079161ef"
make: *** No rule to make target '/home/debian/ardupilot/libraries/AP_HAL_Linux/RCOutput_Navio.h', needed by '/tmp/ArduCopter.build/libraries/AP_HAL_Linux/HAL_Linux_Class.o'.  Stop.
debian@arm:~/ardupilot/ArduCopter$ 

Bye,
Enrico.

**Comment by gmorph** [comment]
Hi Enrico.  I just tested building for bbbmini on both Copter and Plane and it worked fine.  I did
git pull --rebase
git submodule update
first to ensure I had the latest code from master.  I then did a
make clean
make -j8 bbbmini
in each of the Copter and Plane directories and it built fine.
I'll close this out but if you still have problems jump onto the gitter channel and ask and we will see it.
Thanks, Grant.
