### ISSUE TITLE
Works with this board?

### ISSUE THREAD

**Issue by henricavalcante** [diydrones/ardupilot#2808]
![img_0779](https://cloud.githubusercontent.com/assets/2352034/9706956/a4b5d6b0-54ce-11e5-8231-b0ba04a36bcc.JPG)
![img_0778](https://cloud.githubusercontent.com/assets/2352034/9706957/a4ba0514-54ce-11e5-982a-03a648a117b5.JPG)

**Comment by gmorph** [comment]
Do not post questions like this in here.  This is for issues with the ArduPilot software.
If that is this board
http://www.rcgroups.com/forums/showthread.php?t=1677726
then as a guess I would say it might work as its APM2 based.
Thanks, Grant.
