### ISSUE TITLE
Parameter typo RNGFNDRNGFND_PWRRNG

### ISSUE THREAD

**Issue by hamishwillee** [diydrones/ardupilot#2812]
@gmorph [RNGFNDRNGFND_PWRRNG](http://rover.ardupilot.com/wiki/apmrover2-parameters/#powersave_range_rngfndrngfnd_pwrrng) should probably be RNGFND_PWRRNG

**Comment by magicrub** [comment]
I actually meant to fix this long ago with my snooze-lidar PR
<https://github.com/diydrones/ardupilot/pull/2055/files#diff-ff7de988d4a8904051520a5bddaff7c0L91>
but I eventually closed it before it was merged and forgot about the label.

**Comment by gmorph** [comment]
This problem is in all vehicle types.

**Comment by gmorph** [comment]
Resolved by this PR
https://github.com/diydrones/ardupilot/pull/2813
Thanks, Grant.
