### ISSUE TITLE
Arduplane v2.69-2.73 HIL and Sim Issues

### ISSUE THREAD

**Issue by taylorddavis** [diydrones/ardupilot#283]
Anything from ArduPlane v2.69 HIL and up seems to not want to work correctly. When connecting to MP 1.2.50 with v2.69 - v2.73 HIL firmwares (APM 2.0 board), MP doesn't see the RC controller and there's no way to config the "Radio Calibration" feature and in any of the sims you can't control the plane. So there's no way for me to test the new firmwares using the simulators. Also when using v2.68 in Flightgear, after flying an uploaded mission with waypoints, then uploading another mission the plane keeps circling the last mission's last waypoint or the waypoint it was heading before I upload another mission. So lets say the first mission has 5 waypoints, the only way to get the plane to fly the new mission waypoints is to make more than 5. Once uploaded the plane will then fly to waypoint 6 then to the others but will not fly waypoints 1-5. The only way to get the the plane to fly all of the new mission's waypoints is the power down/reset the APM. Has anybody experienced the same issues or knows how to fix this?

**Comment by gmorph** [comment]
HIL is working.  I am closing this issue.  If anyone thinks differently please let me know.
Thanks, Grant.
