### ISSUE TITLE
APM Copter Wiki Link Update for MaxSonar

### ISSUE THREAD

**Issue by MaxBotixInc** [diydrones/ardupilot#2854]
Hello,

We recently had found an error in linking on the APM Copter Wiki. 

I located the error on the following page:
http://copter.ardupilot.com/wiki/common-rangefinder-maxbotix-analog/

Please see the attached image showing the issue with the embedded link.

I appreciate your help in updating this link. 

Best Regards,

Scott Wielenberg
sdwielenberg@maxbotix.com
![2015-09-11 14_11_55-common-maxbotic analog sonar copter3 2 _ copter 1](https://cloud.githubusercontent.com/assets/3835388/9883142/0a193abc-5b9e-11e5-957a-32afc549b512.png)

**Comment by MaxBotixInc** [comment]
MaxBotix Inc., is offering a free sensor to the first user who can complete this requested update. Please contact info@maxbotix.com for complete details and request to speak with Scott. 

The MaxBotix Inc team looks forward to working with you. Have a great day!

**Comment by rmackay9** [comment]
Ok, I think this is fixed now.  I've just updated it on the planner version of the page and it should propagate automatically to the copter, plane and rover copies.
http://planner.ardupilot.com/wiki/common-rangefinder-maxbotix-analog/

Nobody expects everyone to know all the intricacies of how we work but just in case you find  more wiki errors, this is where we track the wiki issues: https://github.com/diydrones/ardupilot-wiki-issue-tracker/issues
