### ISSUE TITLE
IMU going crazy with tracker code

### ISSUE THREAD

**Issue by bateray** [diydrones/ardupilot#2864]
HI i have problem, when i upload tracker code my IMU is going crazy, 360 degrees non-stop spin. With Plane and Copter code, no problem. APM 2.6, INS_PRODUCT_ID Value is 88 in both. This is my parameter http://diydrones.com/forum/attachment/download?id=705844%3AUploadedFile%3A2091900

**Comment by rmackay9** [comment]
Normally we don't put support issues into github because then it just turns into a support forum.  Better to bring this up on the "Figuring out the antenna tracker" diydrones discussion.
http://diydrones.com/forum/topics/figuring-out-the-antenna-tracker?commentId=705844%3AComment%3A2065705
