### ISSUE TITLE
compile warning in EKF

### ISSUE THREAD

**Issue by magicrub** [diydrones/ardupilot#2871]
Warning is from an array index out-of-bounds check flowRadXY[obsIndex].

AP_NavEKF.cpp:3112
if ((flowTestRatio[obsIndex]) < 1.0f && (flowRadXY[obsIndex] < _maxFlowRate)) {
https://github.com/diydrones/ardupilot/blob/master/libraries/AP_NavEKF/AP_NavEKF.cpp#L3112

It's due to the init here on line 2910 where obsIndex is the address of another index.
uint8_t &obsIndex = flow_state.obsIndex;
https://github.com/diydrones/ardupilot/blob/master/libraries/AP_NavEKF/AP_NavEKF.cpp#L2910

Should that be a simple write like this?
uint8_t obsIndex = flow_state.obsIndex;

Fix PR: https://github.com/diydrones/ardupilot/pull/2870

**Comment by rmackay9** [comment]
That PR went in so closing
