### ISSUE TITLE
Crash check in copter 3.3 checks error from commanded angle rather than upside down

### ISSUE THREAD

**Issue by woodrc** [diydrones/ardupilot#2872]
Comments in crash_check.cpp claim to be checking if copter is inverted. Actual code from this commit [4154ecd](https://github.com/diydrones/ardupilot/commit/4154ecdf18ebd2c60acef7532cf280febb35c8e7#diff-662919fbd26c5e71fd0339c85ba7d2aa) checks if error from commanded angle is greater than 30 deg. This resulted in a crash while pulling against a ground anchor with an x8. String attached slightly aft of the cg resulted in the X8 being unable to pitch down. It was otherwise flying fine at 20 meters when it disarmed and broke a bunch of pieces. 
![image](https://cloud.githubusercontent.com/assets/14354309/9972836/402412ee-5e1e-11e5-8d45-eaccb08926b4.png)

**Comment by rmackay9** [comment]
Ok, txs for the report.
master (which will become Copter-3.4) has a parameter called FS_CRASH_CHECK that allows disabling the crash detector.
