### ISSUE TITLE
Division by zero in AP_AHRS_DCM again

### ISSUE THREAD

**Issue by alexbuyval** [diydrones/ardupilot#2875]
After rebase my own branch with master I have faced out with runtime error in the SITL mode in the following line:
https://github.com/diydrones/ardupilot/blob/master/libraries/AP_AHRS/AP_AHRS_DCM.cpp#L669

I think, it necessary to add a check for zero for '_ra_deltat' variable.

**Comment by tridge** [comment]
fixed, thanks!
