### ISSUE TITLE
Copter: Implement MAV_CMD_GET_HOME_POSITION

### ISSUE THREAD

**Issue by jtanx** [diydrones/ardupilot#2886]
It would be handy especially for off-board control systems to know where the current home position is.

**Comment by vooon** [comment]
FYI: home position stored as first waypoint.
But implementation of [HOME_POSITION](https://pixhawk.ethz.ch/mavlink/#HOME_POSITION) is desirable.

**Comment by rmackay9** [comment]
This is in master now and will go out with Copter-3.4.
