### ISSUE TITLE
Traditional Heli Documentation Updates

### ISSUE THREAD

**Issue by Jman841** [diydrones/ardupilot#2891]
The Traditional Heli Documentation on the Wiki, and, description of Parameters is severely outdated, or, does not exist.

Trying to guess what different parameters do is quite challenge and I can't seem to find any resources that explain it like they do for Arduplane or Arducopter.

**Comment by rmackay9** [comment]
Perhaps this should go on the wiki to-do list.
https://github.com/diydrones/ardupilot-wiki-issue-tracker/issues
