### ISSUE TITLE
MOT_THR_MIX_MAX

### ISSUE THREAD

**Issue by roque-canales** [diydrones/ardupilot#2892]
Hello ,

I tested different flights changing MOT_THR_MIX_MAX from 0,5 to 1 in altitude hold mode without be able to see any change in attitude control druring full lean commands.
From 0,5 to 1, when a push pitch or roll at max, Iris+ drone goes a max lean angle, speed up, and when drone goes above 12/13m/s it start to go down....

I can't see any change on requested lean angle vs real lean angle when drone star to fall...

Have you check it on sitl????

**Comment by rmackay9** [comment]
@roque-canales, this is not the purpose of MOT_THR_MIX_MAX.  the parameter is to control the prioritisation of throttle vs attitude when the throttle is very low.  primarily it affects the floppy-ness of the vehicle during landing.
If you are feeling brave, you can try latest Copter (i.e. not yet released) which maintains altitude in AltHold mode even at very high requested lean angles.
