### ISSUE TITLE
Need to compile atmega8u2 PPM encoder program special needs

### ISSUE THREAD

**Issue by a146860** [diydrones/ardupilot#2934]
Need to compile atmega8u2 PPM encoder program special needs  Already have a lot of hardware need to use atmega8u2 atmega8u2 apm 2.6 hardware

**Comment by magicrub** [comment]
Please do not post help requests in the github issue tracker. This is for bug reports and feature requests only. To compile the code please visit the dev wiki
http://dev.ardupilot.com/wiki/building-the-code/
