### ISSUE TITLE
Wiki bug: GPS_RAW_DATA = 5 records RAWX data at 1Hz

### ISSUE THREAD

**Issue by ThorstenDP** [diydrones/ardupilot#2936]
Hi all,
I have set GPS_RAW_DATA to 5 but GRXH/GRXS data is only recorded at 1Hz, while GPS is at 5Hz. 
There is also a small typo in the Wiki at http://copter.ardupilot.com/wiki/arducopter-parameters/#raw_data_logging_gps_raw_data: MHz vs Hz.
Best regards,
Thorsten

**Comment by WickedShell** [comment]
That's a bug in documentation. 1 should be 5 Hz. The number provided there is meant to be the interval between GPS samples that raw data should be logged at.

**Comment by ThorstenDP** [comment]
Thanks! 
That's not 100% intuitive but makes sense :-)
I updated the title accordingly.

**Comment by WickedShell** [comment]
Fixed with #3268.
