### ISSUE TITLE
Use MAV_SEVERITY_INFO on appropriate messages

### ISSUE THREAD

**Issue by DonLakeFlyer** [diydrones/ardupilot#2956]
There are a number of messages which seem like they should be MAV_SEVERITY_INFO. For example: when you request the parameter list the firmware sends out mavlink messages with various firmware version info set to MAV_SEVERITY_WARNING. This in turn causes QGroundControl to thinks these are errors since they are marked as warning. Shouldn't these be MAV_SEVERITY_INFO? There may be others. I'm just getting started with APM Flight Stack support in QGC. This is what I've found so far.

**Comment by DonLakeFlyer** [comment]
@rmackay9 This time I put it in the write palce. Can you assign to me?

**Comment by rmackay9** [comment]
@DonLakeFlyer, wish I could!  No idea how to get new people to appear in the drop-down list.  Maybe once you do a PR or something it'll appear.

**Comment by billbonney** [comment]
It seems the problem is this line https://github.com/diydrones/ardupilot/blob/master/ArduCopter/GCS_Mavlink.cpp#L2025
Which changed from severity LOW to Severity Warning when that doesn't make sense for all that call it. For example when a waypoint is reached. 

BTW: You need to be a collaborator to get access to the labels etc !

**Comment by rmackay9** [comment]
@billbonney, @DonLakeFlyer 
Ok, I think I remember Tridge trying to decide if we needed a MAV_SERVERITY parameter for that call or not.  At the time they were all sent with the same severity so we left it out.  I guess we need to add it.

**Comment by ggregory8** [comment]
I propose changing to MAV_SEVERITY_INFO at least. As most use cases of this are for low priority messages. The problem we have now is all these 'info' messages, such as firmware version etc, are being displayed on Mission Planner HUD and translated to voice as they have a warning severity.

**Comment by magicrub** [comment]
I agree with Glen

**Comment by rmackay9** [comment]
I think adding a severity to the gcs_send_text_fmt message would be best.  That way we can specify what severity should be used for each message we want to send.

**Comment by ggregory8** [comment]
Ok that sounds like the best plan. Will it make 3.3.1? Otherwise this annoying issue could be around for awhile until next release.

**Comment by rmackay9** [comment]
No real changes besides the one bug fix are in 3.3.1 I'm afraid so this won't make it.
