### ISSUE TITLE
i wish to make a skateboard

### ISSUE THREAD

**Issue by long9383** [diydrones/ardupilot#3006]
i hope to use the balance to control two motors around,how to connect the line and program?

**Comment by magicrub** [comment]
Hi @long9383,
You've posted a help request to the bug tracking issues list for Ardupilot. This is for bug tracking and feature requests, not a help forum. Please repost to the forums at http://ardupilot.com/forum/

**Comment by long9383** [comment]
here can ask something?

Date: Wed, 14 Oct 2015 21:36:01 -0700
