### ISSUE TITLE
need help download compiled AC3.3 RC8 for quadcopter

### ISSUE THREAD

**Issue by roque-canales** [diydrones/ardupilot#3008]
Hello, Does any one could help me sending me link to download AC3.3 rc8 ?

Since I have updated my IRIS+ to 3.3 final, telemetry on my rc transmiter no work, srenn apears no data...

**Comment by khancyr** [comment]
here : http://firmware.diydrones.com/Copter/ rc8 release date is 25/07/2015 according to https://groups.google.com/forum/#!topic/drones-discuss/wAuCJmOP7Aw

**Comment by squilter** [comment]
Also, AC3.3 should work.  Make sure that your `SERIAL2_PROTOCOL` parameter is set to 3.
