### ISSUE TITLE
DO_CHANGE_SPEED should be allowed to set a zero speed

### ISSUE THREAD

**Issue by jschall** [diydrones/ardupilot#3018]
We enforce an arbitrary minimum of 2m/s for DO_CHANGE_SPEED. Shots features on Solo depend on setting the speed lower than that.

See Solo implementation:
https://github.com/3drobotics/ardupilot-solo/compare/94a56432c958248b02f36755b3a5426c0a217c9a%5E...7960cfa970c2361453f67c29e09d6da664ff7a65

**Comment by magicrub** [comment]
Why not post a pull request instead of an issue?
