### ISSUE TITLE
DO_CHANGE_SPEED persists across mode changes

### ISSUE THREAD

**Issue by jschall** [diydrones/ardupilot#3019]
Re-initializing waypoint navigation should reset WPNAV_SPEED to stored value
https://github.com/3drobotics/ardupilot-solo/compare/78559a4e9955f27dd963c76a520ecf009055652e%5E...78559a4e9955f27dd963c76a520ecf009055652e

**Comment by magicrub** [comment]
Why not post a pull request instead of an issue?

**Comment by rmackay9** [comment]
closed or not I agree we have an issue with the waypoint speed and how it's completely global and persistent.  It's not clear in my mind at least how we should handle the speed but Jon and I are planning to discuss it (and will also likely send a proposal to drones-discuss) just before implementing a change.
