### ISSUE TITLE
Plane: 2 different throttle failsafe criteria

### ISSUE THREAD

**Issue by dongfang** [diydrones/ardupilot#302]
Throttle fail-safe test is not consistent with actual failsafe activation:

In radio.pde, throttle radio-in value is compared to g.throttle_fs_value, aka parameter THR_FS_VALUE
In test,pde (plane and rover) , test_failsafe, the test in radio.pde is used RC_Channel::get_failsafe() is used instead, which is just 50 below radio minimum.

Suggest deleting RCChannel::get_failsafe and the unused RCChannel::control_mix.

**Comment by gmorph** [comment]
Resolved by this PR
https://github.com/diydrones/ardupilot/pull/2803
Closing 
Thanks, Grant.
