### ISSUE TITLE
MAV_SYS_STATUS_SENSOR_3D_MAG should be deasserted in SYS_STATUS message when compass is not calibrated

### ISSUE THREAD

**Issue by jschall** [diydrones/ardupilot#3021]
Solo implementation: https://github.com/3drobotics/ardupilot-solo/compare/6e2d9aab3b425c97b0922a9fe2a2b7319f3123c6%5E...6e2d9aab3b425c97b0922a9fe2a2b7319f3123c6

**Comment by magicrub** [comment]
Why not post a pull request instead of an issue?
