### ISSUE TITLE
Accelerometer corrections are applied in the wrong order

### ISSUE THREAD

**Issue by jschall** [diydrones/ardupilot#3022]
This applies to both the existing calibration routine and the new one that Solo implements.

Solo implementation: https://github.com/3drobotics/ardupilot-solo/compare/150bf6b8ce198499ce4dd6eb5f1b57c4b42dc3f7%5E...150bf6b8ce198499ce4dd6eb5f1b57c4b42dc3f7

**Comment by magicrub** [comment]
Why not post a pull request instead of an issue?

**Comment by jschall** [comment]
I'm currently just issue-ifying the various Solo features to open discussion as to whether they are wanted, not yet really investigating whether the commits rebase cleanly. I don't want to create a ton of PRs that turn out to be unwanted.
