### ISSUE TITLE
c# code to translate serial data to acceleration and velocity

### ISSUE THREAD

**Issue by gbaski5** [diydrones/ardupilot#3033]
Hi guys,

#YPRAMG=16.29,14.04,6.69,-60.21,21.25,220.43,288.59,-71.59,348.22,-7.25,4.97,11.00
#YPRAMG=17.23,15.02,5.94,-53.28,14.49,210.14,283.16,-75.24,351.21,-59.25,62.97,100.00
#YPRAMG=17.82,14.23,4.78,-61.94,13.52,220.43,279.47,-81.56,354.17,-72.25,-54.03,78.00
#YPRAMG=17.35,15.22,4.31,-60.21,18.35,220.43,281.31,-78.85,353.19,20.75,35.97,-53.00
#YPRAMG=17.06,15.22,4.54,-62.81,10.63,229.79,276.70,-86.99,354.13,9.75,-5.03,-35.00
#YPRAMG=17.00,15.34,3.84,-66.27,21.25,220.43,279.51,-79.78,352.18,23.75,8.97,6.00
#YPRAMG=16.49,15.96,4.85,-55.01,15.46,226.05,281.31,-78.85,353.19,50.75,-7.03,-81.00
#YPRAMG=15.89,14.92,4.59,-59.34,22.22,216.69,281.41,-72.57,353.24,30.75,-3.03,-49.00
#YPRAMG=16.53,15.17,5.21,-61.94,22.22,222.30,283.21,-71.64,353.24,-8.25,15.97,54.00
#YPRAMG=16.59,15.36,5.45,-56.74,23.18,224.18,282.31,-72.57,351.23,-5.25,3.97,12.00

Above is the data i got from the imu on serial, how do i get acceleration, velocity and altitude from this information using C#. really need assistance here...

**Comment by gmorph** [comment]
This doesn't appear to be an issue with ArduPilot especially as its not written in C#.  Its a generic development question.  I'm gunna close.
Thanks, Grant.
