### ISSUE TITLE
ArduCopter HIL firmware compiling not working

### ISSUE THREAD

**Issue by ComfyMobile** [diydrones/ardupilot#3044]
Can I build ArduCopter HIL mode firmware? When trying to compile the current release we get error about variable "sonar" absence in Copter.h. Thank you!

**Comment by magicrub** [comment]
In Copter 3.3 and Plane 3.4 you no longer need to compile for it. It's a param.

**Comment by ComfyMobile** [comment]
how can i switch on this param? where? Thank you very much for help!

**Comment by magicrub** [comment]
My mistake, the param HIL_MODE is only on plane. I thought it was global.
http://plane.ardupilot.com/wiki/arduplane-parameters/#hil_mode_enable_arduplanehil_mode

-TomP

**Comment by rmackay9** [comment]
@ComfyMobile, @magicrub, HIL in copter hasn't worked in literally years so I can't say I'm surprised it's not compiling or working.  I think it'll be some work to get it sorted.. but that's not something that I can personally take on in the near future.
