### ISSUE TITLE
Copter: Flip mode glitch

### ISSUE THREAD

**Issue by earsneyes** [diydrones/ardupilot#3076]
I stumbled upon a problem with flip mode in AC 3.3 / 3.4-dev.

When you trigger a flip it will roll (to the right) after doing the flip.

Sitl does it as well:
	
Start SITL:
cd ~/ardupilot/ArduCopter
`~/ardupilot/Tools/autotest/sim_vehicle.sh -v ArduCopter -L HAM --map --console`
`arm throttle`
`rc 3 1666`
`flip`

Got it on video for the thrill: https://www.youtube.com/watch?v=FoJkj9W1mCI

Log: http://firmware.bbbmini.com/24102015_flipmode.zip

**Comment by imrj** [comment]
I have duplicated the same issue over and over again with AC3.3....abrupt turn to right after flip

**Comment by magicrub** [comment]
smells like an integrator that needs be gated during the flip

**Comment by R-Lefebvre** [comment]
At what point to you change back out of Flip mode?  (ie: Does the
roll-right error stop by itself eventually, or do you have to take back
manual control?)

**Comment by earsneyes** [comment]
Flew in stabilize then triggered the Flip with Channel 8 (spring loaded switch)

The roll stops by itself after the short roll to the right. 
I just needed to counter steer to get it back on the ground.

**Comment by rmackay9** [comment]
I've reproduced in the simulator so it's certainly a code problem.  I'm looking into it'll be a simple or more difficult fix.

**Comment by earsneyes** [comment]
Thanks for looking into this.

**Comment by rmackay9** [comment]
This is fixed in master now and will go out with Copter-3.4.  We're planning to start testing 3.4 in early January with the hopes of going live with it by end of Feb.

With a little more work we could probably come up with a patch to fix Copter-3.3 as well.  It should be a one line fix to update the earth-frame rates.  Obviously we'd like to patch it.. it's just a matter of time.

**Comment by earsneyes** [comment]
Perfect. 
Im going to fly with master soon. 
Thanks!
