### ISSUE TITLE
Buzzer sounds

### ISSUE THREAD

**Issue by rsg85** [diydrones/ardupilot#3080]
Ive just installed a buzzer on the A5 pin and took it out for a test fly.

Im getting the correct sounds for Arm and Disarm, but im also receiving a sequence of 5 beeps at a time throughout the flight

Any ideas what this sound is for?

**Comment by rmackay9** [comment]
@rsg85, we've got some info on the wiki here: http://copter.ardupilot.com/wiki/nav-leds/
My guess is it's the battery failsafe.

By the way, better to raise questions in the support forum.  http://ardupilot.com/forum/viewforum.php?f=3&sid=dc3e144a5272c06b73f2baeb4a557703
