### ISSUE TITLE
ArduPlane - buzzer FR for APM2

### ISSUE THREAD

**Issue by mariansoban** [diydrones/ardupilot#3136]
It would be nice to have same buzzer functionality, at least for arming/disarming, like in ArduCopter 3.2 by using of active buzzer connected e.g. to A5 port of APM.
See my changes for example: https://github.com/mariansoban/ardupilot/commit/887aa4d54bc8e3648345bf55740529063b2e3364
https://www.youtube.com/watch?v=uWPteVr3m7Q

**Comment by WickedShell** [comment]
Closing as APM2.X is no longer a target that is developed against for plane.

**Comment by mariansoban** [comment]
ok, here is the unofficial version which also includes fix for https://github.com/diydrones/ardupilot/issues/3136, if anyone is interested in:
https://github.com/mariansoban/ardupilot/releases/tag/ArduPlane-AVR-3.4.0-sobi-v2
