### ISSUE TITLE
Changing decimal places in Quick view menu

### ISSUE THREAD

**Issue by aemonesi** [diydrones/ardupilot#3143]
I am trying to figure out if there is a way to change the decimal places in the Quick view menu at the bottom left of the screen in Flight Data.  I am new to the program and operations but I have found that having the airspeed and altitude out to the second decimal place clutters the screen when decimals for those parameters are not entirely necessary.  If anyone knows how to change that or where I could find the code to change this it would be much appreciated.  thanks

Andy

**Comment by magicrub** [comment]
This is not an autopilot bug report or feature request. You're talking about a GCS but did not name it. 
Mission Planner: https://github.com/diydrones/MissionPlanner/issues
APM Planner: https://github.com/diydrones/apm_planner/issues

but this sounds like something custom you want. In that case those likes will also get you to the source code and you can compile it yourself.
