### ISSUE TITLE
Plane: APM init does not terminate if I2C inoperative

### ISSUE THREAD

**Issue by dongfang** [diydrones/ardupilot#315]
ArduPlane 2.73 on APM1. Barometer and compass simulated dead by connecting SDA to SCL.
Expectation: APM firmware is writen to cope with an inoperative barometer and a ditto compass (barometer_healthy flags etc.)
Result: Startup does not complete. APM unresponsive to MAVLink.
Last message appears in a terminal to be a text message, �3�Calibrating barometerp�� ���+���+���`'��� . From then on, silence.
APM2 test follows.

**Comment by gmorph** [comment]
I don't think this test is valid.  In addition no further development work will be done on the APM1 so I am closing this issue out.  If anyone has objections please let me know.
Thanks, Grant.
