### ISSUE TITLE
unequal parenthesis in ardupilot/ArduCopter/control_rtl.cpp

### ISSUE THREAD

**Issue by derekxm** [diydrones/ardupilot#3172]
in line 124 of ardupilot/ArduCopter/control_rtl.cpp
destination.z = pv_alt_above_origin(rtl_alt));
There is an extra parenthesis.
Because AC_RALLY is enabled by default, the compiler will not catch it.

**Comment by rmackay9** [comment]
fixed, thanks!  Also added a new define for AC_TERRAIN that allows it to be turned off (so that rally can be turned off)
https://github.com/diydrones/ardupilot/commit/05246ea0c74f636042663b0ccd57971780aa014c
