### ISSUE TITLE
Division by zero in AP_NavEKF_core

### ISSUE THREAD

**Issue by alexbuyval** [diydrones/ardupilot#3174]
After rebase my own branch with master I have faced out with runtime error in the SITL mode in the following line:

https://github.com/diydrones/ardupilot/blob/master/libraries/AP_NavEKF/AP_NavEKF_core.cpp#L874

**Comment by rmackay9** [comment]
Thanks for the report.  I've ping'd Paul.

**Comment by priseborough** [comment]
dtDelVel is a weighted average of the delta time returned by the INS library get_delta_velocity function.

I will put in protection against that, but if the get_delta_velocity function is returning zeros for delta time, then there is another error, either in the INS library, or more likely in the simulator.

**Comment by priseborough** [comment]
https://github.com/diydrones/ardupilot/pull/3183

**Comment by tridge** [comment]
hi Alex, can you tell us how to reproduce this? It shouldn't be possible

**Comment by alexbuyval** [comment]
I have got this error in [ROS/Gazebo SITL mode](http://dev.ardupilot.com/wiki/using-rosgazebo-simulator-with-sitl/). I think that maybe the simulation environment produce invalid data during initialization. This error occures on the first call of UpdateStrapdownEquationsNED method always.

**Comment by priseborough** [comment]
This cannot happen with the flight code
