### ISSUE TITLE
Runtime error in AP_NavEKF2_core

### ISSUE THREAD

**Issue by alexbuyval** [diydrones/ardupilot#3175]
I have faced out with the runtime error if I disabled a compass in the following line:

https://github.com/diydrones/ardupilot/blob/master/libraries/AP_NavEKF2/AP_NavEKF2_core.cpp#L206

I think, we should check the  _ahrs->get_compass() on 'null'

Please note, I am using the ROS SITL mode. I did not check it on real drone.

**Comment by priseborough** [comment]
Please update the line reference for current master

**Comment by alexbuyval** [comment]
[magSelectIndex = _ahrs->get_compass()->get_primary();](https://github.com/diydrones/ardupilot/blob/master/libraries/AP_NavEKF2/AP_NavEKF2_core.cpp#L250)

**Comment by alexbuyval** [comment]
Also I have got the same runtime error in AP_NavEKF2_Measurements.cpp in the following line:
[uint8_t maxCount = _ahrs->get_compass()->get_count();] (https://github.com/diydrones/ardupilot/blob/master/libraries/AP_NavEKF2/AP_NavEKF2_Measurements.cpp#L164)

**Comment by priseborough** [comment]
This is not an EKF issue. That routine should not be able to return null.
