### ISSUE TITLE
Bad AHRS warning too strict?

### ISSUE THREAD

**Issue by GrahamDyer** [diydrones/ardupilot#3179]
A number of people (including myself) are getting the Bad AHRS warning on our Pixhawk or AUAV-X2 boards. Are the checks for this perhaps a little too strict?
Ref: http://diydrones.com/forum/topics/bad-ahrs

**Comment by magicrub** [comment]
Are you, and the others, running the latest release? It's much better now.

**Comment by R-Lefebvre** [comment]
I get it way too frequently too.

**Comment by GrahamDyer** [comment]
Running AP 3.4 and AC 3.3, getting on both

**Comment by severinleuenberger** [comment]
Running APM 3.4 plane and see it to often as well

**Comment by OXINARF** [comment]
Maybe related to #3171?

**Comment by rmackay9** [comment]
Yes, I suspect @OXINARF is right.  Maybe we should add this to the list for a Copter-3.3.2 patch release.

**Comment by magicrub** [comment]
And plane v3.4.1

**Comment by R-Lefebvre** [comment]
But if I'm reading it right, according to Paul this was already fixed in 3.3.1?

**Comment by OXINARF** [comment]
No, it was fixed after the 3.3.1 release.

**Comment by R-Lefebvre** [comment]
Ah, I see.  I read "since the release" the wrong way.

**Comment by OXINARF** [comment]
To supply more info: the commit that Paul said that fixed it should be 59df23b, which came from the PR #3101

**Comment by mtcl** [comment]
Same issue here, I am getting Bad AHRS error also, this happened so much while flying hat it made the copter crash. Its a brand new Pixhawk's second flight.

**Comment by rmackay9** [comment]
@mtcl, this should cause crashes so it would be good to provide a dataflash log.

**Comment by Zanquar** [comment]
calibrate Accel again and again, and then, the warning can be solved

**Comment by magicrub** [comment]
Not all IMUs are created equal (mfgr error), nor are the calibrations (human error). I've added a param "INS_ACCTHRESH" to help loosen it for mfgr type error. https://github.com/diydrones/ardupilot/pull/3364
Is that good enough to close this or is more work needed to fix the root cause?

Also, EKF2 is more tolerant (it can compensate faster/better) so the thresholds could be loosened when EKF2 is used.

**Comment by courierdude** [comment]
Has anybody found a solution to BAD AHRS? Please, I'm begging you. This is my third day of re installing firmware, doing ACCEL calibrations, GPS calibrations, Googling, and generally pulling my hair out.

**Comment by magicrub** [comment]
fixed with https://github.com/diydrones/ardupilot/pull/3364 on Plane v3.5.0
