### ISSUE TITLE
External baro via I2C or SPI

### ISSUE THREAD

**Issue by luin1** [diydrones/ardupilot#3211]
Is it possible to connect an external baro and selecting in the software from which you want to use? external or internal?
The external sensors:
MPL3115A2 - https://www.sparkfun.com/products/11084
or
MPL115A2 - https://www.adafruit.com/product/992
or
LPS331AP - https://www.pololu.com/product/2126
or good MS5611 via I2C - http://www.ebay.pl/itm/MS5611-Pressure-Barometric-sensor-board-from-MEAS-/280786878092

**Comment by rmackay9** [comment]
Yes, I think it's possible to connect an external baro although i haven't seen anyone do it.  The MS5611 would be the one to try with.  If it doesn't work, please email drones-discuss@googlegroups.com and we can probably help.
