### ISSUE TITLE
GPS failsafe

### ISSUE THREAD

**Issue by khancyr** [diydrones/ardupilot#3230]
Hi,

I was look for what is doing copter in case of gps lost. According to the wiki, there is a FS_GPS_ENABLE parameter for GPS Failsafe http://copter.ardupilot.com/wiki/gps-and-gcs-failsafes/

But looking in parameter for copter v3.3.1 (fresh install and reset parameter to default), it is missing.
![gps_failsafee_missing](https://cloud.githubusercontent.com/assets/705341/11396176/0fae4648-9370-11e5-9208-d4b226aa681e.PNG)

Is the GPS failsage merged with EKF failsafe (and the wiki is outdated) or there is a problem ?

**Comment by rmackay9** [comment]
@khancyr, yes, it's been merged with the EKF failsafe now.  So we should update those docs.
