### ISSUE TITLE
MAVLink and Ardupilot communication

### ISSUE THREAD

**Issue by Kurokawa10** [diydrones/ardupilot#3272]
I would like to know in which class of the code of ardupilot is contained the method to link the message it gets (from gsc) with its library of MAVlink and how it works.

Thanks.

**Comment by magicrub** [comment]
Hi @Kurokawa10 You've posted a help question on the github issue/new_feature/TODO tracker for the developers. General questions like this are handled in the forums or drones-discuss.

Common library code: 
https://github.com/diydrones/ardupilot/blob/master/libraries/GCS_MAVLink/GCS_MAVLink.cpp

And additional platform-specific stuff in:
https://github.com/diydrones/ardupilot/blob/master/ArduPlane/GCS_Mavlink.cpp
or
https://github.com/diydrones/ardupilot/blob/master/ArduCopter/GCS_Mavlink.cpp
or
https://github.com/diydrones/ardupilot/blob/master/APMrover2/GCS_Mavlink.cpp
