### ISSUE TITLE
Is there no altitude control with Range finder in auto mode?

### ISSUE THREAD

**Issue by EricXiao1990** [diydrones/ardupilot#3273]
I'm using Range finder, and when flying in althold,  poshold mode or someone else, it was great. But when flying in auto mode, maybe there is no use with range finder.

 Then, I went to check code, I got that altitude only calculated from barometer, while sonar alt from range finder  didn't get into the altitude controller.

 I'm not sure about this problem, if I need use range finder in auto mode, you have some suggestion? If this is an issue, I wonder whether this will be added to future release?

Thanks!

**Comment by rmackay9** [comment]
That's right, the range finder is not used in Auto or Guided.  It's on this issues list somewhere..
