### ISSUE TITLE
Plane: Change short failsafe behavior from CIRCLE to RTL

### ISSUE THREAD

**Issue by dab150** [diydrones/ardupilot#3296]
I propose changing the short failsafe action from CIRCLE to RTL in the plane code.

In our experience it seems that whether you go into the failsafe behavior due to telemetry loss or radio signal loss, going into CIRCLE doesn't do anything to help you and you eventually will go into the long failsafe action of RTL anyways.

**Comment by magicrub** [comment]
CIRCLE is for short FS, it does RTL for long FS already. If you don't want circle then set the short fs timer to be just a tiny bit less than long timer. Example: you only want long timer of 20 so set short to 19.9.
