### ISSUE TITLE
Trouble finding GPS coordinates

### ISSUE THREAD

**Issue by ACME666** [diydrones/ardupilot#3315]
I'm having trouble finding the exact line where the GPS coordinates information step is made towards my screen real-time. To this day, I've only found that a Log file is created every 1/50 seconds in one of the methods of the arducopter class which calls dataflash.Log_Write_GPS.
The method I'm looking for must define some kind of telemetry (tlog file) or a log file sent through mavlink.
Any help or indication will be welcomed.
Thank you.

**Comment by magicrub** [comment]
Hi @ACME666 
You've posted a help question in the bug/feature_request/TODO list for developers. Please use the forums (general help) or drones-discuss discussion thread (developer help).
https://groups.google.com/forum/#!forum/drones-discuss
Sorry for closing, but if we don't enforce this the TODO list gets cluttered
