### ISSUE TITLE
why STIL cant work???

### ISSUE THREAD

**Issue by ahmedelbacksawy** [diydrones/ardupilot#3329]
i done more than 10 times the steps from that link http://dev.ardupilot.com/wiki/sitl-native-on-windows for SITL with out any use .... all times with the same problem on that line (Download and make ArduPilot)
what can i do ??? i need it very fast for my project to test my code :\

**Comment by magicrub** [comment]
Duplicate of https://github.com/diydrones/ardupilot/issues/3269

**Comment by rmackay9** [comment]
@ahmedelbacksawy, I personally always run SITL within a VM
http://dev.ardupilot.com/wiki/setting-up-sitl-on-windows/

**Comment by ahmedelbacksawy** [comment]
@rmackay9  is that work fine ???

**Comment by rmackay9** [comment]
@ahmedelbacksawy, yes, it works a-ok.

**Comment by magicrub** [comment]
I think most devs use SITL on Linux or Linux with VM.
