### ISSUE TITLE
Add parameter to inhibit failsafe in AUTO mode

### ISSUE THREAD

**Issue by AndKe** [diydrones/ardupilot#333]
For some AUTO missions, failsafe needs to be disabled. When the mission prohibits heading towards home from any point (could hit a mountain) or is expected to fly beyond reliable control range.  Even momentary RTL can be disruptive for aerial photo mission.

If failsafe is completely disabled, then we lose a good safety feature before and after the autonomous mission.

Please add:

if MODE=AUTO  and FS_AUTO_ENABLE  = "1" - then  let failsafe condition use setting in FS_SHORT_ACTN  or FS_LONG_ACTN

if MODE=AUTO and FS_AUTO_ENABLE = "0" - then resume mission and inhibit use of failsafe actions

**Comment by gmorph** [comment]
There is a parameter THR_FAILSAFE that allows you to enable/disable the failsafe which I believe achieves this functionality.  If anyone thinks differently please let me know.
Thanks, Grant.

**Comment by AndKe** [comment]
I solved it a while ago by adding another gcs failsafe setting, so it's solved and in master.
