### ISSUE TITLE
Field 'roll_sensor ' could not be resolved

### ISSUE THREAD

**Issue by whyscience** [diydrones/ardupilot#3332]
too many errors 
I do as follows http://dev.ardupilot.com/wiki/editing-the-code-with-eclipse/ 

but it occurs this 

Field 'ToDeg(ahrs.get_gyro().x)' could not be resolved

Description	Resource	Path	Location	Type
Field 'yaw_sensor' could not be resolved	ArduCopter.cpp	/ArduCopter	line 575	Semantic Error

How is it ?
Help !

**Comment by magicrub** [comment]
Ignore the errors within eclipse, you have to run make per the instructions.

**Comment by WickedShell** [comment]
Closing this is a dev env problem, that @magicrub anwsered awhile ago.
