### ISSUE TITLE
Adding a new Flightmode(Plane)

### ISSUE THREAD

**Issue by Leomessi1000** [diydrones/ardupilot#3334]
I tried to add a new Flightmode. I implement the MissonPlanner. (I use ArduPlane V2.74b)
 It's explained on http://dev.ardupilot.com/wiki/apmcopter-adding-a-new-flight-mode/
 However,this page explained only a copter code. I would like to know how to add a new Flightmode about a Plane.
 Has anyone got an idea?

**Comment by rmackay9** [comment]
Probalby best to ask in drones-discuss@googlegroups.com.  I'm going to close this here if that's ok.
Tom Pettinger is probably the person who could answer your questoin.

**Comment by magicrub** [comment]
Last I saw the example itwas very generic and should work for all
platforms. Have you tried looking at plane yet?
