### ISSUE TITLE
Does the aux5 relay for camera actuation work?

### ISSUE THREAD

**Issue by rscarawa** [diydrones/ardupilot#3340]
Not sure if this is an issue or just me.  I have been trying to get my pixhawk to snap a picture with my S110.  I have been able to use a battery on my chdk cable to make it snap.  My pix is in a plane with a 5v bec connected to the rail of pins so I should have the required voltage. 

Looking at the instructions and samples, it is very confusing.  Some demos show a camera connector with the red and black wire next to eachother.  Some show it with the center pin open.  Which configuration is right?  The mission planner software seems to push you to using RC7 as a shutter channel.  I tried hooking to it and get no actuation.  Some demos call for using RC10/Aux2.  No good either.  Another says to use aux5 and configure it as a relay.  Does pixhawk have a built in relay that is supposed to send a voltage signal to the camera?  I saw elsewhere people had issues making this work but it was over a year ago.  Is this still an issue?  Do I need to have my own external relay or is this feature just not working?

Thank you for your understanding if this is already addressed or noted.

Scot

**Comment by R-Lefebvre** [comment]
This Issues List is for a confirmed problems with the software.  This is a support problem, and it likely hardware related. The other existing issue you posted on just after this one actually holds the answer.
