### ISSUE TITLE
a little help is needed please(pixhawk, Minimum Osd ) 

### ISSUE THREAD

**Issue by Mamoshi** [diydrones/ardupilot#3353]
Hi
I have my Pixhawk which has made tons of problems for me lately ( compass Inconsistense problem)
so now that I have opened it, I would like to install minimum osd on it, and I am hoping everything will work flawless when I put everything back together :)

 My question.

  I have 3D radio hooked up to telem.1, and I am thinking thinking the Osd goes to the telem.2 port doesnt it?
If so, do I have to do anything with the Pixhawk for telem. port 2 to work with the Minim osd ?

         Thank you very much in advance

**Comment by magicrub** [comment]
Hi @Mamoshi 
You've posted a help question in the developer TODO list. Please refer to the wiki, it should answer all your configuration/setup questions. http://plane.ardupilot.com/wiki/common-minim-osd-quick-installation-guide/
