### ISSUE TITLE
Non cyclic logging

### ISSUE THREAD

**Issue by dongfang** [diydrones/ardupilot#337]
Sometimes it is useful that logs are not overwritten. eg. if there is a risk or a lpan that the plane (drone) lands out of range and will overwrite useful log data until the battery runs out.
An option, enabled by a parameter, could do (if I undrestood the implementation correctly): At bootup, store the position where this flight session's logging begins. When the block pointer wraps around to overwrite the beginning of same flight's log, stop. So, same-flight data should not be overwritten when storage full. Other flights' data is overwritten as normally.

**Comment by gmorph** [comment]
On the current generation of hardware (Pixhawks etc) there is an SDCard where the logs are written.  This can store many many hours of logs.  Far more then the battery will last running the Autopilot.
For previous generation APM2 this is such a niche case that it will never be implemented.  I'm going to close.
Thanks, Grant.
