### ISSUE TITLE
GCS param writes occasionally timeout

### ISSUE THREAD

**Issue by magicrub** [diydrones/ardupilot#3393]
GCS param writes occasionally timeout. Happens on multiple GCSes when writing bulk params. @peterbarker has duplicated on master.

**Comment by peterbarker** [comment]
My duplication was traced to a bad telemetry radio.  Replacing the radio fixed the issue for me.

I am now unable to reproduce this issue on master, sorry.

Peter

**Comment by magicrub** [comment]
<sadface>

**Comment by magicrub** [comment]
bummer! Ok, I'll keep poking around. Thanks for your help!

**Comment by imrj** [comment]
this has happened to me too, it does seem to be when more than one GCS connected, but not all the time either

**Comment by magicrub** [comment]
Happens to me with a single companion computer connected. No "GCS" per se.

**Comment by magicrub** [comment]
this was tracked down to our GCS behavior. We were writing 450 params to the pixhawks which is not a very good idea. We're now doing a read modify write operation and is much faster and stable.
