### ISSUE TITLE
Support for 12 or 16 channels of PPMSum receiver.

### ISSUE THREAD

**Issue by micropet** [diydrones/ardupilot#340]
Please install a support for 12 or 16 channels of PPMSum receiver.

On the original Mikrokopter we can use the Graupner GR16 or Jeti RMK2 receiver with 16 channels. 8 channels are too few for the many opportunities offered by the AMPCopter.

Peter

**Comment by gmorph** [comment]
The Pixhawk supports 14 input channels.  The APM2 (AVR) now supports 11.  The APM2 will never support more then 11.  The Pixhawk will probably support more then 14 one day.  If everyone is ok I'm going to close this issue as we have addressed the original request i.e. support more then 8 channels.
If I don't hear anything by 11/9/2015 I will close this out.
Thanks, Grant.

**Comment by rmackay9** [comment]
yeah, we do at least 12 for copter.. closing sounds good to me.

**Comment by hpcre** [comment]
Agree to close,  as it has been pointed out that apm will never support more than 11.
Thanks Grant,  Randy.

**Comment by marcmerlin** [comment]
Could http://copter.ardupilot.com/wiki/common-pixhawk-and-px4-compatible-rc-transmitter-and-receiver-systems/ and other relevant places, be updated to state that pixhawk will only read 14 PPMSUM channels from your receiver? I couldn't find this limit anywhere.
Actually right now I can only see 12 channels via PPMSUM and I'm trying to figure out why.

**Comment by marcmerlin** [comment]
Looks like pixhawk only sees 12 channels if I connect my openlrsng module via PPMSUM , but I see 16 if I connect via SUMD to the spektrum satellite port (AP 3.4)
This should be documented.

**Comment by marcmerlin** [comment]
I've now just opened a bug to request raising PPMSUM/CPPM support from 12 channels to 16
https://github.com/diydrones/ardupilot/issues/3337
Turns out that using SUMD or inverted SBUS on openlrsng prevents using serial passthrough since they share the same UART, so I do need to use CPPM on my openlrsng module afterall, but I'm stuck at 12 channels instead of 16.

**Comment by povlhp** [comment]
CPPM supports any number of channels. Could be 100. Cost is 2ms per extra channel. And device receiving it must be able to handle it.

**Comment by marcmerlin** [comment]
@povlhp yes, but ardupilot has some resync code where if it sees too many channels, it starts over. I'm just surprised it stops at only 12 and not at least 16.
