### ISSUE TITLE
g.command_total +-1 confusion

### ISSUE THREAD

**Issue by dongfang** [diydrones/ardupilot#344]
In ArduPlane: (if this is a realy problem it may appear in ArduCopter etc. too):

I cannot find consistently if command number [g.command_total] is a valid command or if it is beyond the end of the list. Is there a +-1 error?

AdruPlane, commands_process.pde:
do_jump:
    if (next_nonnav_command.p1 >= g.command_total) {
    	// p1 is the index to jump to.
        gcs_send_text_fmt(PSTR("Skipping invalid jump to %i"), next_nonnav_command.p1);
        return;        
    }
--> commands[g.command_total] is BEYOND the end of the list.

process_next_command():
        if(nav_command_index > g.command_total) {
            // we are out of commands!
            gcs_send_text_P(SEVERITY_LOW,PSTR("out of commands!"));
and later:
    if (nav_command_index <= (int)g.command_total && non_nav_command_ID == NO_COMMAND) {
        temp = get_cmd_with_index(non_nav_command_index);
-->commands[g.command_total] is NOT beyond the end of the list

comand.pde:
static void update_auto()
{
    if (g.command_index >= g.command_total) {
        handle_no_commands();
--> commands[g.command_total] is BEYOND the end of the list.

static struct Location get_cmd_with_index_raw(int16_t i)
{
..
    // Find out proper location in memory by using the start_byte position + the index
    // --------------------------------------------------------------------------------
    if (i > g.command_total) {
        memset(&temp, 0, sizeof(temp));
        temp.id = CMD_BLANK;
--> commands[g.command_total] is BEYOND the end of the list.

Looking at GCS_Mavlink.pde in ArduPlane, it appears in 
case MAVLINK_MSG_ID_MISSION_COUNT:
that
g.command_total.set_and_save(packet.count - 1);

so g.command_total is one less than the # of WPs sent. That makes 
commands[g.command_total] NOT beyond the end of the list.

**Comment by gmorph** [comment]
This code has been completely re-written since this comment so it no longer applies.  If anyone thinks differently please let me know.
Thanks, Grant.
