### ISSUE TITLE
Flashing old Arducopter version issue

### ISSUE THREAD

**Issue by harewei** [diydrones/ardupilot#3495]
Hello

I'm trying to get old ArduCopter version 3.3.2 rc2 on my pixhawk
I looked at commit, and it seems to be 802ced201dac4ca08f5f4ba5139ccb1933294965

so I used
git clone https://github.com/diydrones/ardupilot oldcopter
cd oldcopter
git reset --hard 802ced201dac4ca08f5f4ba5139ccb1933294965

and with the command
make px4 
inside oldcopter/ArduCopter, which gave me 2 files inside the ArduCopter folder, ArduCopter-v1.px4 and ArduCopter-v2.px4.  Since I'm using pixhawk, I used QGroundControl to flash custom firmware ArduCopter-v2.px4.  However, when I checked the version, it says it's 3.4 dev.  Am I doing something wrong?

**Comment by rmackay9** [comment]
Harewei,
Best to use the Copter-3.3 branch.
https://github.com/diydrones/ardupilot/tree/Copter-3.3
