### ISSUE TITLE
TradHeli Disarmed Servo Filter

### ISSUE THREAD

**Issue by R-Lefebvre** [diydrones/ardupilot#35]
Create a filter on the servo output that runs when disarmed only, which will help to reduce servo noise and activity when the heli is sitting on the ground.

**Comment by gmorph** [comment]
Confirmed this is still an open issue 4/9/2015.

**Comment by R-Lefebvre** [comment]
Hi Grant, can you give more info on your feelings here?  I was actually thinking of closing this.  I don't really see a lot of servo buzz lately.  Just some minor "ticking" really.

**Comment by R-Lefebvre** [comment]
Closing this issue.  It's largely resolved by the EKF.  Servo movement now is very minimal.
