### ISSUE TITLE
Adding Code to Build Process

### ISSUE THREAD

**Issue by davidbitton** [diydrones/ardupilot#3556]
I added additional code (SBGC library) under AP_Mount, but it's not being built. The modules.mk file in the root says it's auto generated. Where do I add a reference to the code in order for it to be built when performing a `make px4-v2`?

**Comment by guludo** [comment]
@davidbitton could you point to the branch you've been working on?

**Comment by davidbitton** [comment]
My [fork](https://github.com/davidbitton/ardupilot) of master. I was able to get the code to build by moving the SBGC_lib folder alongside AP_Mount, and not as a subfolder. Then I added `LIBRARIES += SBGC_lib`to the make.inc file under `ArduCopter`. The next step now is rewrite AP_Mount_AlexMos using the sample code @alexmos published.

**Comment by guludo** [comment]
Your fork just has commits related to submodule and a merge commit.

**Comment by davidbitton** [comment]
i started down the road of adding SBGC_lib as a submodule, but I became
confused quickly with the build process. I figured, let me get the code
working first, and then I'll worry about submodules later.

On Thu, Jan 28, 2016 at 1:20 PM, Gustavo José de Sousa <
notifications@github.com> wrote:

> Your fork just has commits related to submodule and a merge commit.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/diydrones/ardupilot/issues/3556#issuecomment-176319054>
> .
>



-- 
---
David B. Bitton
Code No Evil, LLC

Code Made Fresh Daily.

**Comment by lucasdemarchi** [comment]
@davidbitton I think you figured out what's needed, right? Can this be closed?

**Comment by davidbitton** [comment]
Yes, however I'll be back when it's time to add this as a us module.

Sent from my mobile device.

Please excuse its brevity and/or typographical errors.

On Jan 31, 2016, at 11:10 AM, Lucas De Marchi <notifications@github.com>
wrote:

@davidbitton <https://github.com/davidbitton> I think you figured out
what's needed, right? Can this be closed?

—
Reply to this email directly or view it on GitHub
<https://github.com/diydrones/ardupilot/issues/3556#issuecomment-177538177>.

**Comment by lucasdemarchi** [comment]
Ok, feel free to open another issue if it's needed when you are adding it as a submodule.
