### ISSUE TITLE
Feature request:  stop the mission processing until the required altitude, time or lat/long conditions are met.

### ISSUE THREAD

**Issue by claytonasmith** [diydrones/ardupilot#363]
Hello,
This feature request is for a new mission item type that allows you to stop the mission processing until the required altitude, time or lat/long conditions are met. 

For example:  "Takeoff, then after 60 seconds 'do_set_servo 6 to 1900', then set_mode to *auto*."

Does that sound reasonable?  I meant to submit this a while ago when I talked to Tridge about it.  Also - drones-discuss link: https://groups.google.com/forum/?fromgroups#!topic/drones-discuss/GzWxr17cfHM

Thanks!
Clayton Smith

**Comment by gmorph** [comment]
We now have the CONTINUE_AND_CHANGE_ALT which we believe achieves the desired result.  I'm going to close this out but if anyone thinks differently please let me know.
Thanks, Grant
