### ISSUE TITLE
Copter: Improved Acro mode, for loop and other

### ISSUE THREAD

**Issue by robustini** [diydrones/ardupilot#367]
The recent Acro controller does not allow to perform these maneuvers, in pure flight it works better than Stabilize mode but it is not a real Acro, just a better (light) stabilized mode.

**Comment by rmackay9** [comment]
I think with all the work Leonard did on acro for AC3.2.1 we can close this.  We added a few things in AC3.3 to make it better as well like the improved thrust curve.

if people complain we can re-open although it's probably better if we open new issues with more specific improvements requeted.
