### ISSUE TITLE
Disable Joystick Button

### ISSUE THREAD

**Issue by samworthington** [diydrones/ardupilot#3673]
Would it be possible to add a "disable joystick" button to the Actions tab on the Flight Data screen? It would make flying with a PC joystick much safer by allowing a quick switch to the standard transmitter as a backup.

Ideally, it would be possible to assign the button to a joystick or keyboard button.

**Comment by WickedShell** [comment]
This is a MP issue not Ardupilot. Please open it here instead: https://github.com/diydrones/MissionPlanner
