### ISSUE TITLE
Copter: throw warnings if vibrations are higher than 0.3G

### ISSUE THREAD

**Issue by Olivier-ADLER** [diydrones/ardupilot#368]
Would it be possible to accumulate vibration measurements, compute standard deviation and RMS noise so that we can forbid next flight arming and report that in Mission Planner if noise is too large ?

This should catch a quite large amount of user problems. This issue seems to be one of the more common.

As said by Leonard Hall, we are catching a lot of beginners and bad low cost frames because Arducopter is low cost. We should help them to find and fix their hardware problems alone sending them to the right wiki page for each problem like this.

**Comment by gmorph** [comment]
This is now resolved in Copter - confirmed with Randy.
Thanks, Grant.
