### ISSUE TITLE
how to modify the default ch3 pwm out?

### ISSUE THREAD

**Issue by oceangis** [diydrones/ardupilot#3691]
I am building  a boat with ardurover 2.5 and bidirectional ESC. When i power on Pixhawk first , motor will run at high speed before powering RC. i have check the log file and found there is low pwm output with 1000 and think these is the problem. where i can modify the 1000 to 1500. 

http://diydrones.com/group/arduboat-user-group/forum/topics/how-to-modify-the-default-ch3-pwm-out?xg_source=activity

Above link has log image.

thanks.

**Comment by magicrub** [comment]
Set your rc3-trim to 1500.

**Comment by WickedShell** [comment]
There was a bug where pixhawk would momentarily send 1000 on initial start
up, but that was fixed on master about a month ago.

**Comment by oceangis** [comment]
Hi WickedShell,
    I think this is a bug and want to modify the firmware of Ardurover 2.5, can you tell me how to modify the code or the thread about this bug

**Comment by WickedShell** [comment]
It's a very brief single cycle of 1000 pwm that gets out. The exact commit
for it is
https://github.com/diydrones/PX4Firmware/commit/22b6f5752ef0cb989a383f9b05bfce9509b35daa
its for the PX4Firmware layer. Just compiling off of master will fix it.
Talking to Grant will probably lend more help then me with rover :)

**Comment by oceangis** [comment]
Hi,WickedShell,thank you very much!

**Comment by oceangis** [comment]
change the default value from 1000 to 0 ,the output value is also 1000,
