### ISSUE TITLE
use my own cards in mo

### ISSUE THREAD

**Issue by KoenigsbergPr** [diydrones/ardupilot#3692]
Hi, I`m new to github and so I`m not sure whether I wrote my issue in the correct place...

I use the following blogpost:
http://diydrones.com/profiles/blogs/using-your-own-map-data-in-mission-planner?id=705844%3ABlogPost%3A1366138&page=3#comments

But the final step (creating an .exe with visual studio 2012) doesn´t work. It seems that there are missing some files in the fork... (https://github.com/korgan/MissionPlanner)

Please help! 

Thx

**Comment by WickedShell** [comment]
This is related to mission planner and should be opened on it's issue list. Although you're actual problem is on a forked version of MP that hasn't seen any changes in ~2.5 years which means that its quite out of date at this point, I'd recommend contacting the fork maintainer directly.
