### ISSUE TITLE
Eclipse integration

### ISSUE THREAD

**Issue by sgh055** [diydrones/ardupilot#3706]
![image](https://cloud.githubusercontent.com/assets/15629613/13516253/bef7ca28-e1fb-11e5-9423-ff7cdb8b432f.png)

Import to eclipse(PX4 toolcahin)

I following here(http://dev.ardupilot.com/wiki/editing-the-code-with-eclipse/) What I missing??

**Comment by lucasdemarchi** [comment]
@zehortigoza can you help him? It's about eclipse integration.

@sgh055 I'm changing the title to reflect that this is about eclipse integration and not errors in the source code.

**Comment by sgh055** [comment]
Thank you for your answer

**Comment by ljy1992** [comment]
I've got the same problem, what's the solution of this problem? It seems the libraries are not included correctly...
