### ISSUE TITLE
max climbing speed (PILOT_VELZ_MAX ) needs larger max value

### ISSUE THREAD

**Issue by gaucho1978** [diydrones/ardupilot#3723]
We need to move the copter at 8m/s with an automatic flight program, but the maximum speed seems to be lower. is it correct? could we achieve a bigger value for the speed?
the parameter PILOT_VELZ_MAX accepts max 500 cm/s
i think that it is needed a parameter for the max descending speed and a parameter for the max ascending speed and the maximum value for this last one should be at least 2000 cm/s

**Comment by magicrub** [comment]
Have you tried a larger value? Many of those limits are not enforced and any value would work.. assuming they're physically possible to achieve by your aircraft.

**Comment by gaucho1978** [comment]
no, i didn't

**Comment by rmackay9** [comment]
In autonomous modes (AUTO, Guided) the vehicle uses the WPNAV_SPEED_UP and WPNAV_SPEED_DN parametes.  As @magicrub says, the mission planner (and other ground stations) may limit them on some screens (like the extended tuning screen) but you can set them directly to anything you want on the Full Parameter List or Full Parameter Tree screens.
There are no upper limits placed within the flight code itself.  Heck, Leonard's copter was doing >30m/s autonomously 2 or 3 years ago at the AVC competition.

**Comment by gaucho1978** [comment]
Thank you. 
Dji has big limits.  ardupilot is still the best.

**Comment by magicrub** [comment]
Randy, shall we change the limit to Mach 1?
