### ISSUE TITLE
Why doesn't use '10hz(gps rate)'?

### ISSUE THREAD

**Issue by kyunghwan** [diydrones/ardupilot#3746]
I use ublox M8N gps. 
I think.. if we modify the settings gps, then we can get the 10hz rate.
Why doesn't use 10hz rate in arducopter code? 
Is there another problem?

**Comment by WickedShell** [comment]
Duplicate of #3717 the reasons that doesn't work quite right yet are listed there, and thats where progress forward will be tracked
