### ISSUE TITLE
Plane: Auto TO heading hold

### ISSUE THREAD

**Issue by GAFletcher** [diydrones/ardupilot#387]
I have been doing auto takeoffs by hand launching my 0.780 Kg falcon wing and was having navigation problems until it reached to alt. I was launching in auto to and switching to manual before it got to far of course. It would fly a big arc until it hit to alt and went to wp 2. I decided today to fix this and I have. The hold_course = ahrs.yaw_sensor was set when you set mode to auto with an auto takeoff
I changed the setting of the hold_course to the point in time when the throttle_suppress is set to false, and it does it just once. 
Tested this and the plane climbed out in a pretty strait line until TO alt was reached. Then to wp2.
This would not be noticed with a wheeled or catapult plane cause it doesn't move after setting to AUTO.

in<attitude.pde>
    if (g_gps != NULL && 
        g_gps->status() == GPS::GPS_OK && 
        g_gps->ground_speed >= 200 && airspeed.get_airspeed_cm() > 200) {
        // we're moving at more than 2 m/s /// Added air speed cause I have flown with a plugged pitot and screwed the nav up.

        // Meant to set hold_course to launch heading when it's actually lunched 
        if(throttle_suppressed == true)  hold_course = ahrs.yaw_sensor;
        
        throttle_suppressed = false;
 
and this

in <commands_logic.pde> in <static bool supress_throttle()>
static bool verify_takeoff()
{
    if (ahrs.yaw_initialised()) {
        if (hold_course == -1) {
            // save our current course to take off
         // GAF EXP rem   hold_course = ahrs.yaw_sensor;  /// moved to throttle suppress
            gcs_send_text_fmt(PSTR("Holding course %ld"), hold_course);
        }
    }

Tested once and worked as intended. Strait out climb in AUTO TO.

**Comment by magicrub** [comment]
since merged/implemented
