### ISSUE TITLE
Copter: set circle radius in flight with Ch6

### ISSUE THREAD

**Issue by andycrap** [diydrones/ardupilot#399]
Would it be possible to add a channel 6 circle radius parameter so that the radius of a circle could be set from the radio like the circle speed can be set.

Thanks. Andy.

**Comment by rmackay9** [comment]
The feature has always been there in master but it was hopelessly broken.  This is fixed with this patch and will go out with AC3.3-rc8.
https://github.com/diydrones/ardupilot/commit/28c722c1574eb833a2c77c6cb1ac9def651274c3
