### ISSUE TITLE
GPS: add parameter, dataflash and/or tlog item indicating gps type

### ISSUE THREAD

**Issue by rmackay9** [diydrones/ardupilot#415]
We need to know if the user is using a low quality GPS such as the mediatek to help get to the bottom of support issues more quickly.

**Comment by WickedShell** [comment]
We do broadcast what driver type was loaded over telemetry, but the message is poorly formatted and not terribly useful. (It just says "  ublox  " or "  nmea  " without even a trailing newline.

I've started talking to @peterbarker about better ways to inject one time messages from the GPS driver (specifically containing what HW version is connected. and potentially what baud rate the GPS driver was initialized on) into the DF logs.

This is becoming more critical as people start posting dual GPS logs with different GPS hardware connected.

**Comment by WickedShell** [comment]
Closing this as done. The driver that is loaded along with what baud rate is selected is logged when the GPS picks a driver. The u-blox driver will also log out the hw/sw version's as well, which might be relevant for some of the other drivers to add.
