### ISSUE TITLE
Plane: Overcomplicated waypoint passed check

### ISSUE THREAD

**Issue by dongfang** [diydrones/ardupilot#426]
The location_passed_point implementation in AP_Math/location.cpp:

<pre>
bool location_passed_point(const struct Location &location,
                           const struct Location &point1,
                           const struct Location &point2)
{
    // the 3 points form a triangle. If the angle between lines
    // point1->point2 and location->point2 is greater than 90
    // degrees then we have passed the waypoint
    Vector2f loc1(location.lat, location.lng);
    Vector2f pt1(point1.lat, point1.lng);
    Vector2f pt2(point2.lat, point2.lng);
    float angle = (loc1 - pt2).angle(pt1 - pt2);
    if (isinf(angle)) {
        // two of the points are co-located.
        // If location is equal to point2 then say we have passed the
        // waypoint, otherwise say we haven't
        if (get_distance(&location, &point2) == 0) {
            return true;
        }
        return false;
    } else if (angle == 0) {
        // if we are exactly on the line between point1 and
        // point2 then we are past the waypoint if the
        // distance from location to point1 is greater then
        // the distance from point2 to point1
        return get_distance(&location, &point1) >
               get_distance(&point2, &point1);
    }
    if (degrees(angle) &gt; 90) {
        return true;
    }
    return false;
}
</pre>

is needlessly complicated. It calculates a vector length (sqrt) and an arcsin without using the result for anything more than comparing it with 90 degrees.

It would suffice to use the sign of the dot product:

<pre>
bool location_passed_point_simple(const struct Location &location,
                           const struct Location &point1,
                           const struct Location &point2)
{
    // the 3 points form a triangle. If the dot product between vectors
    // point2->point1 and point2->location is negative, then we have passed 
    // the waypoint.

    Vector2f destinationToPrevious(point2.lat-point1.lat, point2.lon-point1.lon);
    Vector2f destinationToHere(point2.lat-location.lat, point2.lon-location.lon);

    // * is the Vector2 dot product operator.
    float dotproduct = destinationToPrevious * destinationToHere;

    // if one or both vectors are zero, the dot product will become zero. We avoid never "passing"
    // that situatiuon by just saying dot product zero (zero vectors or exactly 90 degrees) counts as passed.
    return dotproduct &lt;= 0;
}
</pre>

Soren Kuula

**Comment by gmorph** [comment]
This code has been completely re-written since this comment and in fact looks very much like the requested change.  Closing this out.  If anyone objects please let me know.
Thanks, Grant.
