### ISSUE TITLE
Plane: Using do_set_servo and do_digicam_command.

### ISSUE THREAD

**Issue by Freyfaxi** [diydrones/ardupilot#449]
Hi there

I am trying to use the do_set_servo or do_digicam_command in arduplane V.2.74b. To move a servo inflight, so it drops a parachute or an egg on a waypoint. 

I have read the forums pretty well and nothing seems to move the servo. Here is a summary of what I am doing and I would really appreciate any help you can give.

I connect 2x servos as seen on Fig. 1 to the CH5 and A5 as seen on Figs. 2 and 3. Because I am not sure which to use.

![2013-07-16 15 49 53](https://f.cloud.github.com/assets/4981363/812534/96a705c0-eef1-11e2-81b3-f0e4711009b9.jpg)

![2013-07-16 15 36 00](https://f.cloud.github.com/assets/4981363/812527/7f139662-eef1-11e2-979e-fe1a1bd076db.jpg)

![2013-07-16 15 36 10](https://f.cloud.github.com/assets/4981363/812528/88995898-eef1-11e2-8dee-76253fa26a1d.jpg)

I am testing this using the mission planner then walking around the parking lot where I work. In Fig. 4 i show how my way points are set in the MP. Fig 5 shows the path I am walking. Then The Fig 6 shows the shutter settings for the do_digicam_command. If somebody can tell me what I am missing and why the servos don't move would be highly appreciated.

![waypoints](https://f.cloud.github.com/assets/4981363/812541/a51e81dc-eef1-11e2-8c2d-c071f83e854e.PNG)

![sche waypoints](https://f.cloud.github.com/assets/4981363/812546/aaf2a034-eef1-11e2-894c-74e78fa27677.PNG)

![shutter setting](https://f.cloud.github.com/assets/4981363/812548/aff78a72-eef1-11e2-99bf-fee2a6eac92b.PNG)

I feel like I am missing something, like enabling the servo outputs in the advanced parameters.

Best Regards

Freyfaxi.

**Comment by gmorph** [comment]
Closing this as working as we used it in the outback challenge.  If anyone objects please let me know.
Thanks, Grant.
