### ISSUE TITLE
Copter: flip when set_wp

### ISSUE THREAD

**Issue by meoudon** [diydrones/ardupilot#484]
I have found problem if you click SET_WP in actions windows then arm and rising throttle up. Motor will shoot to the air and flip to ground.

My procedure:-
- Open up
- Save waypoints in planner
- Fly Ok.
- complete mission and land
- disarm.
- set SET_WP 1.
- ARM
- Rising throttle and goto hell.

I'm looking status windows ch1-ch4 outs. if you don't touch set_wp button is work ok. But if you click set_wp in actions windows. when you arm and rising throttle slow in stabilizer mode ch1-4 out go over 1600 us random channel.

**Comment by gmorph** [comment]
This is a support issue - not a software issue.  Closing.
Thanks, Grant.
