### ISSUE TITLE
Feature request: PWM RSSI support on PWM input channel 8

### ISSUE THREAD

**Issue by cmanley** [diydrones/ardupilot#503]
Some receivers output RSSI as servo pulses. E.g. EzUHF, FrSky.
It would be nice if the PWM RSSI could be fed straight into channel 8 (or another assignable) and that this feature can be activated in Mission Planner.

Then perhaps MinimOSD would be able to read the RSSI message the way it does now from analogue A0.

I have no idea how complicated this would be to achieve code-wise.
Thanks anyway.

**Comment by StewLG** [comment]
I believe this patch should work for folks:

https://github.com/diydrones/ardupilot/pull/2770

It handles inversion like with EzUHF, and high and low ranges so you can get a clear 0-100% value, so I think that covers everything people were asking for here. If not set me straight.

**Comment by magicrub** [comment]
Closed per @StewLG 's comment
