### ISSUE TITLE
Feature request: Log GPS VDOP

### ISSUE THREAD

**Issue by larsen10001** [diydrones/ardupilot#512]
I would like APM to log The GPS The vertical dilution of precision so it is possible to get an estimate of the vertical precision. My global would be to use this as a covariance input in altitude kalman filter.

**Comment by gmorph** [comment]
Closing this as working.  Any objections please let me know.
Thanks, Grant.

**Comment by WickedShell** [comment]
This isn't done in the GPS driver, so I'm pretty confident in saying this
isn't done. (We also don't report it over mavlink at the moment ) I was
planning to add at least the mavlink part since it's part of the message
and ublox is now receiving the information.

**Comment by gmorph** [comment]
Re-opening and I will check again if this is done or not.  I REALLY appreciate you following up - thanks!

**Comment by WickedShell** [comment]
See #2816

**Comment by gmorph** [comment]
Closing this out as it will now be tracked via the PR above.
Thanks, Grant.
