### ISSUE TITLE
Plane Bug?: Programmed 1 Turns in Loiter, but got 4 instead.

### ISSUE THREAD

**Issue by iskess** [diydrones/ardupilot#585]
Since I can't post photos or attachments on Github, please read my post here: 
http://diydrones.com/forum/topics/plane-i-programmed-1-loiter-turn-and-got-4

To set up my approach I programmed one loiter turn at WP27, but when the plane arrived it did 4 turns before continuing on to a nearly perfect autolanding.
 
Also, look at WP27 and notice that the number 25 showed up in a blank column after reading back the flight plan from the APM. What does this mean? Is it related to the unexpected loiter behavior?

**Comment by gmorph** [comment]
Support issue - not a software issue.  Closing.  Any objections please let me know.
Thanks, Grant.
