### ISSUE TITLE
Plane: PWM inputs > 1905 glitching

### ISSUE THREAD

**Issue by chapman** [diydrones/ardupilot#587]
My APM2.5+ running ArduPlane v2.74b doesn't seem to like PWM inputs > 1905, it oscillates madly between a low value (something around 900-950) and that high value.

I first saw this when setting up mixes for aileron->rudder, and flapperons. The individual channel was ok (e.g. aileron) but when the mix pushes it above 100% (e.g. aileron-rudder mix plus some rudder input) it starts going crazy, leading to a control surface reversal which could end very badly (it's unlikely the pilot would think to ease off on the control which starts giving the reversed output).

I first saw it with a Spektrum DX7+AR6200 receiver, now reproduced with the FrSky Taranis+X8R.

Here's a video showing the problem:
https://vimeo.com/75941082

**Comment by gmorph** [comment]
Support issue and not a software bug.  Closing.  Any objections please let me know.
Thanks, Grant.
