### ISSUE TITLE
Plane: Commanding a NAV waypoint outside of Auto mode has unintended effect.

### ISSUE THREAD

**Issue by mday299** [diydrones/ardupilot#620]
This was encountered first during field flights.  We wanted to modify a mission while the plane was still in flight, so we handed control to the pilot (Manual mode) whilst we were fiddling with nav waypoints.  After the mission modification (still in Manual) we set the nav waypoint we wished to start with (e.g., wp 3).  Then we had the pilot manually fly a good approach to this waypoint and switch to Auto.  Upon switching to Auto, the plane did a crazy turn and headed for waypoint 2.

Similar tests revealed the plane always flies one waypoint previous that the intended waypoint if the waypoint change is specified during Manual mode.  If waypoint 1 is specified then something quite strange happens: plane proceeds to waypoint 0 and loiters (won't do the mission at all without another waypoint command)!

This was all with the Mission Planner GCS.  I later tested this in SITL with MAVProxy and similar behavior results.

I think I have narrowed this down to a line of code in APM:Plane in commands_process.pde ... the update_commands function does not allow commands to be updated outside of AUTO mode.  When nav_command_index is decremented by the change_command method when the "change waypoint" command is sent, process_next_command never gets called and nav_command_index is stuck one index behind where it needs to be.

I will submit a patch shortly.

**Comment by magicrub** [comment]
fixed long ago
