### ISSUE TITLE
Plane: Extreme altitude drop after fence return action.

### ISSUE THREAD

**Issue by goochpw** [diydrones/ardupilot#629]
Please see this: 
http://diydrones.com/group/apmusergroup/forum/topics/fence-breach-and-return-drop-in-altitude?xg_source=activity
The attached log shows mission completed 2 times... then a manual fence breach.  Upon returning and RTL, it drops altitude almost to the ground.

**Comment by gmorph** [comment]
This was a known bug and has now been resolved.  If you can replicate please post to the support forums with logs.
Thanks, Grant.
