### ISSUE TITLE
Copter: known issues when flying only with Tablet

### ISSUE THREAD

**Issue by rmackay9** [diydrones/ardupilot#656]
This is a general purpose issue to capture issues to do with flying with only a Tablet ground station as a user interface (i.e. no TX/RX).

As more non-trivial issues are found we should probably create separate issues and assign them to the "AC with Tablet" milestone.

Known Issues:
1. the GCS needs to override the RC controls and raise the throttle above zero to initiate a mission.
2. the GCS needs to clear the RC overrides to allow the pilot to retake control with the TX/RX.  So for example if you yank the 3dr radio out of the ground station it should perform an RTL (if GCS_Failsafe is enabled) but really a pilot should be able to retake control with the transmitter.  Someone should test this!
3. only failback to the TX/RX if the TX/RX is not in failsafe.
4. the current throttle failsafe (aka radio failsafe) probably gets confused by the combination of gcs overrides and real TX/RX input.  The two should be separated so that a loss of contact with the GCS leads to a GCS failsafe, a loss of TX/RX triggers a throttle failsafe.  loss of GCS should never lead to a radio failsafe
5. GCS failsafe is disabled by default (because it hasn't been tested thoroughly)
6. do not allow people to fly ACRO with tablet only (maybe not SPORT either)

**Comment by R-Lefebvre** [comment]
Is this Issue "stale"?  I was reading through this, took a minute to realize it was over a year old, and I think some/most of these problems are fixed.  Maybe we can close this catch-all issue, and track whatever is outstanding in separate issues?

**Comment by rmackay9** [comment]
@R-Lefebvre, yes, totally agree. closing!
