### ISSUE TITLE
Copter: Land desired altitude logging

### ISSUE THREAD

**Issue by lthall** [diydrones/ardupilot#674]
We should change this:

    case THROTTLE_LAND:
        // landing throttle controller
        get_throttle_land();
        set_target_alt_for_reporting(0);
        break;
    }

to this:

    case THROTTLE_LAND:
        // landing throttle controller
        get_throttle_land();
        set_target_alt_for_reporting(controller_desired_alt);
        break;
    }

The important bit being that we log controller_desired_alt not zero.

**Comment by R-Lefebvre** [comment]
No longer valid.  Code no longer exists.
