### ISSUE TITLE
Ail mix to elvator

### ISSUE THREAD

**Issue by JetA1** [diydrones/ardupilot#681]
On the 2.6 I found a little concerning programming in the latest version of Arduplane. 
The standard value mixing of aileron to elevator if a/c is banking is default =1 and recommended by the description. I found out that at only 5° Bank I have full elevator up, this would lead directly to a crash. (Airspeed sensor disabled). With a setting of 0.01 it looks much better with only about 1mm up at same bank. Did not test fly yet. 
Value of mixing of aileron to elevator is deeply buried in the system, it should show up in the PID´s page as it is an important setting. 
As it is programmed any disturbance of the roll will input the elevator which is not necessary and will lead to “swing” the system. It should only be applied when the APM NAV or User commands a turn. Wing levelling should only command aileron. 
Value of mixing rudder to aileron for coordinated turns should show up in the PID page as well, has the same importance as the above. 
b.r.
Wolfgang

**Comment by gmorph** [comment]
This code has been updated and the mixing is now very different.  Closing out but if anyone objects please let me know.
Thanks, Grant.
