### ISSUE TITLE
Plane wind estimation

### ISSUE THREAD

**Issue by Gabeki17** [diydrones/ardupilot#687]
Hi,

I have posted about this at the forum also: http://ardupilot.com/forum/viewtopic.php?f=77&t=4879

I think in a way it is a bug;

When i fly in level, it shows the right value for wind speed.

But when i climb or descend, it increases depending on the angle my plane climbs or descends.

Like theoretically if i dive 90° to the ground, my GS is 0, but as my AS let's say 100 km/h than it would show a 100km/h wind, even if there is none. If the angle is 45° than 50 km/h, etc.

Thx,
Gábor

**Comment by gmorph** [comment]
The wind estimation has changed since this issue was logged.  Closing this out but if it can be replicated please re-open the issue and post dataflash and tlogs.
Thanks, Grant.
