### ISSUE TITLE
Copter: support retractable landing gear

### ISSUE THREAD

**Issue by rmackay9** [diydrones/ardupilot#691]
Request from Marco.
We should probably:
1. assign a ch7/ch8 switch to extend/retract so they can be used in manual flight modes.
2. ensure they're down in the last stage of a LAND mission or RTL
3. during a take-off in AUTO retract them
4. allow them to be deployed/retracted during a mission, maybe using the do-set-servo command?

**Comment by R-Lefebvre** [comment]
I'm taking responsibility for this work.  Will be included in AC 3.3.  Will make it a library so it's usable by Plane.

**Comment by lvale** [comment]
Hi Robert

Please consider that some using Arducopter also need, and use, retractable landing gears on multicopters. I'll sendo you later how I'm using on my Hexa.

Brgds

Luìs

Em 03/01/2015 14:03, Robert Lefebvre <notifications@github.com> escreveu:
I'm taking responsibility for this work.  Will be included in AC 3.3.  Will make it a library so it's usable by Plane.

---

**Comment by rmackay9** [comment]
merged into master so will go out with AC3.3.
