### ISSUE TITLE
Copter: Indoor flight Ch7/Ch8 switch

### ISSUE THREAD

**Issue by lthall** [diydrones/ardupilot#702]
This would facilitate safe flight indoors by disabling all GPS related features, Loiter, Auto, Fence, and ... anything I missed. Except maybe altitude fence (but I would keep it simple and just disable all fence features).

**Comment by rmackay9** [comment]
This is the oldest reporting of this request but there's more detail in this other one.
https://github.com/diydrones/ardupilot/issues/1152
