### ISSUE TITLE
Arduplane autoland does not work in HIL simulation

### ISSUE THREAD

**Issue by SamuMantyniemi** [diydrones/ardupilot#72]
When the next waypoint is "LAND", arduplane idles the throttle and lets the plane glide to the ground continuing the trajectory it had before the waypoint. According to Wiki the landing is supposed to work very differently.

Here are descriptions of the problem:

http://www.diydrones.com/forum/topics/apm-planner-autoland-setup-problem
http://www.diydrones.com/forum/topics/arduplane-autoland

**Comment by gmorph** [comment]
This is working in the current Plane release.
If you believe this is not the case please let me know.
Thanks, Grant.
