### ISSUE TITLE
Feature request. Could this be use for add FailSalfe feature to Turnigy 9x stock receiver?

### ISSUE THREAD

**Issue by villamany** [diydrones/ardupilot#786]
Hi everyone, i just do some checking with my oscilloscope and my three turnigy 9X8Cv2 stock receivers (purchased on different dates).

All match same behavior maybe can be used to trigger any APM failsafe function?

After turning off the transmitter or directly extracting the transmitter module, immediately causes all the PWM trains from channels 1,2,3,6,7,8 go to GND (duty 0ms), while channels 4,5 remain the same duty cycle before turning off.

All channels recover the appropriate values ​​when the transmitter back on.

For example channels 3 and 4 could be checked and enter into fail safe mode when ch3 go to 0ms and ch4 go >800ms?

Thanks...

**Comment by iskess** [comment]
No Pulse on Ch3 (Thr) = failsafe. 
It looks like this is already implemented for Copter, could we get it on Plane?

**Comment by gmorph** [comment]
There is already a parameter for this:
http://plane.ardupilot.com/wiki/arduplane-parameters/#throttle_failsafe_value_arduplanethr_fs_value
I use this with my Turnigy receivers as 0PWM is below any value I put in that parameter.
I'm going to close this.  If anyone objects please let me know.
Thanks, Grant.
