### ISSUE TITLE
Rover: AUTO mode "negative" throttle nudge goes full throttle

### ISSUE THREAD

**Issue by mikerob** [diydrones/ardupilot#840]
Minimum throttle stick input in AUTO gives maximum throttle output if RC3_MIN is not set to RC3_TRIM. 

Radio.pde: 61

	channel_throttle->servo_out = channel_throttle->control_in;
	if (abs(channel_throttle->servo_out) > 50) {
        throttle_nudge = (g.throttle_max - g.throttle_cruise) * ((fabsf(channel_throttle->norm_input())-0.5) / 0.5);
	} else {
		throttle_nudge = 0;
	}

The code seems to check whether I'm in the top or bottom 25% of my travel (>50% in either direction then calculates a proportional nudge of (max-cruise)*(position within that 50%).  This happily gives a positive nudge when you push the stick forward,as intended.

However, the "fabsf(channel_throttle->norm_input())" give a POSITIVE nudge at negative throttle.  It looks like there may need to be two cases - one for servo_out>50 (for which the current code would be fine), and one for servo_out<50 which would remove the fabsf, and change to "channel_throttle->norm_input()+0.5". This would then give a negative nudge.

It only occurs if RC3_MIN is set below RC3_TRIM (e,g, RC3_MIN=1000, RC3_TRIM=1500), which may not occur that often - my asumption is that if you have RC3_MIN and RC3_TRIM set the same (say at 1000), then servo_out never goes negative.

I have a log file that shows this, if someone can advise how to upload it. I can also upload to dropbox, or the ardupilot or diydrones forums.

**Comment by gmorph** [comment]
Fixed by the PR above.  
Really appreciate you raising the issue - thanks!
Thanks, Grant.

**Comment by mikerob** [comment]
No problem. It was a bit frustrating that an actual bug (not feature request) sat for so long, but rover has never been the highest priority. Cest la vie. 

Mike Roberts
Nova Systems

0420 371 654
