### ISSUE TITLE
Feature request: Audio telemetry

### ISSUE THREAD

**Issue by DerFlash** [diydrones/ardupilot#863]
Given the information from:
- here: http://diydrones.com/profiles/blogs/open-source-audio-telemetry
- here: http://www.rcgroups.com/forums/showthread.php?t=1157558
- and here: https://code.google.com/p/opendiyantracker/

Could we use some of the pins (motor 8 pin when not using it?!) to output the Mavlink data packets wrapped into some audio protocol like the projects above do? This way we could have a very easy way to use those data packets on a small antenna tracker equipped with some small arduino board.
I know that would be possible using some external arduino board on the copter. But why add extra hardware when already we have everything we need.

Kind regards
Björn

**Comment by minid33** [comment]
I'd like to add my support for this, it would be a great enhancement to the antenna tracker project.

As I understand things now in long range applications, many long range LRS systems use 433MHz, which is also used by the Telemetry module.

Additionally this could reduce the complexity and weight of running an antenna tracker setup, requiring the vehicle to have one less antenna and replacing the telemetry module with a wire into the video TX.

On the ground side there wouldn't need to be an antenna for the telemetry if the APM or pixhawk on the ground can decode the audio.

**Comment by squilter** [comment]
This can probably be done without modifications to the flight code.  You'd just need to get the mavlink stream (probably from the pixhawk into a companion computer), and then just pipe the data into a software modem (like [minimodem](http://www.whence.com/minimodem/)).  Now just hook up your audio transmitter to the audio out on the companion computer.

The above method probably wouldn't be too hard to figure out.  I don't think that pixhawk has the horsepower to be a modem.

**Comment by squilter** [comment]
Just tried it.  This is pretty cool.

`mavproxy.py --master=127.0.0.1:14550 --cmd="watch *" | minicom --tx 1000`

Might want to turn down the stream rates.
