### ISSUE TITLE
Copter: auto tune of yaw rate and stab gains

### ISSUE THREAD

**Issue by rmackay9** [diydrones/ardupilot#874]
We already have auto tuning of roll and pitch rate and stab terms with AC3.1.  The hope is to extend this to include Yaw (and perhaps altitude hold).

**Comment by nicegraham** [comment]
+1!

**Comment by lthall** [comment]
Hi Matthew,
I would like to chat if we can set it up. I am on google plus as Leonard Hall and my skype name is leonard_hall.

**Comment by rmackay9** [comment]
This is in master now and available as part of AC3.3 beta testing.  Any issues found should be raised (most likely with Leonard) on this diydrones discussion thread: http://diydrones.com/forum/topics/copter-3-3-beta-testing
