### ISSUE TITLE
Request for User settable Camera Stabilize Pitch and Roll Servo Scalars

### ISSUE THREAD

**Issue by ghost** [diydrones/ardupilot#88]
I have read the gimbal compensation issue response below and now understand that it is possible to adjust the servo rate, but the method provided is anything but intuitive (or clearly explained) and It still seems reasonable to me that both pitch and roll could each use a single (multiplier) type value to provide compensation far more naturally and understandably than the current method. 

The values could be tied together or possibly all that is needed is a clearer explanation of how to do this.

The problem is not centering or limits it is that deviation from copter level causes either too much or too little compensation at the camera.

The Auto Stabilize on the camera gimbals roll and pitch axes is a great thing, but servo movement to degrees of camera pitch or tilt is not a fixed value.

To properly stabilize it would be very convenient to have user settable Scalar values for the Roll and Pitch axes of the camera gimbal. 

This would make it easy to dial in the amount of servo correction necessary for a given amount of air frame roll and pitch. Right now it needs to be done mechanically with servo arm length and position. 

I believe you would need  a simple multiplier value for roll and a separate one for pitch.

They could be Plus or Minus and should be settable away from the default of 1 in the Mission Planner Camera Gimbal setting section.

This would be much easier to dial in than by attempting to perfectly set up a 1 to 1 mechanical linkage as is required now.

**Comment by gmorph** [comment]
With all the wiki documentation updates and changes in this space I am going to mark this issue as resolved.  If anyone hates that please re-open this issue.
Thanks, Grant.
