### ISSUE TITLE
Mavlink status text sent with wrong severities

### ISSUE THREAD

**Issue by DonLakeFlyer** [diydrones/ardupilot#901]
Over in QGroundControl land we just updated such that status text messages show up in different colors based on severity. When we did that we noticed that ArduPilot boards are pushing out what is thought to be low severity messages but come through as high severity alerts. The reason for this is in GCS_MAVLink.h there is a gcs_severity enum which is used to set status text mavlink message severity, when in fact the mavlink provided MAV_SEVERITY enum should be used (in common.h). If you look at the two, SEVERITY_LOW=1 maps to MAV_SEVERITY_ALERT which is the opposite of what is meant. Not sure why the mavlink enum isn't being used directly.

**Comment by rmackay9** [comment]
Copter, Tracker, Rover are done.  Plane and some libs stlil to be done but getting close.

**Comment by rmackay9** [comment]
This change will not go out with Copter-3.3 so removed that milestone

**Comment by squilter** [comment]
I can create a PR for the AC3.3 branch with the changes, if you'd like.

**Comment by rmackay9** [comment]
@squilter, I think we will leave it out of Copter-3.3.  We have to draw the line somewhere and the GCS changes required are not ready yet.

**Comment by magicrub** [comment]
Speaking of drawing the line, at what point do we start calling it 3.4? :)

**Comment by rmackay9** [comment]
for Copter, master is currently renamed to Copter-3.4-dev...

**Comment by squilter** [comment]
fixed with #2757
