### ISSUE TITLE
Rover: DO_CHANGE_SPEED responds to "Airspeed" rather than "Groundspeed"

### ISSUE THREAD

**Issue by mikerob** [diydrones/ardupilot#913]
In commands_logic.pde, the switch for DO_CHANGE_SPEED looks only for p1=0, which according to the MAVLINK wiki (http://code.google.com/p/ardupilot-mega/wiki/MAVLink) corresponds to airspeed.
```
static void do_change_speed(const AP_Mission::Mission_Command& cmd){	
    switch (cmd.p1){		
        case 0:			
            if (cmd.content.speed.target_ms > 0) {		
		         g.speed_cruise.set(cmd.content.speed.target_ms);                
                 gcs_send_text_fmt(PSTR("Cruise speed: %.1f m/s"), g.speed_cruise.get());           
            }			
            break;	
    }
```
This means that if you follow the MAVLINK wiki and/or the Mission Planner column heading and enter "1" for a ground speed change, you end up setting a command point that does nothing.

Seems like a simple fix to either document explicitly for Rover, or make both airspeed and groundspeed changes applicable to cruise speed for Rover.

For reference, Copter doesn't even check whether air or ground speed was specified - only Plane cares.

The Mission Planner page (http://copter.ardupilot.com/wiki/planning-a-mission-with-waypoints-and-events/) seems wrong regardless with respect to the precise format of the DO_CHANGE_SPEED command anyway.

**Comment by squilter** [comment]
Looks like this is fixed.
