### ISSUE TITLE
Arduplane: heartbeat.basic_mode STAB bit set in MANUAL flight mode

### ISSUE THREAD

**Issue by sgofferj** [diydrones/ardupilot#95]
I noticed that Arduplane 2.69 sets the STAB bit in hearbeat.basic_mode
when the APM is in MANUAL flight mode. 2.68 did not do that and as far as I
understand the MAVLink specs, it shouldn't.

**Comment by gmorph** [comment]
This is working in the current Plane release.
If you believe this is not the case please let me know.
Thanks, Grant.
