### ISSUE TITLE
Camera: add Absolute Alt (GPS Alt) to CAM messages

### ISSUE THREAD

**Issue by bbasso** [diydrones/ardupilot#960]
It looks like the altitude being written in the CAM messages is the GPS relative altitude and not AGL.  Is that right?

https://github.com/diydrones/ardupilot/blob/master/ArduPlane/Log.pde#L251

It would of course be much better to subtract the home altitude and have AGL for Survey purposes.

**Comment by rmackay9** [comment]
I wonder if we can close this now that absolute alt is in the CAM message... or are we holding out for AGL?

**Comment by WickedShell** [comment]
Closing as we are recording the GPS altitude, the ekf altitude, and the relative altitude.
